// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, tenantID string, resp *models.GatewayResponse) *models.GatewayResponse, error
	EnsureTable(ctx context.Context) error
	GetByID(ctx context.Context, tenantID id string) *models.GatewayResponse, error
	List(ctx context.Context, tenantID string, q models.ListQuery) []models.GatewayResponse, int, error
}
