// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for notification-management.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/notification-management/models"
)

// ServiceInterface defines the interface for the notification-management service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateNotificationManagementRequest) (*models.NotificationManagement, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.NotificationManagement, error)
	List(ctx context.Context, tenantID string) ([]models.NotificationManagement, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateNotificationManagementRequest) (*models.NotificationManagement, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
