// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/tracing/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	CreateSpan(ctx context.Context, span *models.TraceSpan) error
	GetTrace(ctx context.Context, tenantID, traceID string) ([]models.TraceSpan, error)
	SearchTraces(ctx context.Context, tenantID string, req *models.TraceSearchRequest) ([]models.TraceSpan, error)
	CreateSamplingConfig(ctx context.Context, config *models.TraceSamplingConfig) error
	UpsertSamplingConfig(ctx context.Context, tenantID, serviceName string, sampleRate float64, maxSpansPerSec int, enabled bool) (*models.TraceSamplingConfig, error)
	GetAllSamplingConfigs(ctx context.Context, tenantID string) ([]models.TraceSamplingConfig, error)
	CreateOtelConfig(ctx context.Context, config *models.OtelCollectorConfig) error
	GetOtelConfig(ctx context.Context, tenantID, id string) (*models.OtelCollectorConfig, error)
	GetOtelConfigs(ctx context.Context, tenantID string, configType string) ([]models.OtelCollectorConfig, error)
	UpdateOtelConfig(ctx context.Context, tenantID, id string, updates map[string]interface{}) error
	DeleteOtelConfig(ctx context.Context, tenantID, id string) error
}
