// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateOtelConfig(ctx context.Context, config *models.OtelCollectorConfig) error
	CreateSamplingConfig(ctx context.Context, config *models.TraceSamplingConfig) error
	CreateSpan(ctx context.Context, span *models.TraceSpan) error
	DeleteOtelConfig(ctx context.Context, tenantID id string) error
	GetAllSamplingConfigs(ctx context.Context, tenantID string) []models.TraceSamplingConfig, error
	GetOtelConfig(ctx context.Context, tenantID id string) *models.OtelCollectorConfig, error
	GetOtelConfigs(ctx context.Context, tenantID string, configType string) []models.OtelCollectorConfig, error
	GetTrace(ctx context.Context, tenantID traceID string) []models.TraceSpan, error
	SearchTraces(ctx context.Context, tenantID string, req *models.TraceSearchRequest) []models.TraceSpan, error
	UpdateOtelConfig(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpsertSamplingConfig(ctx context.Context, tenantID serviceName string, sampleRate float64, maxSpansPerSec int, enabled bool) *models.TraceSamplingConfig, error
}
