// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateDeployment(ctx context.Context, d *models.Deployment) error
	CreateFunction(ctx context.Context, f *models.Function) error
	CreateFunctionLog(ctx context.Context, l *models.FunctionLog) error
	CreateTrigger(ctx context.Context, t *models.Trigger) error
	DeleteFunction(ctx context.Context, tenantID id string) bool, error
	DeleteTrigger(ctx context.Context, tenantID id string) bool, error
	EvaluateAutoScaling(ctx context.Context, tenantID string) []models.AutoScalingRecommendation, error
	FunctionExists(ctx context.Context, tenantID functionID string) bool, error
	GetAggregateMetrics(ctx context.Context, tenantID string) *models.AggregateMetrics, error
	GetFunction(ctx context.Context, tenantID id string) *models.Function, error
	GetFunctionLogs(ctx context.Context, tenantID functionID string, q models.GetFunctionLogsQuery) []models.FunctionLog, error
	GetFunctionMetrics(ctx context.Context, tenantID functionID string) *models.FunctionMetric, error
	GetFunctionsForAutoScaling(ctx context.Context, tenantID string) []models.Function, error
	GetTrigger(ctx context.Context, tenantID id string) *models.Trigger, error
	ListDeployments(ctx context.Context, tenantID functionID string) []models.Deployment, error
	ListFunctions(ctx context.Context, tenantID string, q models.ListFunctionsQuery, limit offset int) []models.Function, error
	ListTriggers(ctx context.Context, tenantID string, q models.ListTriggersQuery) []models.Trigger, error
	UpdateFunction(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpsertFunctionMetric(ctx context.Context, tenantID functionID string, invocations int64, avgDurationMs float64, errorCount int64, errorRate float64, memoryUsageMB float64) error
}
