// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/serverless/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	CreateFunction(ctx context.Context, f *models.Function) error
	GetFunction(ctx context.Context, tenantID, id string) (*models.Function, error)
	ListFunctions(ctx context.Context, tenantID string, q models.ListFunctionsQuery, limit, offset int) ([]models.Function, error)
	UpdateFunction(ctx context.Context, tenantID, id string, updates map[string]interface{}) error
	DeleteFunction(ctx context.Context, tenantID, id string) (bool, error)
	CreateDeployment(ctx context.Context, d *models.Deployment) error
	ListDeployments(ctx context.Context, tenantID, functionID string) ([]models.Deployment, error)
	CreateFunctionLog(ctx context.Context, l *models.FunctionLog) error
	GetFunctionLogs(ctx context.Context, tenantID, functionID string, q models.GetFunctionLogsQuery) ([]models.FunctionLog, error)
	UpsertFunctionMetric(ctx context.Context, tenantID, functionID string, invocations int64, avgDurationMs float64, errorCount int64, errorRate float64, memoryUsageMB float64) error
	GetFunctionMetrics(ctx context.Context, tenantID, functionID string) (*models.FunctionMetric, error)
	GetAggregateMetrics(ctx context.Context, tenantID string) (*models.AggregateMetrics, error)
	CreateTrigger(ctx context.Context, t *models.Trigger) error
	GetTrigger(ctx context.Context, tenantID, id string) (*models.Trigger, error)
	ListTriggers(ctx context.Context, tenantID string, q models.ListTriggersQuery) ([]models.Trigger, error)
	DeleteTrigger(ctx context.Context, tenantID, id string) (bool, error)
	EvaluateAutoScaling(ctx context.Context, tenantID string) ([]models.AutoScalingRecommendation, error)
	GetFunctionsForAutoScaling(ctx context.Context, tenantID string) ([]models.Function, error)
	FunctionExists(ctx context.Context, tenantID, functionID string) (bool, error)
}
