apiVersion: v1
kind: Service
metadata:
  name: orion-artifact-svc
  namespace: orion
  labels:
    app: orion-artifact-svc
    component: artifact-service
spec:
  type: ClusterIP
  ports:
    - name: http
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      port: 80
      targetPort: 3014
      protocol: TCP
  selector:
    app: orion-artifact-svc
