// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for disaster-recovery.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/disaster-recovery/models"
)

// ServiceInterface defines the interface for the disaster-recovery service.
type ServiceInterface interface {
	CreatePlan(ctx context.Context, tenantID string, req models.CreateDisasterPlanRequest) (*models.DisasterPlan, error)
	GetPlan(ctx context.Context, tenantID, id string) (*models.DisasterPlan, error)
	ListPlans(ctx context.Context, tenantID string, limit, offset int) (*models.ListPlansResponse, error)
	ListRuns(ctx context.Context, tenantID, planID string) ([]models.RecoveryRun, error)
	RunPlan(ctx context.Context, tenantID, planID string) (*models.RecoveryRun, error)
	UpdatePlan(ctx context.Context, tenantID, id string, req models.UpdateDisasterPlanRequest) (*models.DisasterPlan, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
