// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for apm.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the apm service.
type ServiceInterface interface {
	Create(ctx context.Context, req *models.CreateRequest, tenantID string) (*models.ApmEntry, error)
	Delete(ctx context.Context, id, tenantID string) (bool, error)
	Get(ctx context.Context, id, tenantID string) (*models.ApmEntry, error)
	List(ctx context.Context, tenantID string) ([]models.ApmEntry, error)
	Update(ctx context.Context, id, tenantID string, req *models.UpdateRequest) (*models.ApmEntry, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
