apiVersion: v1
kind: ServiceAccount
metadata:
  name: orion-deploy-svc
  namespace: orion
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orion-deploy-svc
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orion-deploy-svc-binding
roleRef:
  kind: Role
  name: orion-deploy-svc
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: orion-deploy-svc
    namespace: orion