// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CountVersions(ctx context.Context, tenantID modelID string) int, error
	CreateCanary(ctx context.Context, c *models.CanaryConfig) error
	CreateModel(ctx context.Context, m *models.AIModel) error
	CreateVersion(ctx context.Context, v *models.ModelVersion) error
	DeleteModel(ctx context.Context, tenantID modelID string) error
	GetCanary(ctx context.Context, tenantID modelID string) *models.CanaryConfig, error
	GetModel(ctx context.Context, tenantID modelID string) *models.AIModel, error
	GetProductionVersions(ctx context.Context, tenantID modelID string) []models.ModelVersion, error
	GetVersion(ctx context.Context, tenantID modelID versionID string) *models.ModelVersion, error
	GetVersionsByModel(ctx context.Context, tenantID modelID string) []models.ModelVersion, error
	ListModels(ctx context.Context, tenantID string, q models.ListModelsQuery) []models.AIModel, int, error
	ListVersions(ctx context.Context, tenantID modelID string, q models.ListVersionsQuery) []models.ModelVersion, int, error
	ModelExists(ctx context.Context, tenantID name string) bool, error
	UpdateCanary(ctx context.Context, tenantID modelID string, enabled bool, status models.CanaryStatus) error
	UpdateModel(ctx context.Context, tenantID modelID string, displayName *string, description *string, tagsJSON metadataJSON string) *models.AIModel, error
	UpdateModelCurrentVersion(ctx context.Context, tenantID modelID version string, status models.ModelStatus) error
	UpdateVersion(ctx context.Context, tenantID versionID string, environment models.Environment, status models.ModelStatus, promotedAt *int64, promotedBy *string) error
	UpdateVersionDeprecated(ctx context.Context, tenantID versionID string, deprecatedAt *int64) error
}
