// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for capacity.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/capacity/models"

	"github.com/gin-gonic/gin"
)

// ServiceInterface defines the interface for the capacity service.
type ServiceInterface interface {
	AddTag(ctx context.Context, tenantID, id, tag string) (gin.H, error)
	Approve(ctx context.Context, tenantID, id string) (gin.H, error)
	BatchCreate(ctx context.Context, tenantID string, req []models.CreateRequest) (gin.H, error)
	CheckCompatibility(ctx context.Context, tenantID, id string) (gin.H, error)
	Configure(ctx context.Context, tenantID string, config gin.H) (gin.H, error)
	Create(ctx context.Context, tenantID string, req models.CreateRequest) (*models.Record, error)
	Delete(ctx context.Context, tenantID, id string) error
	DeleteTag(ctx context.Context, tenantID, id, tag string) (gin.H, error)
	Deploy(ctx context.Context, tenantID string, id string) (gin.H, error)
	DeregisterModel(ctx context.Context, tenantID, id string) (gin.H, error)
	DisablePlugin(ctx context.Context, tenantID, id string) (gin.H, error)
	EnablePlugin(ctx context.Context, tenantID, id string) (gin.H, error)
	EnforcePolicy(ctx context.Context, tenantID, id string) (gin.H, error)
	Escalate(ctx context.Context, tenantID, id string) (gin.H, error)
	Evaluate(ctx context.Context, tenantID string, id string) (gin.H, error)
	Forecast(ctx context.Context, tenantID string) (gin.H, error)
	Get(ctx context.Context, tenantID, id string) (*models.Record, error)
	GetBranchStatus(ctx context.Context, tenantID, branch string) (gin.H, error)
	GetByUser(ctx context.Context, tenantID, userID string) ([]models.Record, error)
	GetConfig(ctx context.Context, tenantID, id string) (gin.H, error)
	GetCoverage(ctx context.Context, tenantID, id string) (gin.H, error)
	GetHistory(ctx context.Context, tenantID string) ([]models.Record, error)
	GetLineage(ctx context.Context, tenantID, id string) (gin.H, error)
	GetLogs(ctx context.Context, tenantID, id string) ([]models.Record, error)
	GetMetrics(ctx context.Context, tenantID, id string) (gin.H, error)
	GetPlugin(ctx context.Context, tenantID, id string) (*models.Record, error)
	GetResults(ctx context.Context, tenantID string) ([]models.Record, error)
	GetStats(ctx context.Context, tenantID string) (gin.H, error)
	GetStatus(ctx context.Context, tenantID, id string) (gin.H, error)
	GetStatusMiddleware(ctx context.Context, tenantID string) (gin.H, error)
	GetUtilization(ctx context.Context, tenantID string) (gin.H, error)
	List(ctx context.Context, tenantID string) ([]models.Record, error)
	ListAlerts(ctx context.Context, tenantID string) ([]models.Record, error)
	ListArtifacts(ctx context.Context, tenantID string) ([]models.Record, error)
	ListExperiments(ctx context.Context, tenantID string) ([]models.Record, error)
	ListHistories(ctx context.Context, tenantID string) ([]models.Record, error)
	ListModels(ctx context.Context, tenantID string) ([]models.Record, error)
	ListPending(ctx context.Context, tenantID string) ([]models.Record, error)
	ListPipelines(ctx context.Context, tenantID string) ([]models.Record, error)
	ListPlugins(ctx context.Context, tenantID string) ([]models.Record, error)
	ListSchemas(ctx context.Context, tenantID string) ([]models.Record, error)
	ListTemplates(ctx context.Context, tenantID string) ([]models.Record, error)
	ListTemplates2(ctx context.Context, tenantID string) ([]models.Record, error)
	ListViolations(ctx context.Context, tenantID string) ([]models.Record, error)
	Pause(ctx context.Context, tenantID, id string) (gin.H, error)
	Regenerate(ctx context.Context, tenantID, id string) (gin.H, error)
	RegisterModel(ctx context.Context, tenantID string, req models.CreateRequest) (*models.Record, error)
	Reject(ctx context.Context, tenantID, id string) (gin.H, error)
	Restart(ctx context.Context, tenantID, id string) (gin.H, error)
	Resume(ctx context.Context, tenantID, id string) (gin.H, error)
	Rollback(ctx context.Context, tenantID string, id string) (gin.H, error)
	RunInspection(ctx context.Context, tenantID string) (gin.H, error)
	RunPipeline(ctx context.Context, tenantID string, id string) (gin.H, error)
	ScaleResource(ctx context.Context, tenantID string, id string) (gin.H, error)
	Search(ctx context.Context, tenantID, query string) ([]models.Record, error)
	Train(ctx context.Context, tenantID string, id string) (gin.H, error)
	Trigger(ctx context.Context, tenantID, id string) (gin.H, error)
	Update(ctx context.Context, tenantID, id string, req models.CreateRequest) (*models.Record, error)
	UpdateConfig(ctx context.Context, tenantID, id string, config gin.H) (gin.H, error)
	UpdateStatus(ctx context.Context, tenantID, id string, status string) (gin.H, error)
	ValidateBranch(ctx context.Context, tenantID, branch string) (gin.H, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
