// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, entity *models.BiDashboard) error
	Delete(ctx context.Context, id tenantID string) bool, error
	GetByID(ctx context.Context, id tenantID string) *models.BiDashboard, error
	List(ctx context.Context, tenantID string) []models.BiDashboard, error
	Update(ctx context.Context, id tenantID string, attrs map[string]interface{}) *models.BiDashboard, error
}
