// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Count(ctx context.Context, tenantID string, q models.AuditLogQuery) int, error
	CoverageStats(ctx context.Context, tenantID string) models.AuditCoverageStats, error
	Create(ctx context.Context, tenantID string, req models.AuditLogCreateRequest) *models.AuditLog, error
	Export(ctx context.Context, tenantID string, q models.AuditLogQuery) []models.AuditLog, error
	GetActions(ctx context.Context, tenantID string) []string, error
	GetByID(ctx context.Context, tenantID id string) *models.AuditLog, error
	GetLatest(ctx context.Context, tenantID string) *models.AuditLog, error
	GetResourceTypes(ctx context.Context, tenantID string) []string, error
	List(ctx context.Context, tenantID string, q models.AuditLogQuery) []models.AuditLog, int, error
	VerifyChain(ctx context.Context, tenantID string) int, bool, error
}
