apiVersion: v1
kind: Service
metadata:
  name: orion-governance-svc-go
  namespace: orion
  labels:
    app: orion-governance-svc-go
    app.kubernetes.io/name: orion-governance-svc-go
    app.kubernetes.io/part-of: orion-platform
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: orion-governance-svc-go
