apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orion-cmdb-svc-go
  namespace: orion
  labels:
    app: orion-cmdb-svc-go
    app.kubernetes.io/part-of: orion-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orion-cmdb-svc-go
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
