// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for terminal-audit.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/terminal-audit/models"
)

// ServiceInterface defines the interface for the terminal-audit service.
type ServiceInterface interface {
	DeleteBatch(ctx context.Context, tenantID string, ids []string) (int, error)
	GetAudit(ctx context.Context, tenantID, id string) (*models.TerminalAuditLog, error)
	GetStats(ctx context.Context, tenantID string) (*models.AuditStats, error)
	ListAudits(ctx context.Context, tenantID string, q models.AuditQuery) ([]models.TerminalAuditLog, error)
	SearchAudits(ctx context.Context, tenantID string, q models.AuditQuery) ([]models.TerminalAuditLog, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
