// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, s *models.Session) error
	Delete(ctx context.Context, tenantID id string) error
	DeleteByUserID(ctx context.Context, tenantID userID string) int64, error
	DeleteExpired(ctx context.Context, tenantID string, now time.Time) int64, error
	GetByID(ctx context.Context, tenantID id string) *models.Session, error
	GetByToken(ctx context.Context, tenantID token string) *models.Session, error
	List(ctx context.Context, tenantID string, userID *string, offset limit int) []models.Session, error
	ListByTenant(ctx context.Context, tenantID string, now time.Time) []models.Session, error
	UpdateLastActive(ctx context.Context, id tenantID string, lastActiveAt time.Time) error
}
