package form

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// =============================================================================
// FormRenderer 表单渲染引擎
// =============================================================================
// 职责:
//   1. 将 Form 定义渲染为 JSON Schema（供前端消费）
//   2. 将 Form 定义渲染为 HTML 模板（供服务端渲染）
//   3. 将 Form 定义渲染为 React 组件代码片段
//   4. 将 Form 定义渲染为 YAML 配置（供运维管理）

type FormRenderer struct {
	form *Form
}

// NewFormRenderer 创建渲染器
func NewFormRenderer(form *Form) *FormRenderer {
	return &FormRenderer{form: form}
}

// RenderJSON 渲染为 JSON Schema（前端消费格式）
func (r *FormRenderer) RenderJSON() ([]byte, error) {
	schema := r.buildJSONSchema()
	return json.MarshalIndent(schema, "", "  ")
}

// RenderHTML 渲染为 HTML 表单模板
func (r *FormRenderer) RenderHTML() ([]byte, error) {
	buf := &bytes.Buffer{}
	buf.WriteString("<form class=\"orion-form\" method=\"POST\">\n")
	buf.WriteString(fmt.Sprintf("  <h2>%s</h2>\n", r.form.Title))

	if r.form.Description != "" {
		buf.WriteString(fmt.Sprintf("  <p>%s</p>\n", r.form.Description))
	}

	buf.WriteString("  <div class=\"form-body\">\n")
	for _, field := range r.form.Fields {
		if field.Hidden {
			continue
		}
		buf.WriteString(r.renderHTMLField(field))
	}
	buf.WriteString("  </div>\n")

	// 动作按钮
	buf.WriteString("  <div class=\"form-actions\">\n")
	for _, action := range r.form.Actions {
		disabled := ""
		if action.Disabled {
			disabled = " disabled"
		}
		buf.WriteString(fmt.Sprintf("    <button type=\"%s\" class=\"%s\"%s>%s</button>\n",
			action.Type, action.Type, disabled, action.Label))
	}
	buf.WriteString("  </div>\n")
	buf.WriteString("</form>")

	return buf.Bytes(), nil
}

// RenderReact 渲染为 React 组件代码片段
func (r *FormRenderer) RenderReact() ([]byte, error) {
	buf := &bytes.Buffer{}
	formName := r.toCamelCase(r.form.Title)

	buf.WriteString(fmt.Sprintf("import React, { useEffect } from 'react';\n"))
	buf.WriteString(fmt.Sprintf("import { Form, Button } from 'antd';\n"))
	buf.WriteString(fmt.Sprintf("import { FormInstance } from './types';\n\n"))
	buf.WriteString(fmt.Sprintf("export interface %sFormProps {\n", formName))
	buf.WriteString(fmt.Sprintf("  formInstance?: FormInstance;\n"))
	buf.WriteString(fmt.Sprintf("  initialValues?: Partial<%sData>;\n", formName))
	buf.WriteString(fmt.Sprintf("  onSubmit?: (values: %sData) => Promise<void>;\n", formName))
	buf.WriteString(fmt.Sprintf("}\n\n"))

	buf.WriteString(fmt.Sprintf("export interface %sData {\n", formName))
	for _, field := range r.form.Fields {
		tsType := r.fieldToTypeScriptType(field.Type)
		buf.WriteString(fmt.Sprintf("  %s: %s;\n", field.Key, tsType))
	}
	buf.WriteString("}\n\n")

	buf.WriteString(fmt.Sprintf("export const %sForm: React.FC<%sFormProps> = ({\n", formName, formName))
	buf.WriteString(fmt.Sprintf("  formInstance: formProp,\n"))
	buf.WriteString(fmt.Sprintf("  initialValues,\n"))
	buf.WriteString(fmt.Sprintf("  onSubmit,\n"))
	buf.WriteString(fmt.Sprintf("}) => {\n"))
	buf.WriteString(fmt.Sprintf("  const [form] = Form.useForm<%sData>();\n\n", formName))
	buf.WriteString(fmt.Sprintf("  useEffect(() => {\n"))
	buf.WriteString(fmt.Sprintf("    if (initialValues) {\n"))
	buf.WriteString(fmt.Sprintf("      form.setFieldsValue(initialValues);\n"))
	buf.WriteString(fmt.Sprintf("    }\n"))
	buf.WriteString(fmt.Sprintf("  }, [initialValues]);\n\n"))
	buf.WriteString(fmt.Sprintf("  const handleSubmit = async (values: %sData) => {\n", formName))
	buf.WriteString(fmt.Sprintf("    if (onSubmit) await onSubmit(values);\n"))
	buf.WriteString(fmt.Sprintf("  };\n\n"))
	buf.WriteString(fmt.Sprintf("  return (\n"))
	buf.WriteString(fmt.Sprintf("    <Form\n"))
	buf.WriteString(fmt.Sprintf("      form={form}\n"))
	buf.WriteString(fmt.Sprintf("      onFinish={handleSubmit}\n"))
	buf.WriteString(fmt.Sprintf("      labelCol={{ span: 6 }}\n"))
	buf.WriteString(fmt.Sprintf("      wrapperCol={{ span: 18 }}\n"))
	buf.WriteString(fmt.Sprintf("    >\n"))

	for _, field := range r.form.Fields {
		if field.Hidden {
			continue
		}
		buf.WriteString(r.renderReactField(field))
	}

	buf.WriteString("      <Form.Item>\n")
	buf.WriteString("        <Button type=\"primary\" htmlType=\"submit\">\n")
	buf.WriteString("          提交\n")
	buf.WriteString("        </Button>\n")
	buf.WriteString("      </Form.Item>\n")
	buf.WriteString("    </Form>\n")
	buf.WriteString("  );\n")
	buf.WriteString("};\n")

	return buf.Bytes(), nil
}

// RenderYAML 渲染为 YAML 配置（仅供展示，返回注释 + JSON）
func (r *FormRenderer) RenderYAML() ([]byte, error) {
	buf := &bytes.Buffer{}
	buf.WriteString("# Dynamic Form Definition (YAML)\n")
	buf.WriteString("# Generated by Orion FormRenderer\n")
	buf.WriteString("---\n")
	buf.WriteString(fmt.Sprintf("id: %s\n", r.form.ID))
	buf.WriteString(fmt.Sprintf("name: %s\n", r.form.Name))
	buf.WriteString(fmt.Sprintf("title: %s\n", r.form.Title))
	if r.form.Description != "" {
		buf.WriteString(fmt.Sprintf("description: %s\n", r.form.Description))
	}
	buf.WriteString(fmt.Sprintf("version: %d\n", r.form.Version))
	buf.WriteString(fmt.Sprintf("tenant_id: %s\n", r.form.TenantID))
	buf.WriteString(fmt.Sprintf("module_name: %s\n", r.form.ModuleName))
	buf.WriteString(fmt.Sprintf("form_type: %s\n", r.form.FormType))
	buf.WriteString(fmt.Sprintf("status: %s\n", r.form.Status))
	buf.WriteString("fields:\n")

	for _, field := range r.form.Fields {
		buf.WriteString(fmt.Sprintf("  - key: %s\n", field.Key))
		buf.WriteString(fmt.Sprintf("    label: %s\n", field.Label))
		buf.WriteString(fmt.Sprintf("    type: %s\n", field.Type))
		if field.Required {
			buf.WriteString("    required: true\n")
		}
		if field.MaxLength != nil {
			buf.WriteString(fmt.Sprintf("    max_length: %d\n", *field.MaxLength))
		}
		if len(field.Options) > 0 {
			buf.WriteString("    options:\n")
			for _, opt := range field.Options {
				buf.WriteString(fmt.Sprintf("      - key: %s\n", opt.Key))
				buf.WriteString(fmt.Sprintf("        label: %s\n", opt.Label))
			}
		}
	}

	return buf.Bytes(), nil
}

// renderHTMLField 渲染单个字段为 HTML
func (r *FormRenderer) renderHTMLField(field FormField) string {
	buf := &bytes.Buffer{}
	buf.WriteString(fmt.Sprintf("    <div class=\"form-field\" data-key=\"%s\">\n", field.Key))
	buf.WriteString(fmt.Sprintf("      <label for=\"%s\">%s</label>\n", field.Key, field.Label))

	required := ""
	if field.Required {
		required = " required"
	}

	switch field.Type {
	case FieldTypeInput:
		buf.WriteString(fmt.Sprintf("      <input type=\"text\" id=\"%s\" name=\"%s\" placeholder=\"%s\"%s/>\n",
			field.Key, field.Key, field.Placeholder, required))
	case FieldTypeTextArea:
		rows := 4
		buf.WriteString(fmt.Sprintf("      <textarea id=\"%s\" name=\"%s\" rows=\"%d\" placeholder=\"%s\"%s></textarea>\n",
			field.Key, field.Key, rows, field.Placeholder, required))
	case FieldTypeSelect:
		buf.WriteString(fmt.Sprintf("      <select id=\"%s\" name=\"%s\"%s>\n", field.Key, field.Key, required))
		for _, opt := range field.Options {
			disabled := ""
			if opt.Disabled {
				disabled = " disabled"
			}
			buf.WriteString(fmt.Sprintf("        <option value=\"%s\"%s>%s</option>\n",
				opt.Key, disabled, opt.Label))
		}
		buf.WriteString("      </select>\n")
	case FieldTypeCascader:
		buf.WriteString(fmt.Sprintf("      <select id=\"%s\" name=\"%s\"%s>\n",
			field.Key, field.Key, required))
		buf.WriteString("        <option value=\"\">请选择</option>\n")
		buf.WriteString("      </select>\n")
	case FieldTypeDate:
		buf.WriteString(fmt.Sprintf("      <input type=\"date\" id=\"%s\" name=\"%s\"%s/>\n",
			field.Key, field.Key, required))
	case FieldTypeDateTime:
		buf.WriteString(fmt.Sprintf("      <input type=\"datetime-local\" id=\"%s\" name=\"%s\"%s/>\n",
			field.Key, field.Key, required))
	case FieldTypeCheckbox:
		buf.WriteString(fmt.Sprintf("      <input type=\"checkbox\" id=\"%s\" name=\"%s\"/>\n",
			field.Key, field.Key))
	case FieldTypeRadio:
		for _, opt := range field.Options {
			buf.WriteString(fmt.Sprintf("      <label><input type=\"radio\" name=\"%s\" value=\"%s\"/> %s</label>\n",
				field.Key, opt.Key, opt.Label))
		}
	case FieldTypeNumber:
		buf.WriteString(fmt.Sprintf("      <input type=\"number\" id=\"%s\" name=\"%s\"%s/>\n",
			field.Key, field.Key, required))
	case FieldTypeUpload:
		buf.WriteString(fmt.Sprintf("      <input type=\"file\" id=\"%s\" name=\"%s\"/>\n",
			field.Key, field.Key))
	case FieldTypeEditor:
		buf.WriteString(fmt.Sprintf("      <textarea id=\"%s\" name=\"%s\" rows=\"8\"%s></textarea>\n",
			field.Key, field.Key, required))
	default:
		buf.WriteString(fmt.Sprintf("      <input type=\"text\" id=\"%s\" name=\"%s\"%s/>\n",
			field.Key, field.Key, required))
	}

	if field.Hint != "" {
		buf.WriteString(fmt.Sprintf("      <span class=\"hint\">%s</span>\n", field.Hint))
	}

	buf.WriteString("    </div>\n")
	return buf.String()
}

// renderReactField 渲染单个字段为 React 代码
func (r *FormRenderer) renderReactField(field FormField) string {
	buf := &bytes.Buffer{}
	buf.WriteString(fmt.Sprintf("      <Form.Item\n"))
	buf.WriteString(fmt.Sprintf("        name=\"%s\"\n", field.Key))
	buf.WriteString(fmt.Sprintf("        label=\"%s\"\n", field.Label))

	// 校验规则
	if field.Required {
		buf.WriteString(fmt.Sprintf("        rules={[{ required: true, message: \"%s\" }]}\n", field.Label))
	}

	buf.WriteString("      >\n")

	switch field.Type {
	case FieldTypeInput:
		buf.WriteString(fmt.Sprintf("        <Input placeholder=\"%s\" />\n", field.Placeholder))
	case FieldTypeTextArea:
		buf.WriteString(fmt.Sprintf("        <Input.TextArea placeholder=\"%s\" rows={4} />\n", field.Placeholder))
	case FieldTypeNumber:
		buf.WriteString(fmt.Sprintf("        <Input.Number placeholder=\"%s\" />\n", field.Placeholder))
	case FieldTypeSelect:
		buf.WriteString("        <Select\n")
		buf.WriteString("          showSearch\n")
		buf.WriteString("          optionFilterProp=\"label\"\n")
		buf.WriteString("          options={[\n")
		for _, opt := range field.Options {
			buf.WriteString(fmt.Sprintf("            {{ value: '%s', label: '%s' }},\n", opt.Key, opt.Label))
		}
		buf.WriteString("          ]}\n")
		buf.WriteString("        />\n")
	case FieldTypeMultiSelect:
		buf.WriteString("        <Select\n")
		buf.WriteString("          mode=\"multiple\"\n")
		buf.WriteString("          options={[\n")
		for _, opt := range field.Options {
			buf.WriteString(fmt.Sprintf("            {{ value: '%s', label: '%s' }},\n", opt.Key, opt.Label))
		}
		buf.WriteString("          ]}\n")
		buf.WriteString("        />\n")
	case FieldTypeCascader:
		buf.WriteString(fmt.Sprintf("        <Cascader options={%sCascaderOptions} />\n", field.Key))
	case FieldTypeDate:
		buf.WriteString("        <DatePicker />\n")
	case FieldTypeDateTime:
		buf.WriteString("        <DatePicker showTime />\n")
	case FieldTypeTime:
		buf.WriteString("        <TimePicker />\n")
	case FieldTypeCheckbox:
		buf.WriteString("        <Checkbox />\n")
	case FieldTypeRadio:
		buf.WriteString("        <Radio.Group options={[\n")
		for _, opt := range field.Options {
			buf.WriteString(fmt.Sprintf("          {{ label: '%s', value: '%s' }},\n", opt.Label, opt.Key))
		}
		buf.WriteString("        ]} />\n")
	case FieldTypeSwitch:
		buf.WriteString("        <Switch />\n")
	case FieldTypeUpload:
		buf.WriteString("        <Upload>\n")
		buf.WriteString("          <Button>上传文件</Button>\n")
		buf.WriteString("        </Upload>\n")
	case FieldTypeEditor:
		buf.WriteString("        <RichTextEditor />\n")
	case FieldTypeColor:
		buf.WriteString("        <ColorPicker />\n")
	case FieldTypeUserSelect:
		buf.WriteString("        <UserSelect />\n")
	default:
		buf.WriteString(fmt.Sprintf("        <Input placeholder=\"%s\" />\n", field.Placeholder))
	}

	buf.WriteString("      </Form.Item>\n")
	return buf.String()
}

// buildJSONSchema 构建 JSON Schema
func (r *FormRenderer) buildJSONSchema() map[string]interface{} {
	schema := map[string]interface{}{
		"$schema": "http://json-schema.org/draft-07/schema#",
		"title":   r.form.Title,
		"type":    "object",
		"properties": map[string]interface{}{},
		"required": []string{},
	}

	properties := schema["properties"].(map[string]interface{})
	var required []string

	for _, field := range r.form.Fields {
		prop := map[string]interface{}{
			"type":        r.fieldTypeToJSONSchemaType(field.Type),
			"description": field.Label,
		}
		if field.MaxLength != nil {
			prop["maxLength"] = *field.MaxLength
		}
		if field.MinLength != nil {
			prop["minLength"] = *field.MinLength
		}
		if field.Max != nil {
			prop["maximum"] = int64(*field.Max)
		}
		if field.Min != nil {
			prop["minimum"] = int64(*field.Min)
		}
		if field.Pattern != "" {
			prop["pattern"] = field.Pattern
		}
		if field.Default != nil {
			prop["default"] = field.Default
		}
		if len(field.Options) > 0 {
			enum := make([]string, 0)
			for _, opt := range field.Options {
				enum = append(enum, opt.Key)
			}
			prop["enum"] = enum
		}
		properties[field.Key] = prop

		if field.Required {
			required = append(required, field.Key)
		}
	}

	schema["required"] = required
	return schema
}

// 类型转换辅助
func (r *FormRenderer) fieldTypeToJSONSchemaType(ft FieldType) string {
	switch ft {
	case FieldTypeNumber, FieldTypeSwitch:
		return "number"
	case FieldTypeCheckbox:
		return "boolean"
	case FieldTypeCascader, FieldTypeMultiSelect, FieldTypeSelect:
		return "array"
	default:
		return "string"
	}
}

func (r *FormRenderer) fieldToTypeScriptType(ft FieldType) string {
	switch ft {
	case FieldTypeNumber, FieldTypeSwitch:
		return "number"
	case FieldTypeCheckbox:
		return "boolean"
	case FieldTypeCascader:
		return "string[]"
	case FieldTypeMultiSelect, FieldTypeUpload:
		return "string[]"
	case FieldTypeDateTime, FieldTypeDate:
		return "Date | string"
	default:
		return "string"
	}
}

func (r *FormRenderer) toCamelCase(s string) string {
	words := strings.Fields(s)
	if len(words) == 0 {
		return s
	}
	result := ""
	for _, w := range words {
		if len(w) > 0 {
			result += strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return result
}
