apiVersion: v1
kind: Service
metadata:
  name: orion-code-svc
  namespace: orion
  labels:
    app: orion-code-svc
    component: code-management
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3010
    protocol: TCP
    name: http
  selector:
    app: orion-code-svc
---
apiVersion: v1
kind: Service
metadata:
  name: orion-code-svc-headless
  namespace: orion
  labels:
    app: orion-code-svc
    component: code-management
    tier: backend
spec:
  clusterIP: None
  ports:
  - port: 3010
    targetPort: 3010
    protocol: TCP
    name: http
  selector:
    app: orion-code-svc