{{- $fullname := include "orion-service.fullname" . -}}
{{- if .Values.fullnameOverride }}{{ $fullname = .Values.fullnameOverride }}{{ end -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace | default "orion" }}
  labels:
    app: {{ $fullname }}
    app.kubernetes.io/name: {{ $fullname }}
    app.kubernetes.io/part-of: orion-platform
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ $fullname }}
