// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for gateway-dynamic.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/gateway-dynamic/models"
)

// ServiceInterface defines the interface for the gateway-dynamic service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateGatewayRouteRequest) (*models.GatewayRoute, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.GatewayRoute, error)
	List(ctx context.Context, tenantID string, limit, offset int) ([]models.GatewayRoute, error)
	ListWithFilter(ctx context.Context, tenantID string, enabled *bool, q string, limit, offset int) ([]models.GatewayRoute, int, error)
	Stats(ctx context.Context, tenantID string) (*models.RouteStats, error)
	Toggle(ctx context.Context, tenantID, id string, enabled bool) (*models.GatewayRoute, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateGatewayRouteRequest) (*models.GatewayRoute, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
