// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for deployment-trigger.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/deployment-trigger/models"
	"time"
)

// ServiceInterface defines the interface for the deployment-trigger service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req *models.CreateTriggerRequest) (*models.DeploymentTrigger, error)
	Delete(ctx context.Context, tenantID, id string) error
	EvaluateCron(expression string) (*time.Time, error)
	Execute(ctx context.Context, tenantID, id string) (*models.TriggerExecution, error)
	Get(ctx context.Context, tenantID, id string) (*models.DeploymentTrigger, error)
	GetExecutions(ctx context.Context, tenantID, id string, limit int) ([]models.TriggerExecution, error)
	List(ctx context.Context, tenantID string) ([]models.DeploymentTrigger, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateTriggerRequest) (*models.DeploymentTrigger, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
