// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for test-generation.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"github.com/gin-gonic/gin"
	"orion/platform-svc-go/internal/test-generation/models"
)

// ServiceInterface defines the interface for the test-generation service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateRequest) (*models.Record, error)
	Delete(ctx context.Context, tenantID, id string) error
	GenerateTests(ctx context.Context, tenantID, id string) (gin.H, error)
	Get(ctx context.Context, tenantID, id string) (*models.Record, error)
	GetResults(ctx context.Context, tenantID, id string) ([]string, error)
	List(ctx context.Context, tenantID string) ([]models.Record, error)
	ListTemplates(ctx context.Context, tenantID string) (map[string]interface{}, error)
	Regenerate(ctx context.Context, tenantID, id string) (gin.H, error)
	Update(ctx context.Context, tenantID, id string, req models.CreateRequest) (*models.Record, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
