// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for chatops.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/chatops/models"
)

// ServiceInterface defines the interface for the chatops service.
type ServiceInterface interface {
	AddTag(ctx context.Context, tenantID, versionID, tagName, createdBy string) error
	CreateAuditLog(ctx context.Context, tenantID, userID, action, command, details string) error
	CreateCapabilityMapping(ctx context.Context, tenantID string, req models.CreateCapabilityMappingRequest) (*models.CapabilityMapping, error)
	CreateCommand(ctx context.Context, tenantID string, req models.CreateCommandRequest) (*models.ChatOpsCommand, error)
	CreateCommandPermission(ctx context.Context, tenantID string, req models.CreateCommandPermissionRequest) (*models.CommandPermission, error)
	CreateCommandVersion(ctx context.Context, tenantID string, req models.CreateCommandVersionRequest) (*models.CommandVersion, error)
	CreateEnvironmentPermission(ctx context.Context, tenantID string, req models.CreateEnvironmentPermissionRequest) (*models.EnvironmentPermission, error)
	CreateRateLimit(ctx context.Context, tenantID string, req models.CreateRateLimitRequest) (*models.RateLimit, error)
	CreateRole(ctx context.Context, tenantID string, req models.CreateRoleRequest) (*models.PermissionRole, error)
	CreateWebhook(ctx context.Context, tenantID string, req models.CreateWebhookRequest) (*models.Webhook, error)
	DeleteCapabilityMapping(ctx context.Context, tenantID, id string) error
	DeleteCommand(ctx context.Context, tenantID, id string) error
	DeleteCommandPermission(ctx context.Context, tenantID, id string) error
	DeleteCommandVersion(ctx context.Context, tenantID, id string) error
	DeleteEnvironmentPermission(ctx context.Context, tenantID, id string) error
	DeleteRateLimit(ctx context.Context, tenantID, id string) error
	DeleteRole(ctx context.Context, tenantID, id string) error
	DeleteWebhook(ctx context.Context, tenantID, id string) error
	ExecuteCommand(ctx context.Context, tenantID string, userID string, req models.ExecuteCommandRequest) (*models.Execution, error)
	ExportAuditLogs(ctx context.Context, tenantID string, q models.AuditLogQuery) (map[string]any, error)
	GetAlertStates(ctx context.Context, tenantID, userID string) ([]models.AlertState, error)
	GetAllApprovalConfigs(ctx context.Context, tenantID string) ([]models.ApprovalConfig, error)
	GetAllCapabilityMappings(ctx context.Context, tenantID string, environment *string) ([]models.CapabilityMapping, error)
	GetAllCommandPermissions(ctx context.Context, tenantID string) ([]models.CommandPermission, error)
	GetAllCommandVersions(ctx context.Context, tenantID string, page, perPage int) (models.CommandVersionResult, error)
	GetAllEnvironmentPermissions(ctx context.Context, tenantID string) ([]models.EnvironmentPermission, error)
	GetAllRateLimits(ctx context.Context, tenantID string) ([]models.RateLimit, error)
	GetAllRoles(ctx context.Context, tenantID string) ([]models.PermissionRole, error)
	GetAllWebhooks(ctx context.Context, tenantID string) ([]models.Webhook, error)
	GetApprovalConfigByCapability(ctx context.Context, tenantID, capability string) (*models.ApprovalConfig, error)
	GetApproverSchedule(ctx context.Context, tenantID string) ([]models.ApproverSchedule, error)
	GetApprovers(ctx context.Context, tenantID string) ([]models.Approver, error)
	GetAuditStats(ctx context.Context, tenantID string) (map[string]any, error)
	GetCapabilityMapping(ctx context.Context, tenantID, id string) (*models.CapabilityMapping, error)
	GetCommand(ctx context.Context, tenantID, id string) (*models.ChatOpsCommand, error)
	GetCommandByName(ctx context.Context, tenantID, name string) (*models.ChatOpsCommand, error)
	GetCommandConfigs(ctx context.Context, tenantID, userID string) ([]models.CommandConfig, error)
	GetCommandHelp(ctx context.Context, tenantID, name string) (*models.ChatOpsCommand, error)
	GetCommandPermission(ctx context.Context, tenantID, id string) (*models.CommandPermission, error)
	GetDNDSettings(ctx context.Context, tenantID, userID string) (*models.DNDSettings, error)
	GetDashboardStats(ctx context.Context, tenantID string, req models.DashboardStatsRequest) (*models.DashboardStatsResult, error)
	GetEnvironmentPermission(ctx context.Context, tenantID, id string) (*models.EnvironmentPermission, error)
	GetExecutionStatus(ctx context.Context, tenantID, id string) (*models.Execution, error)
	GetGlobalApprovalConfig(ctx context.Context, tenantID string) (*models.GlobalApprovalConfig, error)
	GetKnowledgeRecommendations(ctx context.Context, tenantID string, context string, limit int) ([]models.KnowledgeRecommendation, error)
	GetNotificationPreference(ctx context.Context, tenantID, userID string) (*models.NotificationPreference, error)
	GetPlatformConfigs(ctx context.Context, tenantID, userID string) ([]models.PlatformConfig, error)
	GetQuestionConfigs(ctx context.Context, tenantID, userID string) ([]models.QuestionConfig, error)
	GetRateLimit(ctx context.Context, tenantID, id string) (*models.RateLimit, error)
	GetRecommendations(ctx context.Context, tenantID, userID, currentPage, resourceID string) ([]map[string]any, error)
	GetRole(ctx context.Context, tenantID, id string) (*models.PermissionRole, error)
	GetSessionMessages(ctx context.Context, tenantID, sessionID string, limit int, cursor *string) ([]models.ChatOpsMessage, error)
	GetUserAllowedCommands(ctx context.Context, tenantID, userID string) ([]string, error)
	GetVersionsByCommand(ctx context.Context, tenantID, commandID string) ([]models.CommandVersion, error)
	GetWebhook(ctx context.Context, tenantID, id string) (*models.Webhook, error)
	GetWebhookLogs(ctx context.Context, tenantID, webhookID string, limit int) ([]map[string]any, error)
	HealthCheck(ctx context.Context) (*models.HealthCheckResult, error)
	ListAuditLogs(ctx context.Context, tenantID string, q models.AuditLogQuery) ([]models.AuditLog, error)
	ListCommands(ctx context.Context, tenantID string, permissionLevel, name *string, limit, offset int) ([]models.ChatOpsCommand, error)
	ListExecutions(ctx context.Context, tenantID string, commandID, userID, status *string, limit, offset int) ([]models.Execution, error)
	MarkAlertAcknowledged(ctx context.Context, tenantID, userID, alertID string) error
	MarkAlertDismissed(ctx context.Context, tenantID, userID, alertID string) error
	MarkAlertRead(ctx context.Context, tenantID, userID, alertID string) error
	ReceiveMessage(ctx context.Context, tenantID string, userID string, req models.ReceiveMessageRequest) (map[string]any, error)
	RemoveTag(ctx context.Context, tenantID, versionID, tagName string) error
	TestWebhook(ctx context.Context, tenantID, id string) (*models.TestWebhookResult, error)
	ToggleDND(ctx context.Context, tenantID, userID string, enabled bool) (*models.DNDSettings, error)
	UpdateAlertState(ctx context.Context, tenantID, userID, alertID, status string) error
	UpdateApprovalConfig(ctx context.Context, tenantID, capability string, req models.UpdateApprovalConfigRequest) (*models.ApprovalConfig, error)
	UpdateApprovalConfigs(ctx context.Context, tenantID string, req models.UpdateApprovalConfigsRequest) ([]models.ApprovalConfig, error)
	UpdateApproverSchedule(ctx context.Context, tenantID string, schedule []models.ApproverSchedule) error
	UpdateCapabilityMapping(ctx context.Context, tenantID, id string, req models.UpdateCapabilityMappingRequest) (*models.CapabilityMapping, error)
	UpdateCommand(ctx context.Context, tenantID, id string, req models.UpdateCommandRequest) (*models.ChatOpsCommand, error)
	UpdateCommandConfigs(ctx context.Context, tenantID, userID string, req models.UpdateCommandConfigsRequest) ([]models.CommandConfig, error)
	UpdateCommandPermission(ctx context.Context, tenantID, id string, req models.UpdateCommandPermissionRequest) (*models.CommandPermission, error)
	UpdateDNDSettings(ctx context.Context, tenantID, userID string, req models.UpdateDNDRequest) (*models.DNDSettings, error)
	UpdateEnvironmentPermission(ctx context.Context, tenantID, id string, req models.UpdateEnvironmentPermissionRequest) (*models.EnvironmentPermission, error)
	UpdateGlobalApprovalConfig(ctx context.Context, tenantID string, config *models.GlobalApprovalConfig) error
	UpdateNotificationPreference(ctx context.Context, tenantID, userID string, req models.UpdateNotificationPreferenceRequest) (*models.NotificationPreference, error)
	UpdatePlatformConfigs(ctx context.Context, tenantID, userID string, req models.UpdatePlatformConfigRequest) ([]models.PlatformConfig, error)
	UpdateQuestionConfigs(ctx context.Context, tenantID, userID string, req models.UpdateQuestionConfigsRequest) ([]models.QuestionConfig, error)
	UpdateRateLimit(ctx context.Context, tenantID, id string, updates map[string]any) (*models.RateLimit, error)
	UpdateRole(ctx context.Context, tenantID, id string, req models.UpdateRoleRequest) (*models.PermissionRole, error)
	UpdateWebhook(ctx context.Context, tenantID, id string, body map[string]any) (*models.Webhook, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
