// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	AddChangeHistory(ctx context.Context, h *models.ChangeHistory) error
	Create(ctx context.Context, entity *models.ConfigMgmt) error
	CreateChangeRequest(ctx context.Context, cr *models.ChangeRequest) error
	CreateDriftReport(ctx context.Context, dr *models.DriftReport) error
	Delete(ctx context.Context, id tenantID string) bool, error
	DeleteChangeRequest(ctx context.Context, id tenantID string) bool, error
	GetByID(ctx context.Context, id tenantID string) *models.ConfigMgmt, error
	GetChangeHistory(ctx context.Context, changeRequestID tenantID string) []models.ChangeHistory, error
	GetChangeRequest(ctx context.Context, id tenantID string) *models.ChangeRequest, error
	GetDriftReport(ctx context.Context, id tenantID string) *models.DriftReport, error
	List(ctx context.Context, tenantID string) []models.ConfigMgmt, error
	ListChangeRequests(ctx context.Context, tenantID string, filter *models.ChangeHistoryFilter) []models.ChangeRequest, error
	Update(ctx context.Context, id tenantID string, attrs map[string]interface{}) *models.ConfigMgmt, error
	UpdateChangeRequest(ctx context.Context, id tenantID string, attrs map[string]interface{}) *models.ChangeRequest, error
	UpdateDriftReport(ctx context.Context, id tenantID string, attrs map[string]interface{}) *models.DriftReport, error
}
