// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for canary-traffic.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the canary-traffic service.
type ServiceInterface interface {
	AdjustWeight(ctx context.Context, id, tenantID string, canaryWeight int) (*models.CanaryTraffic, error)
	Create(ctx context.Context, req *models.CreateRequest, tenantID string) (*models.CanaryTraffic, error)
	Delete(ctx context.Context, id, tenantID string) (bool, error)
	Get(ctx context.Context, id, tenantID string) (*models.CanaryTraffic, error)
	GetTrafficSplit(ctx context.Context, id, tenantID string) (*models.TrafficSplit, error)
	List(ctx context.Context, tenantID string) ([]models.CanaryTraffic, error)
	Update(ctx context.Context, id, tenantID string, req *models.UpdateRequest) (*models.CanaryTraffic, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
