// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/sso-providers/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, provider *models.SSOProvider) error
	GetByID(ctx context.Context, tenantID, id string) (*models.SSOProvider, error)
	List(ctx context.Context, tenantID string, filter *models.SSOProviderFilter) ([]models.SSOProvider, int, error)
	Update(ctx context.Context, tenantID, id string, updates map[string]interface{}) (*models.SSOProvider, error)
	Delete(ctx context.Context, tenantID, id string) (bool, error)
}
