// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for mlops.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/mlops/models"
)

// ServiceInterface defines the interface for the mlops service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateRequest) (*models.Record, error)
	Delete(ctx context.Context, tenantID, id string) error
	DeregisterModel(ctx context.Context, tenantID, id string) error
	Deploy(ctx context.Context, tenantID, id string) (map[string]any, error)
	Evaluate(ctx context.Context, tenantID, id string) (map[string]any, error)
	Get(ctx context.Context, tenantID, id string) (*models.Record, error)
	GetMetrics(ctx context.Context, tenantID, id string) (map[string]any, error)
	ListArtifacts(ctx context.Context, tenantID, id string) ([]models.Record, error)
	ListExperiments(ctx context.Context, tenantID, id string) ([]models.Record, error)
	ListModels(ctx context.Context, tenantID string) ([]models.Record, error)
	ListPipelines(ctx context.Context, tenantID string) ([]models.Record, error)
	List(ctx context.Context, tenantID string) ([]models.Record, error)
	RegisterModel(ctx context.Context, tenantID string, req models.CreateRequest) (*models.Record, error)
	Rollback(ctx context.Context, tenantID, id string) (map[string]any, error)
	Train(ctx context.Context, tenantID, id string) (map[string]any, error)
	Update(ctx context.Context, tenantID, id string, req models.CreateRequest) (*models.Record, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
