// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for mlops.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the mlops service.
type ServiceInterface interface {
	AddTag(ctx context.Context, tenantID, id, tag string) error
	Approve(ctx context.Context, tenantID, id string) (map[string]any, error)
	BatchCreate(ctx context.Context, tenantID string, reqs []models.CreateRequest) (map[string]any, error)
	CheckCompatibility(ctx context.Context, tenantID, id string) (map[string]any, error)
	Configure(ctx context.Context, tenantID string, cfg map[string]any) error
	Create(ctx context.Context, tenantID string, req models.CreateRequest) (*models.Record, error)
	Delete(ctx context.Context, tenantID, id string) error
	DeleteTag(ctx context.Context, tenantID, id, tag string) error
	Deploy(ctx context.Context, tenantID, id string) (map[string]any, error)
	DeregisterModel(ctx context.Context, tenantID, id string) error
	DisablePlugin(ctx context.Context, tenantID, id string) error
	EnablePlugin(ctx context.Context, tenantID, id string) error
	EnforcePolicy(ctx context.Context, tenantID string) (map[string]any, error)
	Escalate(ctx context.Context, tenantID, id string) (map[string]any, error)
	Evaluate(ctx context.Context, tenantID, id string) (map[string]any, error)
	Forecast(ctx context.Context, tenantID string) (map[string]any, error)
	Get(ctx context.Context, tenantID, id string) (*models.Record, error)
	GetBranchStatus(ctx context.Context, tenantID, branch string) (map[string]any, error)
	GetByUser(ctx context.Context, tenantID, user string) ([]models.Record, error)
	GetConfig(ctx context.Context, tenantID string) (map[string]any, error)
	GetCoverage(ctx context.Context, tenantID string) (map[string]any, error)
	GetHistory(ctx context.Context, tenantID, id string) ([]string, error)
	GetLineage(ctx context.Context, tenantID, id string) (map[string]any, error)
	GetLogs(ctx context.Context, tenantID, id string) ([]string, error)
	GetMetrics(ctx context.Context, tenantID, id string) (map[string]any, error)
	GetPlugin(ctx context.Context, tenantID, id string) (map[string]any, error)
	GetResults(ctx context.Context, tenantID string) ([]models.Record, error)
	GetStats(ctx context.Context, tenantID string) (map[string]any, error)
	GetStatus(ctx context.Context, tenantID string) (map[string]any, error)
	GetStatusMiddleware(ctx context.Context) (map[string]any, error)
	GetUtilization(ctx context.Context, tenantID string) (map[string]any, error)
	List(ctx context.Context, tenantID string) ([]models.Record, error)
	ListAlerts(ctx context.Context, tenantID string) ([]string, error)
	ListArtifacts(ctx context.Context, tenantID, id string) ([]models.Record, error)
	ListExperiments(ctx context.Context, tenantID, id string) ([]models.Record, error)
	ListHistories(ctx context.Context, tenantID string) ([]models.Record, error)
	ListModels(ctx context.Context, tenantID string) ([]models.Record, error)
	ListPending(ctx context.Context, tenantID string) ([]models.Record, error)
	ListPipelines(ctx context.Context, tenantID string) ([]models.Record, error)
	ListPlugins(ctx context.Context, tenantID string) ([]models.Record, error)
	ListSchemas(ctx context.Context, tenantID string) ([]string, error)
	ListTemplates(ctx context.Context, tenantID string) ([]models.Record, error)
	ListTemplates2(ctx context.Context, tenantID string) ([]models.Record, error)
	ListViolations(ctx context.Context, tenantID string) ([]string, error)
	Pause(ctx context.Context, tenantID, id string) (map[string]any, error)
	Regenerate(ctx context.Context, tenantID, id string) (map[string]any, error)
	RegisterModel(ctx context.Context, tenantID string, req models.CreateRequest) (*models.Record, error)
	Reject(ctx context.Context, tenantID, id string) (map[string]any, error)
	Restart(ctx context.Context, tenantID string) (map[string]any, error)
	Resume(ctx context.Context, tenantID, id string) (map[string]any, error)
	Rollback(ctx context.Context, tenantID, id string) (map[string]any, error)
	RunInspection(ctx context.Context, tenantID string) (map[string]any, error)
	RunPipeline(ctx context.Context, tenantID, id string) (map[string]any, error)
	ScaleResource(ctx context.Context, tenantID, id string, req map[string]any) (map[string]any, error)
	Search(ctx context.Context, tenantID, q string) ([]models.Record, error)
	Train(ctx context.Context, tenantID, id string) (map[string]any, error)
	Trigger(ctx context.Context, tenantID, id string) (map[string]any, error)
	Update(ctx context.Context, tenantID, id string, req models.CreateRequest) (*models.Record, error)
	UpdateConfig(ctx context.Context, tenantID string, cfg map[string]any) error
	UpdateStatus(ctx context.Context, tenantID, id string, status string) error
	ValidateBranch(ctx context.Context, tenantID, branch string) (map[string]any, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
