// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for digital-twin-simulation.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the digital-twin-simulation service.
type ServiceInterface interface {
	CreateTwin(ctx context.Context, tenantID string, req models.CreateTwinRequest) (*models.DigitalTwin, error)
	DeleteTwin(ctx context.Context, tenantID, id string) error
	GetComparison(ctx context.Context, twinID string) (*TwinComparison, error)
	GetState(ctx context.Context, twinID string) (*TwinStateResponse, error)
	GetTwin(ctx context.Context, tenantID, id string) (*models.DigitalTwin, error)
	ListSimulations(ctx context.Context, twinID string, q models.ListQuery) ([]models.Simulation, int64, error)
	ListTwins(ctx context.Context, tenantID string, q models.ListQuery) ([]models.DigitalTwin, int64, error)
	Predict(ctx context.Context, twinID string, req models.PredictRequest) (*PredictionResult, error)
	Simulate(ctx context.Context, tenantID, twinID string, req models.SimulateRequest) (*models.Simulation, error)
	SyncTwin(ctx context.Context, tenantID, id string) (*models.DigitalTwin, error)
	UpdateTwin(ctx context.Context, tenantID, id string, req models.UpdateTwinRequest) (*models.DigitalTwin, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
