// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateAccount(ctx context.Context, account *models.Account) error
	CreateInvoice(ctx context.Context, invoice *models.Invoice) error
	CreateLineItem(ctx context.Context, item *models.LineItem) error
	CreateSubscription(ctx context.Context, sub *models.Subscription) error
	DeleteAccount(ctx context.Context, tenantID id string) bool, error
	DeleteInvoice(ctx context.Context, tenantID id string) bool, error
	DeleteSubscription(ctx context.Context, tenantID id string) bool, error
	GetAccountByID(ctx context.Context, tenantID id string) *models.Account, error
	GetBillingStats(ctx context.Context, tenantID string) *models.BillingStats, error
	GetInvoiceByID(ctx context.Context, tenantID id string) *models.Invoice, error
	GetSubscriptionByID(ctx context.Context, tenantID id string) *models.Subscription, error
	ListAccounts(ctx context.Context, tenantID string, status *string) []models.Account, error
	ListInvoices(ctx context.Context, tenantID string, filter *models.InvoiceFilter) []models.Invoice, int, error
	ListLineItemsByInvoice(ctx context.Context, tenantID invoiceID string) []models.LineItem, error
	ListSubscriptions(ctx context.Context, tenantID string, status *string) []models.Subscription, error
	UpdateAccount(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.Account, error
	UpdateInvoice(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.Invoice, error
	UpdateSubscription(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.Subscription, error
}
