// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Count(ctx context.Context, tenantID string, q models.ListReviewsQuery) int, error
	Create(ctx context.Context, m *models.ReviewRequest) error
	GetByID(ctx context.Context, tenantID id string) *models.ReviewRequest, error
	List(ctx context.Context, tenantID string, q models.ListReviewsQuery) []models.ReviewRequest, error
	UpdateStatus(ctx context.Context, tenantID id string, status string) error
}
