// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, m *models.Experiment) error
	CreateInjection(ctx context.Context, rec *models.InjectionRecord) error
	CreateRecovery(ctx context.Context, rec *models.RecoveryRecord) error
	CreateRun(ctx context.Context, run *models.ExperimentRun) error
	Delete(ctx context.Context, tenantID id string) error
	GetByID(ctx context.Context, tenantID id string) *models.Experiment, error
	GetInjection(ctx context.Context, tenantID injectionID string) *models.InjectionRecord, error
	GetRun(ctx context.Context, tenantID runID string) *models.ExperimentRun, error
	List(ctx context.Context, tenantID string, status string, limit offset int) []models.Experiment, error
	ListInjectionsByExperiment(ctx context.Context, tenantID experimentID string) []models.InjectionRecord, error
	ListRecoveriesByExperiment(ctx context.Context, tenantID experimentID string) []models.RecoveryRecord, error
	ListRunning(ctx context.Context, tenantID string) []models.Experiment, error
	Update(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpdateInjectionStatus(ctx context.Context, tenantID injectionID status string) error
	UpdateRecoveryStatus(ctx context.Context, tenantID experimentID status message string) error
	UpdateRunStatus(ctx context.Context, tenantID runID status string) error
	UpdateStatus(ctx context.Context, tenantID id status string) error
}
