// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for workflow-webhook.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the workflow-webhook service.
type ServiceInterface interface {
	Count(ctx context.Context, tenantID string) (int, error)
	Create(ctx context.Context, tenantID, userID string, req *models.CreateWebhookTriggerRequest) (*models.WebhookTrigger, error)
	Delete(ctx context.Context, tenantID, id string) error
	GetByID(ctx context.Context, tenantID, id string) (*models.WebhookTrigger, error)
	List(ctx context.Context, tenantID string, filter *models.ListFilter, page, pageSize int) ([]models.WebhookTrigger, int, error)
	ListLogs(ctx context.Context, triggerID string, page, pageSize int) ([]models.WebhookTriggerLog, int, error)
	ProcessWebhook(ctx context.Context, webhookPath string, body []byte, signatureHeader, timestampHeader string) (*ProcessWebhookResult, error)
	RotateSecret(ctx context.Context, tenantID, id string) (string, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateWebhookTriggerRequest) (*models.WebhookTrigger, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
