// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for do-not-disturb.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the do-not-disturb service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID, userID string, req *models.CreateDoNotDisturbRequest) (*models.DoNotDisturb, error)
	Get(ctx context.Context, tenantID, userID string) (*models.DoNotDisturb, error)
	IsActive(ctx context.Context, tenantID, userID string) (bool, error)
	Update(ctx context.Context, tenantID, userID string, req *models.UpdateDoNotDisturbRequest) (*models.DoNotDisturb, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
