// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for ueba.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/ueba/models"
)

// ServiceInterface defines the interface for the ueba service.
type ServiceInterface interface {
	CreateAlert(ctx context.Context, tenantID string, req *models.CreateAlertRequest) (*models.UEBAAlert, error)
	DetectAnomaly(ctx context.Context, tenantID string, req *models.DetectAnomalyRequest) (*models.CreateAlertRequest, error)
	DismissAlert(ctx context.Context, id, tenantID string, req *models.DismissAlertRequest) error
	GetAlert(ctx context.Context, id, tenantID string) (*models.UEBAAlert, error)
	GetProfile(ctx context.Context, tenantID, entityID string) (*models.UEBAProfile, error)
	ListAlerts(ctx context.Context, tenantID string, q models.ListAlertsQuery) ([]models.UEBAAlert, error)
	ListProfiles(ctx context.Context, tenantID string) ([]models.UEBAProfile, error)
	SaveProfile(ctx context.Context, tenantID, userID, entityType, entityID, profileData string) error
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
