// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package service

import (
	"context"

	"orion/platform-svc-go/internal/webhook/store/models"
)

// ServiceInterface defines the interface for the webhook/store service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID, domain string, req *models.CreateConfigEntryRequest) (*models.ConfigEntry, error)
	Get(ctx context.Context, tenantID, id string) (*models.ConfigEntry, error)
	ListByDomain(ctx context.Context, tenantID, domain string) ([]models.ConfigEntry, error)
	ListAll(ctx context.Context, tenantID string) ([]models.ConfigEntry, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateConfigEntryRequest) (*models.ConfigEntry, error)
	Delete(ctx context.Context, tenantID, id string) error
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
