apiVersion: v1
kind: Service
metadata:
  name: orion-runner-svc
  namespace: orion
  labels:
    app: orion-runner-svc
    version: v1
    component: runner-service
spec:
  type: ClusterIP
  ports:
    - port: 3028
      targetPort: 3028
      protocol: TCP
      name: http
  selector:
    app: orion-runner-svc