// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CountProviders(ctx context.Context, tenantID string, q models.ListProvidersQuery) int, error
	CreateProvider(ctx context.Context, p *models.SSOProvider) error
	CreateSession(ctx context.Context, s *models.SSOSession) error
	DeleteProvider(ctx context.Context, tenantID id string) error
	GetProvider(ctx context.Context, tenantID id string) *models.SSOProvider, error
	GetSession(ctx context.Context, tenantID id string) *models.SSOSession, error
	GetSessionByState(ctx context.Context, tenantID state string) *models.SSOSession, error
	ListProviders(ctx context.Context, tenantID string, q models.ListProvidersQuery) []models.SSOProvider, error
	ListSessions(ctx context.Context, tenantID string, status string, limit int) []models.SSOSession, error
	UpdateProvider(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpdateSession(ctx context.Context, tenantID id string, updates map[string]interface{}) error
}
