-- Migration 262: Monitoring Alert Instances
-- Persistent storage for alert instances generated by AlertRuleEngine.
-- Complements monitoring_alert_rules (049) with actual alert records.

CREATE TABLE IF NOT EXISTS monitoring_alert_instances (
  id              VARCHAR(64) PRIMARY KEY,
  tenant_id       VARCHAR(64) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  rule_id         VARCHAR(64) NOT NULL,
  rule_name       VARCHAR(200),
  metric          VARCHAR(200) NOT NULL,
  value           NUMERIC NOT NULL,
  threshold       NUMERIC NOT NULL,
  severity        VARCHAR(20) NOT NULL DEFAULT 'warning',
  status          VARCHAR(20) NOT NULL DEFAULT 'triggered',
  triggered_at    TIMESTAMP NOT NULL DEFAULT NOW(),
  acknowledged_at TIMESTAMP,
  acknowledged_by VARCHAR(64),
  resolved_at     TIMESTAMP,
  tags            JSONB,
  message         TEXT,
  created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_monitoring_alert_instances_tenant_id ON monitoring_alert_instances(tenant_id);
CREATE INDEX IF NOT EXISTS idx_monitoring_alert_instances_rule_id ON monitoring_alert_instances(rule_id);
CREATE INDEX IF NOT EXISTS idx_monitoring_alert_instances_status ON monitoring_alert_instances(status);
CREATE INDEX IF NOT EXISTS idx_monitoring_alert_instances_severity ON monitoring_alert_instances(severity);
CREATE INDEX IF NOT EXISTS idx_monitoring_alert_instances_triggered_at ON monitoring_alert_instances(triggered_at DESC);
