// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/sprint/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, m *models.Sprint) error
	GetBoard(ctx context.Context, tenantID, sprintID string) (*models.SprintBoard, error)
	AddTicket(ctx context.Context, st *models.SprintTicket) error
	RemoveTicket(ctx context.Context, tenantID, sprintID, ticketID string) error
	ReorderTickets(ctx context.Context, tenantID, sprintID string, orders []models.TicketOrder) error
	GetBurndownData(ctx context.Context, tenantID, sprintID string) (*models.BurndownData, error)
	GetByID(ctx context.Context, tenantID, id string) (*models.Sprint, error)
	List(ctx context.Context, tenantID string, limit, offset int) ([]models.Sprint, error)
	Update(ctx context.Context, tenantID, id string, updates map[string]interface{}) error
	Delete(ctx context.Context, tenantID, id string) error
}
