// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for dependency-coordination.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/dependency-coordination/models"
)

// ServiceInterface defines the interface for the dependency-coordination service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req *models.CreateDependencyCoordinationRequest) (*models.DependencyCoordination, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.DependencyCoordination, error)
	List(ctx context.Context, tenantID string) ([]models.DependencyCoordination, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateDependencyCoordinationRequest) (*models.DependencyCoordination, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
