// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/smart-deploy/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateDeploymentRequest) (*models.Deployment, error)
	GetByID(ctx context.Context, tenantID, id string) (*models.Deployment, error)
	List(ctx context.Context, tenantID string, opt models.ListDeploymentsOptions) ([]models.Deployment, int, error)
	GetLatest(ctx context.Context, tenantID, appName, environment string) (*models.Deployment, error)
	UpdateStatus(ctx context.Context, tenantID, id string, status models.DeploymentStatus) (*models.Deployment, error)
	CreateRollback(ctx context.Context, tenantID string, req models.CreateRollbackRequest, deploymentID string) (*models.Rollback, error)
	ListRollbacks(ctx context.Context, tenantID, deploymentID string) ([]models.Rollback, error)
	UpdateRollbackStatus(ctx context.Context, tenantID, id string, status string) (*models.Rollback, error)
	SetRollbackCompleted(ctx context.Context, tenantID, id string) error
	GetMetrics(ctx context.Context, tenantID string) (*models.DeploymentMetrics, error)
	CreateAuditEntry(ctx context.Context, tenantID string, entry models.AuditEntry) error
	ListAuditEntries(ctx context.Context, tenantID, deploymentID string) ([]models.AuditEntry, error)
}
