// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/sla/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	CreateDefinition(ctx context.Context, d *models.SLADefinition) error
	GetDefinitionByID(ctx context.Context, tenantID, id string) (*models.SLADefinition, error)
	ListDefinitions(ctx context.Context, tenantID string, q models.DefinitionListQuery) ([]models.SLADefinition, int, error)
	UpdateDefinition(ctx context.Context, tenantID, id string, updates map[string]interface{}) error
	DeleteDefinition(ctx context.Context, tenantID, id string) error
	CreateTracking(ctx context.Context, t *models.SLATracking) error
	GetTrackingByID(ctx context.Context, tenantID, id string) (*models.SLATracking, error)
	ListTracking(ctx context.Context, tenantID string, q models.TrackingListQuery) ([]models.SLATracking, int, error)
	UpdateTracking(ctx context.Context, tenantID, id string, updates map[string]interface{}) error
	UpdateTrackingStatus(ctx context.Context, tenantID, id, status string, reason string) error
	MarkMet(ctx context.Context, tenantID, id string) error
	MarkBreached(ctx context.Context, tenantID, id, details string) error
	PauseTracking(ctx context.Context, tenantID, id, reason string) error
	ResumeTracking(ctx context.Context, tenantID, id string) error
	CreateBreachEvent(ctx context.Context, e *models.SLABreachEvent) error
	GetBreachEventsByTracking(ctx context.Context, trackingID string) ([]models.SLABreachEvent, error)
	ListBreachEvents(ctx context.Context, tenantID string, limit, offset int) ([]models.SLABreachEvent, int, error)
	DetectBreaches(ctx context.Context, tenantID string) (int, int, error)
	GetStats(ctx context.Context, tenantID string) (*models.StatsResult, error)
}
