// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Count(ctx context.Context, tenantID string) int, error
	CountByUser(ctx context.Context, tenantID userID string) int, error
	Create(ctx context.Context, key *models.APIKey) error
	Delete(ctx context.Context, tenantID id string) error
	GetByHash(ctx context.Context, tenantID keyHash string) *models.APIKey, error
	GetByID(ctx context.Context, tenantID id string) *models.APIKey, error
	List(ctx context.Context, tenantID string, filter *models.ListFilter, offset limit int) []models.APIKey, error
	UpdateLastUsed(ctx context.Context, id string, tenantID string, usedAt interface{}) error
}
