// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for ticket-knowledge.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/ticket-knowledge/models"
)

// ServiceInterface defines the interface for the ticket-knowledge service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateTicketKnowledgeRequest) (*models.TicketKnowledge, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.TicketKnowledge, error)
	List(ctx context.Context, tenantID string) ([]models.TicketKnowledge, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateTicketKnowledgeRequest) (*models.TicketKnowledge, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
