// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for lowcode.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/lowcode/models"
)

// ServiceInterface defines the interface for the lowcode service.
type ServiceInterface interface {
	ApplyTemplate(ctx context.Context, tenantID, userID, templateID string, req *models.ApplyTemplateRequest) (*models.LowcodeFlow, error)
	CreateFlow(ctx context.Context, tenantID, userID string, req *models.CreateFlowRequest) (*models.LowcodeFlow, error)
	CreateTemplate(ctx context.Context, userID string, req *models.CreateTemplateRequest) (*models.LowcodeTemplate, error)
	CreateVersion(ctx context.Context, tenantID, userID, workflowID string) (*models.VersionSnapshot, error)
	DeleteFlow(ctx context.Context, tenantID, id string) error
	ExecuteFlow(ctx context.Context, tenantID, userID, flowID string, input string) (*models.LowcodeInstance, error)
	ExportWorkflow(ctx context.Context, tenantID, id string) (*models.ExportResponse, error)
	GetFlow(ctx context.Context, tenantID, id string) (*models.LowcodeFlow, error)
	ImportWorkflow(ctx context.Context, tenantID, userID string, req *models.ImportWorkflowRequest) (*models.LowcodeFlow, error)
	ListFlows(ctx context.Context, tenantID string, filter *models.ListFlowFilters, page, pageSize int) ([]models.LowcodeFlow, int, error)
	ListTemplates(ctx context.Context) ([]models.LowcodeTemplate, error)
	ListVersions(ctx context.Context, tenantID, workflowID string) ([]models.VersionSnapshot, error)
	PublishFlow(ctx context.Context, tenantID, id string) (*models.LowcodeFlow, error)
	UpdateFlow(ctx context.Context, tenantID, id string, req *models.UpdateFlowRequest) (*models.LowcodeFlow, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
