// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, m *models.ServiceRegistry) error
	Deregister(ctx context.Context, tenantID serviceID string) error
	FindByServiceID(ctx context.Context, tenantID serviceID string) *models.ServiceRegistry, error
	GetByInternalID(ctx context.Context, tenantID id string) *models.ServiceRegistry, error
	List(ctx context.Context, tenantID string, f *ListFilters) []models.ServiceRegistry, error
	RecordHeartbeat(ctx context.Context, tenantID serviceID string) error
	Register(ctx context.Context, tenantID serviceID serviceName serviceURL protocol version string, metadata models.JSONB) *models.ServiceRegistry, error
}
