// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/service-registry/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, m *models.ServiceRegistry) error
	GetByInternalID(ctx context.Context, tenantID, id string) (*models.ServiceRegistry, error)
	FindByServiceID(ctx context.Context, tenantID, serviceID string) (*models.ServiceRegistry, error)
	List(ctx context.Context, tenantID string, f *ListFilters) ([]models.ServiceRegistry, error)
	Register(ctx context.Context, tenantID, serviceID, serviceName, serviceURL, protocol, version string, metadata models.JSONB) (*models.ServiceRegistry, error)
	Deregister(ctx context.Context, tenantID, serviceID string) error
	RecordHeartbeat(ctx context.Context, tenantID, serviceID string) error
}
