// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for alert-breaker.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the alert-breaker service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req *models.CreateAlertBreakerRequest) (*models.AlertBreaker, error)
	Delete(ctx context.Context, tenantID, id string) (bool, error)
	Get(ctx context.Context, tenantID, id string) (*models.AlertBreaker, error)
	List(ctx context.Context, tenantID string) ([]models.AlertBreaker, int, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateAlertBreakerRequest) (*models.AlertBreaker, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
