// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/vector-store/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, m *models.VectorStore) error
	GetByID(ctx context.Context, tenantID, id string) (*models.VectorStore, error)
	List(ctx context.Context, tenantID string) ([]models.VectorStore, error)
	Update(ctx context.Context, tenantID, id string, updates map[string]interface{}) (*models.VectorStore, error)
	Delete(ctx context.Context, tenantID, id string) error
}
