// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, dnd *models.DoNotDisturb) error
	GetByUser(ctx context.Context, tenantID userID string) *models.DoNotDisturb, error
	IsDNDActive(ctx context.Context, tenantID userID string) bool, error
	Update(ctx context.Context, tenantID userID string, updates map[string]interface{}) *models.DoNotDisturb, error
}
