// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CleanupExpired(ctx context.Context, tenantID string, retentionDays int) int64, error
	GetRunAuditTrail(ctx context.Context, tenantID runID string, limit int) *models.AuditTrailResponse, error
	Query(ctx context.Context, q models.AuditLogQuery) []models.AuditLog, int, error
	Record(ctx context.Context, log *models.AuditLog) error
	RecordBatch(ctx context.Context, logs []*models.AuditLog) error
}
