// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for data-lineage.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the data-lineage service.
type ServiceInterface interface {
	CreateLineage(ctx context.Context, tenantID string, req *models.CreateLineageRequest) (*models.Lineage, error)
	CreateNode(ctx context.Context, tenantID string, lineageID string, req *models.CreateNodeRequest) (*models.Node, error)
	CreateRelationship(ctx context.Context, tenantID string, lineageID string, req *models.CreateRelationshipRequest) (*models.Relationship, error)
	DeleteLineage(ctx context.Context, tenantID, id string) error
	GetLineage(ctx context.Context, tenantID, id string) (*models.Lineage, error)
	GetStats(ctx context.Context, tenantID string) (*models.LineageStats, error)
	ListLineages(ctx context.Context, tenantID string, status *string) ([]models.Lineage, error)
	ListNodes(ctx context.Context, tenantID, lineageID string) ([]models.Node, error)
	ListRelationships(ctx context.Context, tenantID, lineageID string) ([]models.Relationship, error)
	UpdateLineage(ctx context.Context, tenantID, id string, req *models.UpdateLineageRequest) (*models.Lineage, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
