// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Count(ctx context.Context, tenantID string) int, error
	Create(ctx context.Context, role *models.Role) error
	Delete(ctx context.Context, tenantID id string) error
	GetByID(ctx context.Context, tenantID id string) *models.Role, error
	List(ctx context.Context, tenantID string, filter *models.ListFilter, offset limit int) []models.Role, error
	Update(ctx context.Context, role *models.Role) error
	UpdatePermissions(ctx context.Context, tenantID id string, permissions models.Permissions) error
}
