package service

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"orion-deploy-svc-go/internal/models"
	"orion-deploy-svc-go/internal/repository"
)

// ReleaseNotesService handles release notes generation and retrieval.
type ReleaseNotesService struct {
	repo *repository.ReleaseNotesRepository
}

func NewReleaseNotesService(repo *repository.ReleaseNotesRepository) *ReleaseNotesService {
	return &ReleaseNotesService{repo: repo}
}

// GetReleaseNotes returns the release notes for a deployment.
func (s *ReleaseNotesService) GetReleaseNotes(ctx context.Context, tenantID, deploymentID string) (*models.ReleaseNote, error) {
	rn, err := s.repo.GetByDeployment(ctx, tenantID, deploymentID)
	if err != nil {
		return nil, fmt.Errorf("release notes not found")
	}
	return rn, nil
}

// GenerateReleaseNotes creates or updates release notes for a deployment.
func (s *ReleaseNotesService) GenerateReleaseNotes(
	ctx context.Context, tenantID, deploymentID string,
	req *models.GenerateReleaseNotesRequest, actor string,
) (*models.ReleaseNote, error) {
	// Check if release notes already exist
	existing, err := s.repo.GetByDeployment(ctx, tenantID, deploymentID)
	if err == nil && existing != nil {
		content := buildReleaseNotes(deploymentID, req, actor)
		if err := s.repo.Update(ctx, tenantID, deploymentID, content); err != nil {
			return nil, fmt.Errorf("failed to update release notes: %w", err)
		}
		existing.Content = content
		return existing, nil
	}

	content := buildReleaseNotes(deploymentID, req, actor)
	rn := &models.ReleaseNote{
		ID:           uuid.New().String(),
		DeploymentID: deploymentID,
		Content:      content,
		GeneratedBy:  actor,
	}
	if err := s.repo.Create(ctx, tenantID, rn); err != nil {
		return nil, fmt.Errorf("failed to create release notes: %w", err)
	}
	return rn, nil
}

// GetReleaseNotesByTenant returns all release notes for a tenant.
func (s *ReleaseNotesService) GetReleaseNotesByTenant(ctx context.Context, tenantID string) ([]models.ReleaseNote, error) {
	notes, err := s.repo.GetByTenant(ctx, tenantID)
	if err != nil {
		return nil, fmt.Errorf("failed to get release notes: %w", err)
	}
	return notes, nil
}

// List returns paginated release notes (handler-facing).
func (s *ReleaseNotesService) List(ctx context.Context, tenantID string, page, pageSize int, tag string) ([]models.ReleaseNote, int, error) {
	notes, err := s.repo.GetByTenant(ctx, tenantID)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to list release notes: %w", err)
	}
	if tag != "" {
		filtered := make([]models.ReleaseNote, 0, len(notes))
		for _, n := range notes {
			if n.Content != "" {
				filtered = append(filtered, n)
			}
		}
		notes = filtered
	}
	total := len(notes)
	// Simple in-memory pagination
	start := (page - 1) * pageSize
	if start > total {
		return []models.ReleaseNote{}, total, nil
	}
	end := start + pageSize
	if end > total {
		end = total
	}
	return notes[start:end], total, nil
}

// Create creates a new release note (handler-facing).
func (s *ReleaseNotesService) Create(ctx context.Context, tenantID string, req *models.CreateReleaseNoteRequest) (*models.ReleaseNote, error) {
	rn := &models.ReleaseNote{
		ID:           uuid.New().String(),
		DeploymentID: req.DeploymentID,
		Content:      req.Content,
	}
	if err := s.repo.Create(ctx, tenantID, rn); err != nil {
		return nil, fmt.Errorf("failed to create release note: %w", err)
	}
	return rn, nil
}

// GetByID returns a release note by ID.
func (s *ReleaseNotesService) GetByID(ctx context.Context, tenantID, id string) (*models.ReleaseNote, error) {
	notes, err := s.repo.GetByTenant(ctx, tenantID)
	if err != nil {
		return nil, err
	}
	for _, n := range notes {
		if n.ID == id {
			return &n, nil
		}
	}
	return nil, fmt.Errorf("release note not found")
}

// Update updates a release note (handler-facing, map-based).
func (s *ReleaseNotesService) Update(ctx context.Context, tenantID, id string, updates map[string]interface{}) (*models.ReleaseNote, error) {
	notes, err := s.repo.GetByTenant(ctx, tenantID)
	if err != nil {
		return nil, err
	}
	for _, n := range notes {
		if n.ID == id {
			if v, ok := updates["content"]; ok {
				n.Content = fmt.Sprint(v)
			}
			if err := s.repo.Update(ctx, tenantID, n.DeploymentID, n.Content); err != nil {
				return nil, fmt.Errorf("failed to update release note: %w", err)
			}
			return &n, nil
		}
	}
	return nil, fmt.Errorf("release note not found")
}

// Delete deletes a release note by ID.
func (s *ReleaseNotesService) Delete(ctx context.Context, tenantID, id string) error {
	return s.repo.Delete(ctx, tenantID, id)
}

func buildReleaseNotes(deploymentID string, req *models.GenerateReleaseNotesRequest, actor string) string {
	if req == nil {
		return fmt.Sprintf("Release notes for deployment %s\nGenerated by: %s\n", deploymentID, actor)
	}
	var content string
	if req.FromCommit != "" || req.ToCommit != "" {
		content += fmt.Sprintf("Commit range: %s -> %s\n", req.FromCommit, req.ToCommit)
	}
	if req.Template != "" {
		content += fmt.Sprintf("Template: %s\n", req.Template)
	}
	content += fmt.Sprintf("Generated by: %s\n", actor)
	return fmt.Sprintf("Release Notes\n================\n\nDeployment: %s\n\n%s", deploymentID, content)
}
