// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Count(ctx context.Context, tenantID string) int, error
	Create(ctx context.Context, s *models.ScheduledNotification) error
	CreateLog(ctx context.Context, log *models.ExecutionLog) error
	Delete(ctx context.Context, id string, tenantID string) bool, error
	GetByID(ctx context.Context, id string, tenantID string) *models.ScheduledNotification, error
	List(ctx context.Context, tenantID string, filter *models.ListFilter, limit offset int) []models.ScheduledNotification, error
	ListLogsBySchedule(ctx context.Context, scheduleID string) []models.ExecutionLog, error
	Update(ctx context.Context, schedule *models.ScheduledNotification) *models.ScheduledNotification, error
	UpdateFields(ctx context.Context, id string, tenantID string, updates map[string]interface{}) *models.ScheduledNotification, error
}
