// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/scheduled-notification/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, s *models.ScheduledNotification) error
	GetByID(ctx context.Context, id string, tenantID string) (*models.ScheduledNotification, error)
	List(ctx context.Context, tenantID string, filter *models.ListFilter, limit, offset int) ([]models.ScheduledNotification, error)
	Count(ctx context.Context, tenantID string) (int, error)
	Update(ctx context.Context, schedule *models.ScheduledNotification) (*models.ScheduledNotification, error)
	UpdateFields(ctx context.Context, id string, tenantID string, updates map[string]interface{}) (*models.ScheduledNotification, error)
	Delete(ctx context.Context, id string, tenantID string) (bool, error)
	CreateLog(ctx context.Context, log *models.ExecutionLog) error
	ListLogsBySchedule(ctx context.Context, scheduleID string) ([]models.ExecutionLog, error)
}
