/**
 * RiskReportRepository - PostgreSQL Repository for Risk Reports
 *
 * Stores risk assessment reports generated by RiskAssessmentService.
 */

import { BaseRepository } from '../db/base-repository';
import { OrionError, ErrorCode } from '../errors';

// ==================== Entity Interfaces ====================

export interface RiskReportEntity {
  id: string;
  tenantId: string;
  assessmentId: string;
  riskScore: number;
  riskLevel: string;
  canDeploy: boolean;
  criticalRiskCount: number;
  summary: Record<string, unknown>;
  details: Record<string, unknown>;
  recommendations: Record<string, unknown>[];
  generatedAt: Date;
  createdAt: Date;
}

export interface CreateRiskReportInput {
  tenant_id: string;
  assessment_id: string;
  risk_score: number;
  risk_level: string;
  can_deploy: boolean;
  critical_risk_count: number;
  summary: Record<string, unknown>;
  details: Record<string, unknown>;
  recommendations: Record<string, unknown>[];
  generated_at?: Date;
}

// ==================== Repository Class ====================

export class RiskReportRepository extends BaseRepository<RiskReportEntity> {
  constructor(db: { query: (text: string, params?: unknown[]) => Promise<{ rows: any[]; rowCount: number | null }> }) {
    super(db, 'risk_reports');
  }

  async findByTenant(tenantId: string, options?: { limit?: number; offset?: number }): Promise<RiskReportEntity[]> {
    const limit = options?.limit ?? 20;
    const offset = options?.offset ?? 0;
    const result = await this.db.query(
      `SELECT * FROM risk_reports WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3`,
      [tenantId, limit, offset],
    );
    return result.rows.map(row => this.mapRowToEntity(row));
  }

  async findByAssessment(assessmentId: string): Promise<RiskReportEntity | null> {
    const result = await this.db.query(
      `SELECT * FROM risk_reports WHERE assessment_id = $1 ORDER BY created_at DESC LIMIT 1`,
      [assessmentId],
    );
    if (result.rows.length === 0) return null;
    return this.mapRowToEntity(result.rows[0]);
  }

  async findByRiskLevel(riskLevel: string, tenantId?: string): Promise<RiskReportEntity[]> {
    let query = `SELECT * FROM risk_reports WHERE risk_level = $1`;
    const params: unknown[] = [riskLevel];

    if (tenantId) {
      query += ` AND tenant_id = $2`;
      params.push(tenantId);
    }

    query += ` ORDER BY created_at DESC`;
    const result = await this.db.query(query, params);
    return result.rows.map(row => this.mapRowToEntity(row));
  }

  async findDeployable(tenantId: string): Promise<RiskReportEntity[]> {
    const result = await this.db.query(
      `SELECT * FROM risk_reports WHERE tenant_id = $1 AND can_deploy = true ORDER BY risk_score ASC, created_at DESC`,
      [tenantId],
    );
    return result.rows.map(row => this.mapRowToEntity(row));
  }

  async findAll(options?: { limit?: number; offset?: number }): Promise<{ entities: RiskReportEntity[]; total: number }> {
    const limit = options?.limit ?? 20;
    const offset = options?.offset ?? 0;
    const result = await this.db.query(
      `SELECT * FROM risk_reports ORDER BY created_at DESC LIMIT $1 OFFSET $2`,
      [limit, offset],
    );
    const countResult = await this.db.query(`SELECT COUNT(*) as count FROM risk_reports`);
    return {
      entities: result.rows.map(row => this.mapRowToEntity(row)),
      total: parseInt(countResult.rows[0].count, 10),
    };
  }

  async findById(id: string): Promise<RiskReportEntity | undefined> {
    const result = await this.db.query(
      `SELECT * FROM risk_reports WHERE id = $1`,
      [id],
    );
    if (result.rows.length === 0) return undefined;
    return this.mapRowToEntity(result.rows[0]);
  }

  async createReport(input: CreateRiskReportInput): Promise<RiskReportEntity> {
    const result = await this.db.query(
      `INSERT INTO risk_reports
        (tenant_id, assessment_id, risk_score, risk_level, can_deploy, critical_risk_count, summary, details, recommendations, generated_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
       RETURNING *`,
      [
        input.tenant_id,
        input.assessment_id,
        input.risk_score,
        input.risk_level,
        input.can_deploy,
        input.critical_risk_count,
        input.summary,
        input.details,
        input.recommendations,
        input.generated_at ?? new Date(),
      ],
    );
    if (result.rows.length === 0) throw new OrionError('INSERT returned no rows', ErrorCode.OPERATION_FAILED);
    return this.mapRowToEntity(result.rows[0]);
  }

  protected mapRowToEntity(row: any): RiskReportEntity {
    return {
      id: row.id,
      tenantId: row.tenant_id,
      assessmentId: row.assessment_id,
      riskScore: parseFloat(row.risk_score),
      riskLevel: row.risk_level,
      canDeploy: row.can_deploy,
      criticalRiskCount: row.critical_risk_count,
      summary: row.summary ?? {},
      details: row.details ?? {},
      recommendations: row.recommendations ?? [],
      generatedAt: row.generated_at,
      createdAt: row.created_at,
    };
  }
}

export default RiskReportRepository;