// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for ai-models.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/ai-models/models"
)

// ServiceInterface defines the interface for the ai-models service.
type ServiceInterface interface {
	ConfigureCanary(ctx context.Context, tenantID, modelID string, req models.CanaryConfigRequest) (*models.CanaryConfig, error)
	DeleteModel(ctx context.Context, tenantID, modelID string) error
	GetCanaryConfig(ctx context.Context, tenantID, modelID string) (*models.CanaryConfig, error)
	GetModel(ctx context.Context, tenantID, modelID string) (*models.AIModel, error)
	GetModelMetrics(ctx context.Context, tenantID, modelID string) (*models.ModelMetricsResponse, error)
	GetVersion(ctx context.Context, tenantID, modelID, versionID string) (*models.ModelVersion, error)
	ListModels(ctx context.Context, tenantID string, q models.ListModelsQuery) (*models.ModelListResponse, error)
	ListVersions(ctx context.Context, tenantID, modelID string, q models.ListVersionsQuery) (*models.VersionListResponse, error)
	PromoteVersion(ctx context.Context, tenantID, modelID, versionID, userID string, req models.PromoteVersionRequest) (*models.ModelVersion, error)
	PublishVersion(ctx context.Context, tenantID, modelID, userID string, req models.PublishVersionRequest) (*models.ModelVersion, error)
	RegisterModel(ctx context.Context, tenantID, userID string, req models.RegisterModelRequest) (*models.AIModel, error)
	RollbackVersion(ctx context.Context, tenantID, modelID string) (*models.ModelVersion, error)
	StopCanary(ctx context.Context, tenantID, modelID string) error
	UpdateModel(ctx context.Context, tenantID, modelID string, req models.UpdateModelRequest) (*models.AIModel, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
