// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	ClearDefaultForPipeline(ctx context.Context, tenantID pipelineID string) error
	CreateVersion(ctx context.Context, v *models.Version) error
	DeleteVersion(ctx context.Context, tenantID id string) bool, error
	GetVersion(ctx context.Context, tenantID id string) *models.Version, error
	ListPublishedVersions(ctx context.Context, tenantID pipelineID string) []models.Version, error
	ListVersions(ctx context.Context, tenantID pipelineID string, q *models.ListQuery) *models.VersionListResult, error
	SetStatusDeprecated(ctx context.Context, tenantID id string) error
	SetStatusPublished(ctx context.Context, tenantID id string, publishedAt time.Time, isDefault bool) error
	UpdateVersion(ctx context.Context, tenantID id string, updates map[string]any) *models.Version, error
}
