// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for subapp.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/subapp/models"
)

// ServiceInterface defines the interface for the subapp service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, createdBy *string, req models.CreateSubAppRequest) (*models.SubApp, error)
	Delete(ctx context.Context, tenantID, key string, changedBy *string) error
	GetAll(ctx context.Context, tenantID string) ([]models.SubApp, error)
	GetByKey(ctx context.Context, tenantID, key string) (*models.SubApp, error)
	GetEnabled(ctx context.Context, tenantID string) ([]models.SubApp, error)
	GetHistory(ctx context.Context, tenantID, key string) ([]models.SubAppConfigHistory, error)
	ToggleStatus(ctx context.Context, tenantID, key string, changedBy *string) (*models.SubApp, error)
	Update(ctx context.Context, tenantID, key string, updatedBy *string, req models.UpdateSubAppRequest) (*models.SubApp, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
