// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for security-compliance.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the security-compliance service.
type ServiceInterface interface {
	AutoRemediateCompliance(ctx context.Context, tenantID string, req models.RemediationRequest) (*models.RemediationResult, error)
	CloseFinding(ctx context.Context, tenantID, findingID string, reason string) error
	CollectEvidence(ctx context.Context, tenantID string, req models.CollectEvidenceRequest) (*models.EvidenceCollection, error)
	CreateAuditPlan(ctx context.Context, tenantID string, req models.CreateAuditPlanRequest) (*models.AuditPlan, error)
	DefinePolicy(ctx context.Context, tenantID string, req models.CreatePolicyRequest) (*models.CompliancePolicy, error)
	EvaluateCompliance(ctx context.Context, tenantID string, req models.EvaluateComplianceRequest) (*models.ComplianceEvaluationResult, error)
	ExecuteAudit(ctx context.Context, tenantID, planID string) (*models.AuditExecution, error)
	GenerateEvidenceCollection(ctx context.Context, tenantID string, req models.CollectEvidenceRequest) (*models.EvidenceCollection, error)
	GetAuditFindings(ctx context.Context, tenantID, reportID string) ([]models.AuditFinding, error)
	GetAuditReport(ctx context.Context, tenantID, executionID string) (*models.AuditReport, error)
	GetComplianceReport(ctx context.Context, tenantID, policyID string) (*models.ComplianceReport, error)
	GetComplianceScore(ctx context.Context, tenantID string) (*models.ComplianceScore, error)
	GetEvidence(ctx context.Context, tenantID, policyID string) ([]models.Evidence, error)
	GetFramework(ctx context.Context, tenantID, id string) (*models.ComplianceFramework, error)
	GetFrameworks(ctx context.Context, tenantID string) (*models.FrameworkList, error)
	GetPolicy(ctx context.Context, tenantID, id string) (*models.CompliancePolicy, error)
	ListAuditPlans(ctx context.Context, tenantID string, limit, offset int) ([]models.AuditPlan, error)
	ListPolicies(ctx context.Context, tenantID string, limit, offset int) ([]models.CompliancePolicy, error)
	PerformGapAnalysis(ctx context.Context, tenantID string, req models.GapAnalysisRequest) (*models.GapAnalysisResult, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
