// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, channel *models.NotificationChannel) error
	Delete(ctx context.Context, tenantID id string) bool, error
	GetByID(ctx context.Context, tenantID id string) *models.NotificationChannel, error
	List(ctx context.Context, tenantID string, filter *models.ChannelFilter) []models.NotificationChannel, int, error
	ListEnabledByType(ctx context.Context, tenantID channelType string) []models.NotificationChannel, error
	Update(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.NotificationChannel, error
}
