// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for pipeline-versions.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/pipeline-versions/models"
)

// ServiceInterface defines the interface for the pipeline-versions service.
type ServiceInterface interface {
	CompareVersions(ctx context.Context, tenantID string, req *models.CompareVersionsRequest) (*models.CompareResult, error)
	CreateVersion(ctx context.Context, tenantID, pipelineID string, req *models.CreateVersionRequest, createdBy string) (*models.Version, error)
	DeleteVersion(ctx context.Context, tenantID, versionID string) error
	DeprecateVersion(ctx context.Context, tenantID, versionID string) (*models.Version, error)
	GetVersion(ctx context.Context, tenantID, versionID string) (*models.Version, error)
	ListVersions(ctx context.Context, tenantID, pipelineID string, q *models.ListQuery) (*models.VersionListResult, error)
	PublishVersion(ctx context.Context, tenantID, versionID string, req *models.PublishVersionRequest) (*models.Version, error)
	RollbackVersion(ctx context.Context, tenantID, pipelineID string, req *models.RollbackVersionRequest) (*models.Version, error)
	UpdateVersion(ctx context.Context, tenantID, versionID string, req *models.UpdateVersionRequest) (*models.Version, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
