// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for dual-engine.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the dual-engine service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req *models.CreateDualEngineRequest) (*models.DualEngine, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.DualEngine, error)
	List(ctx context.Context, tenantID string) ([]models.DualEngine, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateDualEngineRequest) (*models.DualEngine, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
