// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/secret/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, s *models.Secret) error
	GetByID(ctx context.Context, id string) (*models.Secret, error)
	GetByTenantAndName(ctx context.Context, tenantID, name, scope string) (*models.Secret, error)
	List(ctx context.Context, tenantID string, filter *models.ListFilter) ([]models.Secret, error)
	UpdateValue(ctx context.Context, id string, encryptedValue []byte) error
	UpdateDescription(ctx context.Context, id string, description string) error
	Delete(ctx context.Context, id string) error
}
