// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for scheduled-notification.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the scheduled-notification service.
type ServiceInterface interface {
	Count(ctx context.Context, tenantID string) (int, error)
	Create(ctx context.Context, tenantID, userID string, req *models.CreateScheduleRequest) (*models.ScheduledNotification, error)
	Delete(ctx context.Context, tenantID, id string) (bool, error)
	Execute(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.ScheduledNotification, error)
	GetLogs(ctx context.Context, tenantID, id string) ([]models.ExecutionLog, error)
	List(ctx context.Context, tenantID string, filter *models.ListFilter, page, pageSize int) ([]models.ScheduledNotification, int, error)
	Pause(ctx context.Context, tenantID, id string) (*models.ScheduledNotification, error)
	Resume(ctx context.Context, tenantID, id string) (*models.ScheduledNotification, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateScheduleRequest) (*models.ScheduledNotification, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
