// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for billing.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the billing service.
type ServiceInterface interface {
	CreateAccount(ctx context.Context, tenantID string, req *models.CreateAccountRequest) (*models.Account, error)
	CreateInvoice(ctx context.Context, tenantID string, req *models.CreateInvoiceRequest) (*models.Invoice, error)
	CreateLineItem(ctx context.Context, tenantID string, req *models.CreateLineItemRequest) (*models.LineItem, error)
	CreateSubscription(ctx context.Context, tenantID string, req *models.CreateSubscriptionRequest) (*models.Subscription, error)
	DeleteAccount(ctx context.Context, tenantID, id string) error
	DeleteInvoice(ctx context.Context, tenantID, id string) error
	DeleteSubscription(ctx context.Context, tenantID, id string) error
	GetAccount(ctx context.Context, tenantID, id string) (*models.Account, error)
	GetBillingStats(ctx context.Context, tenantID string) (*models.BillingStats, error)
	GetInvoice(ctx context.Context, tenantID, id string) (*models.Invoice, error)
	GetSubscription(ctx context.Context, tenantID, id string) (*models.Subscription, error)
	ListAccounts(ctx context.Context, tenantID string, status *string) ([]models.Account, error)
	ListInvoices(ctx context.Context, tenantID string, filter *models.InvoiceFilter) ([]models.Invoice, int, error)
	ListLineItems(ctx context.Context, tenantID, invoiceID string) ([]models.LineItem, error)
	ListSubscriptions(ctx context.Context, tenantID string, status *string) ([]models.Subscription, error)
	UpdateAccount(ctx context.Context, tenantID, id string, req *models.UpdateAccountRequest) (*models.Account, error)
	UpdateInvoice(ctx context.Context, tenantID, id string, updates map[string]any) (*models.Invoice, error)
	UpdateSubscription(ctx context.Context, tenantID, id string, req *models.UpdateSubscriptionRequest) (*models.Subscription, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
