// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for incident-action.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/incident-action/models"
)

// ServiceInterface defines the interface for the incident-action service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, e *models.IncidentAction) (*models.IncidentAction, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.IncidentAction, error)
	List(ctx context.Context, tenantID string) ([]models.IncidentAction, error)
	Update(ctx context.Context, tenantID, id string, updates map[string]any) (*models.IncidentAction, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
