// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for finops.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the finops service.
type ServiceInterface interface {
	ApplyOptimization(ctx context.Context, tenantID string, id string) (bool, error)
	CompareCosts(ctx context.Context, tenantID string, serviceA string, serviceB string, period string) (*models.CostComparisonResult, error)
	CreateBudgetGuard(ctx context.Context, req *models.CreateBudgetGuardRequest, tenantID string) (*models.BudgetGuard, error)
	DeleteBudgetGuard(ctx context.Context, id string, tenantID string) (bool, error)
	DetectAnomalies(ctx context.Context, tenantID string, days *int, startStr *string, endStr *string) (*models.AnomalyDetectionResult, error)
	EvaluateCost(ctx context.Context, tenantID string, pipelineID string, estimatedCost float64, projectID *string, environment *string) (*models.EvaluationResult, error)
	GetBudgetGuard(ctx context.Context, id string, tenantID string) (*models.BudgetGuard, error)
	GetCostOverview(ctx context.Context, tenantID string) (*models.CostOverview, error)
	GetCostTrend(ctx context.Context, tenantID string, days int) (*models.CostTrendResult, error)
	GetOptimizationSuggestions(ctx context.Context, tenantID string, category *string, minSavings *float64) ([]models.OptimizationSuggestion, error)
	GetServiceCostTrend(ctx context.Context, tenantID string, serviceID string, period string) (*models.CostTrendResult, error)
	GetServiceOptimizationSuggestions(ctx context.Context, tenantID string, serviceID string, entityType string) ([]models.OptimizationSuggestion, error)
	ListBudgetGuards(ctx context.Context, tenantID string) ([]models.BudgetGuard, error)
	RejectOptimization(ctx context.Context, tenantID string, id string) (bool, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
