// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for queue.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/queue/models"
)

// ServiceInterface defines the interface for the queue service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateQueueRequest) (*models.Queue, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.Queue, error)
	List(ctx context.Context, tenantID string) ([]models.Queue, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateQueueRequest) (*models.Queue, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
