// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for artifact.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/artifact/models"
)

// ServiceInterface defines the interface for the artifact service.
type ServiceInterface interface {
	AddTags(ctx context.Context, tenantID, id string, tags []string) error
	Create(ctx context.Context, tenantID string, req models.CreateArtifactRequest) (*models.Artifact, error)
	Delete(ctx context.Context, tenantID, id string) error
	Deprecate(ctx context.Context, tenantID, id string) (*models.Artifact, error)
	Download(ctx context.Context, tenantID, id string, req models.DownloadArtifactRequest) (*models.Artifact, error)
	Get(ctx context.Context, tenantID, id string) (*models.Artifact, error)
	GetCurrentStage(ctx context.Context, tenantID, id string) (*string, error)
	GetDownloadHistory(ctx context.Context, tenantID, id string) ([]models.ArtifactDownload, error)
	GetNamespaces(ctx context.Context, tenantID string) ([]models.NamespaceStat, error)
	GetPromotionHistory(ctx context.Context, tenantID, id string) ([]models.ArtifactPromotion, error)
	GetStats(ctx context.Context, tenantID string) (*models.ArtifactStats, error)
	GetTags(ctx context.Context, tenantID, id string) ([]string, error)
	GetTypeStats(ctx context.Context, tenantID string) ([]models.ArtifactTypeStat, error)
	List(ctx context.Context, tenantID string, q models.ListArtifactsQuery) (*models.ArtifactListResponse, error)
	Promote(ctx context.Context, tenantID, id string, req models.PromoteArtifactRequest) (*models.ArtifactPromotion, error)
	Quarantine(ctx context.Context, tenantID, id string, req models.QuarantineArtifactRequest) (*models.Artifact, error)
	RemoveTags(ctx context.Context, tenantID, id string, tags []string) error
	Search(ctx context.Context, tenantID string, query string, limit, offset int) ([]models.Artifact, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateArtifactRequest) (*models.Artifact, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
