// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for vectorize-rules.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the vectorize-rules service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateVectorizeRulesRequest) (*models.VectorizeRules, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.VectorizeRules, error)
	List(ctx context.Context, tenantID string) ([]models.VectorizeRules, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateVectorizeRulesRequest) (*models.VectorizeRules, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
