// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for supply-chain.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/supply-chain/models"
)

// ServiceInterface defines the interface for the supply-chain service.
type ServiceInterface interface {
	AnalyzeDependencies(ctx context.Context, tenantID, packageName, version string, depth int) error
	GenerateSBOM(ctx context.Context, tenantID string, req *models.GenerateSBOMRequest) (*models.SBOM, error)
	GenerateSupplyChainReport(ctx context.Context, tenantID, pipelineID, artifactID string) (*models.SupplyChainReport, error)
	GetDependencyGraph(ctx context.Context, tenantID, packageName, version string) (*models.DependencyGraph, error)
	GetSBOM(ctx context.Context, tenantID, sbomID string) (*models.SBOM, error)
	GetSupplyChainReport(ctx context.Context, tenantID, pipelineID string) (*models.SupplyChainReport, error)
	GetVulnerabilitiesForComponent(ctx context.Context, name, version string) ([]models.Vulnerability, error)
	ListSBOMs(ctx context.Context, tenantID string, q models.ListSBOMsQuery) ([]models.SBOM, error)
	SignArtifact(ctx context.Context, tenantID, artifactID string, req *models.SignArtifactRequest) (*models.ArtifactSignature, error)
	VerifyArtifactSignature(ctx context.Context, artifactID, signature string, req *models.VerifySignatureRequest) (*models.ArtifactSignature, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
