// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for pipeline-version.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the pipeline-version service.
type ServiceInterface interface {
	AddTag(ctx context.Context, versionID string, tenantID string, tag string) (*models.PipelineVersion, error)
	CreateVersion(ctx context.Context, pipelineID string, tenantID string, req *models.CreateVersionRequest) (*models.PipelineVersion, error)
	DiffVersions(ctx context.Context, fromID string, toID string, tenantID string) (*models.DiffResult, error)
	GetVersion(ctx context.Context, id string, tenantID string) (*models.PipelineVersion, error)
	GetVersionByPipelineAndVersion(ctx context.Context, pipelineID string, version string, tenantID string) (*models.PipelineVersion, error)
	ListVersionsByPipeline(ctx context.Context, pipelineID string, tenantID string) ([]models.PipelineVersion, int, error)
	RemoveTag(ctx context.Context, versionID string, tenantID string, tag string) (*models.PipelineVersion, error)
	Rollback(ctx context.Context, versionID string, tenantID string) (*models.PipelineVersion, error)
	SetBaseline(ctx context.Context, versionID string, tenantID string, set bool) (*models.PipelineVersion, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
