// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for ai-agents.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/ai-agents/models"
	"orion/platform-svc-go/internal/ai-agents/repository"
)

// ServiceInterface defines the interface for the ai-agents service.
type ServiceInterface interface {
	AgentAuditLogToResponse(log *models.AgentAuditLog) (*models.AgentAuditLogResponse, error)
	AgentToInfo(a *models.AIAgent) (*models.AgentInfo, error)
	CountAgents(ctx context.Context, tenantID string, filter *repository.ListFilter) (int64, error)
	DeleteAgent(ctx context.Context, id string, tenantID string) (bool, error)
	ExecuteAgent(ctx context.Context, agentID string, tenantID string, req *models.ExecuteAgentRequest) (*models.ExecuteAgentResult, error)
	GetAgent(ctx context.Context, id string, tenantID string) (*models.AIAgent, error)
	GetAgentStats(ctx context.Context, tenantID string) (*models.AgentStats, error)
	GetAuditLogs(ctx context.Context, agentID string, tenantID string, limit int) ([]models.AgentAuditLog, error)
	ListAgents(ctx context.Context, tenantID string, filter *repository.ListFilter) ([]models.AIAgent, error)
	RecordAuditLog(ctx context.Context, tenantID string, log *models.AgentAuditLog) error
	RegisterAgent(ctx context.Context, tenantID, userID string, req *models.RegisterAgentRequest) (*models.AIAgent, error)
	UpdateAgent(ctx context.Context, id string, tenantID string, req *models.UpdateAgentRequest) (*models.AIAgent, error)
	UpdateAgentStatus(ctx context.Context, id string, tenantID string, status models.AgentStatus) (*models.AIAgent, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
