// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for auth.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the auth service.
type ServiceInterface interface {
	GetProfile(ctx context.Context, tenantID, userID string) (*models.MeResponse, error)
	Login(ctx context.Context, req *models.LoginRequest, requestedTenantID string) (*models.LoginResponse, error)
	Logout(ctx context.Context, req *models.LogoutRequest) error
	Refresh(ctx context.Context, req *models.RefreshRequest) (*models.RefreshResponse, error)
	Register(ctx context.Context, req *models.RegisterRequest, requestedTenantID string) (*models.RegisterResponse, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
