// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	GetRunDetail(ctx context.Context, runID string) *RunDetail, error
}
