// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for sprint.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/sprint/models"
)

// ServiceInterface defines the interface for the sprint service.
type ServiceInterface interface {
	AddTicket(ctx context.Context, tenantID, sprintID string, req models.AddTicketRequest) (*models.SprintTicket, error)
	Create(ctx context.Context, tenantID string, req models.CreateSprintRequest) (*models.Sprint, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.Sprint, error)
	GetBoard(ctx context.Context, tenantID, sprintID string) (*models.SprintBoard, error)
	GetBurndownData(ctx context.Context, tenantID, sprintID string) (*models.BurndownData, error)
	List(ctx context.Context, tenantID string, limit, offset int) ([]models.Sprint, error)
	RemoveTicket(ctx context.Context, tenantID, sprintID, ticketID string) error
	ReorderTickets(ctx context.Context, tenantID, sprintID string, req models.ReorderTicketsRequest) error
	Update(ctx context.Context, tenantID, id string, req models.UpdateSprintRequest) (*models.Sprint, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
