// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, m *models.NotificationManagement) error
	Delete(ctx context.Context, tenantID id string) error
	GetByID(ctx context.Context, tenantID id string) *models.NotificationManagement, error
	List(ctx context.Context, tenantID string) []models.NotificationManagement, error
	Update(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.NotificationManagement, error
}
