// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CountActiveConfigs(ctx context.Context, tenantID string) int, error
	CountTotalConfigs(ctx context.Context, tenantID string) int, error
	CreateConfig(ctx context.Context, config *models.DegradationConfig) error
	CreateHistory(ctx context.Context, history *models.DegradationHistory) error
	DeleteConfig(ctx context.Context, tenantID configID string) error
	GetConfig(ctx context.Context, tenantID configID string) *models.DegradationConfig, error
	GetHistoryList(ctx context.Context, tenantID configID string, q models.ListHistoryQuery) *models.HistoryListResponse, error
	GetLatestTriggeredHistory(ctx context.Context, tenantID configID string) *models.DegradationHistory, error
	GetServiceSummary(ctx context.Context, tenantID string) []ServiceSummary, error
	ListConfigs(ctx context.Context, tenantID string, q models.ListConfigsQuery) *models.ConfigListResponse, error
	SumTriggerCounts(ctx context.Context, tenantID string) int, error
	UpdateConfig(ctx context.Context, tenantID configID string, name *string, description *string, triggers *string, actions *string, recovery *string, metadata *string) *models.DegradationConfig, error
	UpdateConfigRecovered(ctx context.Context, tenantID configID string) error
	UpdateConfigStatus(ctx context.Context, tenantID configID string, enabled bool, status models.DegradationStatus) *models.DegradationConfig, error
	UpdateConfigTriggered(ctx context.Context, tenantID configID string, triggeredAt int64) error
	UpdateHistoryRecovered(ctx context.Context, tenantID historyID string, recoveredAt int64) error
}
