// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for runbook.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the runbook service.
type ServiceInterface interface {
	CompleteExecution(ctx context.Context, tenantID, executionID string, success bool) error
	Create(ctx context.Context, tenantID string, req models.CreateRunbookRequest) (*models.Runbook, error)
	CreateExecution(ctx context.Context, tenantID, runbookID string, req models.CreateRunbookExecutionRequest) (*models.RunbookExecution, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.Runbook, error)
	List(ctx context.Context, tenantID string, q models.ListQuery) ([]models.Runbook, int, error)
	ListExecutions(ctx context.Context, tenantID, runbookID string) ([]models.RunbookExecution, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateRunbookRequest) (*models.Runbook, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
