// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for sbom.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/sbom/models"
)

// ServiceInterface defines the interface for the sbom service.
type ServiceInterface interface {
	CompareSBOMs(ctx context.Context, fromID, toID, tenantID string) (*models.SBOMComparison, error)
	CreateAttestation(ctx context.Context, sbomID string, tenantID string, req *models.CreateAttestationRequest) (*models.SBOMAttestation, error)
	DeleteSBOM(ctx context.Context, id string, tenantID string) (bool, error)
	ExportSBOM(ctx context.Context, id string, tenantID string, format string) (*models.ExportResponse, error)
	GenerateSBOM(ctx context.Context, req *models.GenerateSBOMRequest, tenantID string) (*models.SBOMDocument, error)
	GetLicenses(ctx context.Context, sbomID string, tenantID string) ([]models.LicenseInfo, error)
	GetSBOM(ctx context.Context, id string, tenantID string) (*models.SBOMDocument, error)
	ListAttestations(ctx context.Context, sbomID string, tenantID string) ([]models.SBOMAttestation, error)
	ListComponents(ctx context.Context, sbomID string, tenantID string, offset, limit int) ([]models.SBOMComponent, int, error)
	ListSBOMs(ctx context.Context, tenantID string, q *models.ListQuery) ([]models.SBOMDocument, int, error)
	ListVulnerabilities(ctx context.Context, sbomID string, tenantID string, severity *string, offset, limit int) ([]models.Vulnerability, int, error)
	ScanSBOM(ctx context.Context, id string, tenantID string, req *models.ScanRequest) (*models.SBOMDocument, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
