// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for test-selector.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/test-selector/models"
)

// ServiceInterface defines the interface for the test-selector service.
type ServiceInterface interface {
	CreateTestSuite(ctx context.Context, tenantID string, req models.CreateTestSuiteRequest) (*models.TestSuite, error)
	DeleteTestSuite(ctx context.Context, tenantID, id string) error
	GetAllTestHistory(ctx context.Context, tenantID string) ([]*models.TestHistoryStats, error)
	GetCases(ctx context.Context, tenantID string, suiteID *string, flakyThreshold *float64) ([]models.TestCase, error)
	GetCoverage(ctx context.Context, tenantID string) (models.CoverageStats, error)
	GetFlakyTests(ctx context.Context, tenantID string, threshold *float64) ([]string, float64, error)
	GetImpactAnalysis(ctx context.Context, tenantID, file string) (*models.ImpactAnalysisResult, error)
	GetPRTestResult(ctx context.Context, tenantID, prID string) (*models.PRTestResultResponse, error)
	GetRecommendations(ctx context.Context, tenantID string, req models.RecommendationRequest) (*models.TestExecutionPlan, error)
	GetStats(ctx context.Context, tenantID string) (*models.TestSelectorStats, error)
	GetSuites(ctx context.Context, tenantID string) ([]models.TestSuite, error)
	GetTestCoverage(ctx context.Context, tenantID string) (models.CoverageStats, error)
	GetTestHistory(ctx context.Context, tenantID, testID string) (*models.TestHistoryStats, error)
	GetTestPlan(ctx context.Context, tenantID, planID string) (*models.TestExecutionPlan, error)
	GetTestSuite(ctx context.Context, tenantID, id string) (*models.TestSuite, error)
	ListFiles(ctx context.Context, tenantID string) ([]string, error)
	ListTestSuites(ctx context.Context, tenantID string) ([]models.TestSuite, error)
	Reanalyze(ctx context.Context, tenantID string) error
	RecordTestResult(ctx context.Context, tenantID string, req models.RecordTestResultRequest) error
	RunTestSuite(ctx context.Context, tenantID, id string) error
	SelectTestsForPR(ctx context.Context, tenantID string, change models.PRChange) (*models.TestExecutionPlan, error)
	UpdateTestSuite(ctx context.Context, tenantID, id string, req models.UpdateTestSuiteRequest) (*models.TestSuite, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
