// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/user/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, user *models.User) error
	GetByID(ctx context.Context, tenantID, id string) (*models.User, error)
	GetByUsername(ctx context.Context, username string) (*models.User, error)
	GetByEmail(ctx context.Context, email string) (*models.User, error)
	List(ctx context.Context, tenantID string, filter *models.GetUserFilters, offset, limit int) ([]models.User, error)
	Count(ctx context.Context, tenantID string) (int, error)
	Update(ctx context.Context, tenantID, id string, updates map[string]interface{}) error
	UpdatePassword(ctx context.Context, id string, newPasswordHash string) error
	Delete(ctx context.Context, tenantID, id string) error
}
