// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/user-token/models"
	"time"
)

// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, tenantID, userID string, name string, expiresAt *time.Time) (*models.Token, error)
	ListByUserID(ctx context.Context, tenantID, userID string) ([]models.Token, error)
	GetByID(ctx context.Context, tenantID, id string) (*models.Token, error)
	Delete(ctx context.Context, tenantID, id string) error
	EnsureTable(ctx context.Context) error
}
