apiVersion: v1
kind: Service
metadata:
  name: orion-knowledge-svc
  namespace: orion
  labels:
    app: orion-knowledge-svc
    component: knowledge-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3020
      protocol: TCP
  selector:
    app: orion-knowledge-svc
---
apiVersion: v1
kind: Service
metadata:
  name: orion-knowledge-svc-nodeport
  namespace: orion
  labels:
    app: orion-knowledge-svc
    component: knowledge-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 3020
      targetPort: 3020
      nodePort: 30220
      protocol: TCP
  selector:
    app: orion-knowledge-svc