// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	GetRunHistoryCompare(ctx context.Context, pipelineIDs []string, period granularity string) map[string][]models.TrendEntry, error
	GetRunHistoryTrend(ctx context.Context, pipelineID period granularity string) []models.TrendEntry, error
}
