// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CountForEffectiveness(ctx context.Context, tenantID string, q models.EffectivenessQuery) int, error
	CreateApprovalRequest(ctx context.Context, incidentID title string, req models.RespondApprovalRequest, riskLevel string, actions []models.HealingAction, expiresAt *time.Time) *models.ApprovalRequest, error
	CreateIncident(ctx context.Context, tenantID string, req models.CreateIncidentRequest) *models.HealingIncident, error
	CreateStrategy(ctx context.Context, s *models.HealingStrategy) error
	GetApprovalRequest(ctx context.Context, id string) *models.ApprovalRequest, error
	GetIncident(ctx context.Context, tenantID id string) *models.HealingIncident, error
	GetIncidentByApprovalID(ctx context.Context, tenantID approvalID string) *models.HealingIncident, error
	GetStrategy(ctx context.Context, id string) *models.HealingStrategy, error
	ListApprovalRequests(ctx context.Context, status string) []models.ApprovalRequest, error
	ListForEffectiveness(ctx context.Context, tenantID string, q models.EffectivenessQuery) []models.HealingIncident, error
	ListIncidents(ctx context.Context, tenantID string, q models.HistoryQuery) []models.HealingIncident, int, error
	ListStrategies(ctx context.Context) []models.HealingStrategy, error
	MarkExpiredApprovals(ctx context.Context) int64, error
	ToggleStrategy(ctx context.Context, id string, enabled bool) error
	UpdateApprovalRequest(ctx context.Context, id string, updates map[string]interface{}) *models.ApprovalRequest, error
	UpdateIncident(ctx context.Context, id string, updates map[string]interface{}) *models.HealingIncident, error
}
