// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"time"
	"orion/platform-svc-go/internal/self-healing/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	CreateStrategy(ctx context.Context, s *models.HealingStrategy) error
	GetStrategy(ctx context.Context, id string) (*models.HealingStrategy, error)
	ListStrategies(ctx context.Context) ([]models.HealingStrategy, error)
	ToggleStrategy(ctx context.Context, id string, enabled bool) error
	CreateIncident(ctx context.Context, tenantID string, req models.CreateIncidentRequest) (*models.HealingIncident, error)
	GetIncident(ctx context.Context, tenantID, id string) (*models.HealingIncident, error)
	UpdateIncident(ctx context.Context, id string, updates map[string]interface{}) (*models.HealingIncident, error)
	ListIncidents(ctx context.Context, tenantID string, q models.HistoryQuery) ([]models.HealingIncident, int, error)
	CountForEffectiveness(ctx context.Context, tenantID string, q models.EffectivenessQuery) (int, error)
	ListForEffectiveness(ctx context.Context, tenantID string, q models.EffectivenessQuery) ([]models.HealingIncident, error)
	CreateApprovalRequest(ctx context.Context, incidentID, title string, req models.RespondApprovalRequest, riskLevel string, actions []models.HealingAction, expiresAt *time.Time) (*models.ApprovalRequest, error)
	GetApprovalRequest(ctx context.Context, id string) (*models.ApprovalRequest, error)
	ListApprovalRequests(ctx context.Context, status string) ([]models.ApprovalRequest, error)
	UpdateApprovalRequest(ctx context.Context, id string, updates map[string]interface{}) (*models.ApprovalRequest, error)
	MarkExpiredApprovals(ctx context.Context) (int64, error)
	GetIncidentByApprovalID(ctx context.Context, tenantID, approvalID string) (*models.HealingIncident, error)
}
