// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateOperationRequest(ctx context.Context, op *BatchOperationRequest) error
	FinalizeOperationRequest(ctx context.Context, id string, tenantID string) error
	GetOperationRequest(ctx context.Context, id string, tenantID string) *BatchOperationRequest, error
	ListOperationRequests(ctx context.Context, tenantID string, operation *string) []BatchOperationRequest, error
	RecordBatchDelete(ctx context.Context, req *models.BatchDeleteRequest, tenantID string) string, error
	RecordBatchStart(ctx context.Context, req *models.BatchStartRequest, tenantID string) string, error
	RecordBatchStop(ctx context.Context, req *models.BatchStopRequest, tenantID string) string, error
	UpdateOperationStatus(ctx context.Context, id string, tenantID string, status string) error
}
