// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Count(ctx context.Context, tenantID string) int, error
	Create(ctx context.Context, tpl *models.NotificationTemplate) error
	Delete(ctx context.Context, tenantID id string) bool, error
	GetByID(ctx context.Context, tenantID id string) *models.NotificationTemplate, error
	List(ctx context.Context, tenantID string, filter models.ListFilter, limit offset int) []models.NotificationTemplate, error
	Update(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.NotificationTemplate, error
}
