// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for policy.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/policy/models"
)

// ServiceInterface defines the interface for the policy service.
type ServiceInterface interface {
	CreateOverride(ctx context.Context, tenantID string, req models.CreateOverrideRequest, overrideBy string) (*models.PolicyOverride, error)
	CreatePolicy(ctx context.Context, tenantID string, req models.CreatePolicyRequest) (*models.Policy, error)
	DeletePolicy(ctx context.Context, tenantID, id string) error
	EvaluateGate(ctx context.Context, tenantID, gateID string, input map[string]any) (*models.EvaluatePolicyResponse, error)
	EvaluatePolicy(ctx context.Context, tenantID string, req models.EvaluatePolicyRequest) (*models.EvaluatePolicyResponse, error)
	GetBundle(ctx context.Context, tenantID, id string) (*models.PolicyBundle, error)
	GetEvaluationHistory(ctx context.Context, tenantID, policyID string, limit, offset int) ([]models.PolicyEvaluation, error)
	GetExemption(ctx context.Context, tenantID, id string) (*models.Exemption, error)
	GetPolicy(ctx context.Context, tenantID, id string) (*models.Policy, error)
	GetViolation(ctx context.Context, tenantID, id string) (*models.Violation, error)
	ListBundles(ctx context.Context, tenantID string) ([]models.PolicyBundle, error)
	ListEvaluations(ctx context.Context, tenantID string, limit, offset int) ([]models.PolicyEvaluation, error)
	ListExemptions(ctx context.Context, tenantID string, req models.ListExemptionsRequest) (*models.ListExemptionsResponse, error)
	ListOverrides(ctx context.Context, tenantID string, limit, offset int) ([]models.PolicyOverride, error)
	ListPolicies(ctx context.Context, tenantID string, limit, offset int) ([]models.Policy, error)
	ListViolations(ctx context.Context, tenantID string, limit, offset int) ([]models.Violation, error)
	ResolveViolation(ctx context.Context, tenantID, id string, req models.ResolveViolationRequest) error
	ReviewExemption(ctx context.Context, tenantID, id string, req models.ReviewExemptionRequest) (*models.Exemption, error)
	RevokeExemption(ctx context.Context, tenantID, id string) (*models.Exemption, error)
	SubmitExemption(ctx context.Context, tenantID string, req models.CreateExemptionRequest) (*models.Exemption, error)
	SyncBundles(ctx context.Context, tenantID string, sourceURL string) (*models.SyncBundlesResponse, error)
	TestPolicy(ctx context.Context, rego string, testCases []map[string]any) ([]models.TestCaseResult, error)
	TogglePolicy(ctx context.Context, tenantID, id string, enabled bool) (*models.Policy, error)
	UpdatePolicy(ctx context.Context, tenantID, id string, req models.UpdatePolicyRequest) (*models.Policy, error)
	WaiveViolation(ctx context.Context, tenantID, id string, req models.WaiveViolationRequest) error
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
