// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for auth-mfa.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the auth-mfa service.
type ServiceInterface interface {
	ActivateDevice(ctx context.Context, tenantID, id string) error
	CreateDevice(ctx context.Context, tenantID, userID string, req *models.CreateMFADeviceRequest) (*models.MFADevice, error)
	DeleteDevice(ctx context.Context, tenantID, id string) (bool, error)
	DisableDevice(ctx context.Context, tenantID, id string) error
	GenerateBackupCodes(ctx context.Context, tenantID, userID string) ([]string, error)
	GetDevice(ctx context.Context, tenantID, id string) (*models.MFADevice, error)
	ListDevices(ctx context.Context, tenantID, userID string, filter *models.MFADeviceFilter) ([]models.MFADevice, error)
	VerifyCode(ctx context.Context, tenantID, userID, code string) (bool, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
