// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, item *models.DualEngine) error
	Delete(ctx context.Context, tenantID id string) bool, error
	GetByID(ctx context.Context, tenantID id string) *models.DualEngine, error
	List(ctx context.Context, tenantID string) []models.DualEngine, error
	Update(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.DualEngine, error
}
