// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for workflow.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the workflow service.
type ServiceInterface interface {
	Create(ctx context.Context, req *models.CreateWorkflowRequest, tenantID string, createdBy string) (*models.Workflow, error)
	Delete(ctx context.Context, id string, tenantID string) (bool, error)
	Execute(ctx context.Context, workflowID string, tenantID string, triggeredBy string, initialInput string) (*models.WorkflowExecution, error)
	Get(ctx context.Context, id string, tenantID string) (*models.Workflow, error)
	GetExecution(ctx context.Context, executionID string, tenantID string) (*models.WorkflowExecution, error)
	List(ctx context.Context, tenantID string, status *string, page, pageSize int) ([]models.Workflow, int, error)
	ListExecutions(ctx context.Context, workflowID string, tenantID string, page, pageSize int) ([]models.WorkflowExecution, int, error)
	Pause(ctx context.Context, id string, tenantID string) (*models.Workflow, error)
	Resume(ctx context.Context, id string, tenantID string) (*models.Workflow, error)
	Update(ctx context.Context, id string, req *models.UpdateWorkflowRequest, tenantID string) (*models.Workflow, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
