// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, tenantID string, req models.CreatePipelineRequest) *models.Pipeline, error
	Delete(ctx context.Context, tenantID id string) bool, error
	GetByID(ctx context.Context, tenantID id string) *models.Pipeline, error
	GetStats(ctx context.Context, tenantID pipelineID string) *models.PipelineStats, error
	GetVersions(ctx context.Context, tenantID pipelineID string) []models.PipelineVersion, error
	List(ctx context.Context, tenantID string, opt models.ListPipelinesOptions) []models.Pipeline, int, error
	Update(ctx context.Context, tenantID id string, req models.UpdatePipelineRequest) *models.Pipeline, error
}
