// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	AddEdge(ctx context.Context, tenantID source target string, relType models.RelationType) error
	Create(ctx context.Context, tenantID string, m *models.ServiceTopology) error
	Delete(ctx context.Context, tenantID id string) error
	DetectCycles(ctx context.Context, tenantID string) [][]string, error
	EnsureTable(ctx context.Context) error
	GetByID(ctx context.Context, tenantID id string) *models.ServiceTopology, error
	GetByServiceName(ctx context.Context, tenantID serviceName string) *models.ServiceTopology, error
	GetDownstreamDependents(ctx context.Context, tenantID serviceName string) []string, error
	GetEdges(ctx context.Context, tenantID serviceName string) []models.TopologyEdge, error
	GetTopologyStats(ctx context.Context, tenantID string) *models.TopologyStats, error
	GetUpstreamDependencies(ctx context.Context, tenantID serviceName string) []string, error
	List(ctx context.Context, tenantID string) []models.ServiceTopology, error
	RemoveEdge(ctx context.Context, tenantID source target string) error
	Update(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.ServiceTopology, error
}
