// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for notification.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/notification/models"
)

// ServiceInterface defines the interface for the notification service.
type ServiceInterface interface {
	Count(ctx context.Context, tenantID string) (int, error)
	Create(ctx context.Context, tenantID string, userID string, req *models.CreateNotificationRequest) (*models.Notification, error)
	Delete(ctx context.Context, tenantID string, id string) (bool, error)
	Get(ctx context.Context, tenantID string, id string) (*models.Notification, error)
	GetStats(ctx context.Context, tenantID string) (*models.NotificationStats, error)
	List(ctx context.Context, tenantID string, filter *models.ListFilter, page int, pageSize int) ([]models.Notification, int, error)
	MarkAllRead(ctx context.Context, tenantID string, userID string) error
	MarkRead(ctx context.Context, tenantID string, id string) error
	Update(ctx context.Context, tenantID string, id string, req *models.UpdateNotificationRequest) (*models.Notification, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
