// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateAuditRule(ctx context.Context, rule *models.AuditRule) error
	CreateDataSource(ctx context.Context, ds *models.DataSource) error
	CreateOrder(ctx context.Context, o *models.SqlOrder) error
	DeleteDataSource(ctx context.Context, id string) error
	GetAuditRule(ctx context.Context, id string) *models.AuditRule, error
	GetDataSource(ctx context.Context, id string) *models.DataSource, error
	GetOrder(ctx context.Context, id string) *models.SqlOrder, error
	InsertQueryExecutionLog(ctx context.Context, rec *models.QueryExecutionRecord) error
	ListAuditRules(ctx context.Context, tenantID string) []models.AuditRule, error
	ListDataSources(ctx context.Context, tenantID string) []models.DataSource, error
	ListOrders(ctx context.Context, tenantID status string, page limit int) []models.SqlOrder, int, error
	ListQueryLogs(ctx context.Context, tenantID string, q models.QueryLogQuery) []models.QueryExecutionRecord, int, error
	UpdateAuditRule(ctx context.Context, id string, updates map[string]interface{}) *models.AuditRule, error
	UpdateDataSource(ctx context.Context, id string, updates map[string]interface{}) *models.DataSource, error
	UpdateDataSourceStatus(ctx context.Context, id status string) error
	UpdateOrderStatus(ctx context.Context, id status string, approvedBy *string, result *string) *models.SqlOrder, error
}
