// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CountCommandLogs(ctx context.Context, tenantID string) int, error
	CountCronJobLogsByJobID(ctx context.Context, jobID string) int, error
	CountCronJobs(ctx context.Context) int, error
	CountTemplates(ctx context.Context) int, error
	CountUploadTasks(ctx context.Context) int, error
	CreateCommandLog(ctx context.Context, log *models.CommandLog) error
	CreateCommandLogDetails(ctx context.Context, details []models.CommandLogDetail) error
	CreateCronJob(ctx context.Context, job *models.CronJob) error
	CreateCronJobLog(ctx context.Context, log *models.CronJobLog) error
	CreateTemplate(ctx context.Context, tmpl *models.Template) error
	CreateUploadTask(ctx context.Context, task *models.UploadTask) error
	DeleteCronJob(ctx context.Context, id string) error
	DeleteTemplate(ctx context.Context, id string) error
	GetCommandLogByID(ctx context.Context, id string) *models.CommandLog, error
	GetCommandLogDetailsByCommandID(ctx context.Context, commandID string) []models.CommandLogDetail, error
	GetCronJobByID(ctx context.Context, id string) *models.CronJob, error
	GetTemplateByID(ctx context.Context, id string) *models.Template, error
	GetUploadTaskByID(ctx context.Context, id string) *models.UploadTask, error
	ListCommandLogs(ctx context.Context, tenantID string, page pageSize int) []models.CommandLog, error
	ListCronJobLogsByJobID(ctx context.Context, jobID string, page pageSize int) []models.CronJobLog, error
	ListCronJobs(ctx context.Context) []models.CronJob, error
	ListTemplates(ctx context.Context) []models.Template, error
	ListUploadTasks(ctx context.Context) []models.UploadTask, error
	ToggleCronJob(ctx context.Context, id string, enabled bool) error
	UpdateCronJob(ctx context.Context, id string, updates map[string]interface{}) error
	UpdateCronJobLastRun(ctx context.Context, id string, lastRunAt time.Time) error
	UpdateTemplate(ctx context.Context, id string, updates map[string]interface{}) error
	UpdateUploadTask(ctx context.Context, id string, updates map[string]interface{}) error
}
