// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for version-archive.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/version-archive/models"
)

// ServiceInterface defines the interface for the version-archive service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateVersionArchiveRequest) (*models.VersionArchive, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.VersionArchive, error)
	List(ctx context.Context, tenantID string) ([]models.VersionArchive, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateVersionArchiveRequest) (*models.VersionArchive, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
