apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: orion-security-pdb
  namespace: orion
  labels:
    app: orion-security
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: orion-security
