// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, tenantID string, e *models.LTLILCLKLELTLuLALULTLOLMLALTLILOLN) *models.LTLILCLKLELTLuLALULTLOLMLALTLILOLN, error
	Delete(ctx context.Context, tenantID id string) error
	GetByID(ctx context.Context, tenantID id string) *models.LTLILCLKLELTLuLALULTLOLMLALTLILOLN, error
	List(ctx context.Context, tenantID string) []models.LTLILCLKLELTLuLALULTLOLMLALTLILOLN, error
	Update(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.LTLILCLKLELTLuLALULTLOLMLALTLILOLN, error
}
