// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for branch-policy.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the branch-policy service.
type ServiceInterface interface {
	AddTag(ctx context.Context, tenantID string, tag string) error
	Approve(ctx context.Context, tenantID, id string) error
	BatchCreate(ctx context.Context, tenantID string, reqs []models.CreateRequest) ([]models.Record, error)
	CheckCompatibility(ctx context.Context, tenantID string) (bool, error)
	Configure(ctx context.Context, tenantID string, cfg map[string]any) error
	Create(ctx context.Context, tenantID string, req models.CreateRequest) (*models.Record, error)
	Delete(ctx context.Context, tenantID, id string) error
	DeleteTag(ctx context.Context, tenantID string, tag string) error
	Deploy(ctx context.Context, tenantID, id string) error
	DeregisterModel(ctx context.Context, tenantID, id string) error
	DisablePlugin(ctx context.Context, tenantID, id string) error
	EnablePlugin(ctx context.Context, tenantID, id string) error
	EnforcePolicy(ctx context.Context, tenantID string) error
	Escalate(ctx context.Context, tenantID, id string) error
	Evaluate(ctx context.Context, tenantID string) error
	Forecast(ctx context.Context, tenantID string) (map[string]any, error)
	Get(ctx context.Context, tenantID, id string) (*models.Record, error)
	GetBranchStatus(ctx context.Context, tenantID, id string) (string, error)
	GetByUser(ctx context.Context, tenantID, user string) ([]string, error)
	GetConfig(ctx context.Context, tenantID string) (map[string]any, error)
	GetCoverage(ctx context.Context, tenantID string) (map[string]any, error)
	GetHistory(ctx context.Context, tenantID string) ([]string, error)
	GetLineage(ctx context.Context, tenantID, id string) (map[string]any, error)
	GetLogs(ctx context.Context, tenantID, id string) ([]string, error)
	GetMetrics(ctx context.Context, tenantID string) (map[string]any, error)
	GetPlugin(ctx context.Context, tenantID, id string) (map[string]any, error)
	GetResults(ctx context.Context, tenantID string) ([]string, error)
	GetStats(ctx context.Context, tenantID string) (map[string]any, error)
	GetStatus(ctx context.Context, tenantID string) (string, error)
	GetStatusMiddleware(ctx context.Context, tenantID string) (string, error)
	GetUtilization(ctx context.Context, tenantID string) (map[string]any, error)
	List(ctx context.Context, tenantID string) ([]models.Record, error)
	ListAlerts(ctx context.Context, tenantID string) ([]string, error)
	ListArtifacts(ctx context.Context, tenantID string) ([]string, error)
	ListExperiments(ctx context.Context, tenantID string) ([]string, error)
	ListHistories(ctx context.Context, tenantID string) ([]string, error)
	ListModels(ctx context.Context, tenantID string) ([]string, error)
	ListPending(ctx context.Context, tenantID string) ([]string, error)
	ListPipelines(ctx context.Context, tenantID string) ([]string, error)
	ListPlugins(ctx context.Context, tenantID string) ([]string, error)
	ListSchemas(ctx context.Context, tenantID string) ([]string, error)
	ListTemplates(ctx context.Context, tenantID string) ([]string, error)
	ListTemplates2(ctx context.Context, tenantID string) ([]string, error)
	ListViolations(ctx context.Context, tenantID string) ([]string, error)
	Pause(ctx context.Context, tenantID, id string) error
	Regenerate(ctx context.Context, tenantID string) error
	RegisterModel(ctx context.Context, tenantID string) error
	Reject(ctx context.Context, tenantID, id string) error
	Restart(ctx context.Context, tenantID string) error
	Resume(ctx context.Context, tenantID, id string) error
	Rollback(ctx context.Context, tenantID, id string) error
	RunInspection(ctx context.Context, tenantID string) error
	RunPipeline(ctx context.Context, tenantID string) error
	ScaleResource(ctx context.Context, tenantID string) error
	Search(ctx context.Context, tenantID, q string) ([]string, error)
	Train(ctx context.Context, tenantID string) error
	Trigger(ctx context.Context, tenantID string) error
	Update(ctx context.Context, tenantID, id string, req models.CreateRequest) (*models.Record, error)
	UpdateConfig(ctx context.Context, tenantID string, cfg map[string]any) error
	UpdateStatus(ctx context.Context, tenantID, id string) error
	ValidateBranch(ctx context.Context, tenantID, branch string) (bool, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
