// gen-interface generates repository_interface.go files from repository.go source files.
// It uses Go AST parsing to correctly extract public method signatures of *Repository,
// ensuring proper Go syntax (multi-value return types wrapped in parentheses).
//
// Usage:
//   go run tools/gen-interface/main.go
//
// Scans orion-platform-svc-go/internal/*/repository/repository.go and generates
// matching repository_interface.go files with correct interface syntax.

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// methodSig holds the extracted signature of a single public method on *Repository.
type methodSig struct {
	name   string
	params string // comma-separated parameter list (without "ctx context.Context")
	rets   string // return types, with parentheses for multiple returns
}

func main() {
	cwd, _ := os.Getwd()

	// Find project root (up to 5 levels)
	root := findRoot(cwd)
	if root == "" {
		fmt.Fprintln(os.Stderr, "ERROR: could not locate project root")
		os.Exit(1)
	}

	repoRoot := filepath.Join(root, "orion-platform-svc-go", "internal")

	// Collect all repository.go files
	var repos []string
	err := filepath.Walk(repoRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if !info.IsDir() && info.Name() == "repository.go" {
			repos = append(repos, path)
		}
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR walking %s: %v\n", repoRoot, err)
		os.Exit(1)
	}

	sort.Strings(repos)

	created := 0
	skipped := 0
	errCount := 0

	for _, repoFile := range repos {
		ifacePath := repoFile[:len(repoFile)-3] + "_interface.go"

		sig, err := extractInterface(repoFile)
		if err != nil {
			fmt.Printf("  %-40s SKIP (%v)\n", moduleName(repoFile), err)
			skipped++
			continue
		}
		if sig == "" {
			continue
		}

		// Write interface file
		err = os.WriteFile(ifacePath, []byte(sig), 0644)
		if err != nil {
			fmt.Printf("  %-40s ERROR (%v)\n", moduleName(repoFile), err)
			errCount++
			continue
		}
		created++
		fmt.Printf("  %-40s OK\n", moduleName(repoFile))
	}

	fmt.Printf("\nSummary: created=%d skipped=%d errors=%d\n", created, skipped, errCount)
}

// extractInterface parses a repository.go file and returns a valid interface definition string.
func extractInterface(repoFile string) (string, error) {
	src, err := os.ReadFile(repoFile)
	if err != nil {
		return "", err
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, repoFile, src, 0)
	if err != nil {
		return "", err
	}

	var methods []methodSig
	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Recv == nil || len(fn.Recv.List) == 0 {
			continue
		}
		// Only extract methods whose receiver is *Repository
		recv := exprString(fn.Recv.List[0].Type, fset)
		if recv != "*Repository" {
			continue
		}
		// Only public methods
		if !ast.IsExported(fn.Name.Name) {
			continue
		}

		params := formatParamList(fn.Type.Params, fset)
		rets := formatReturnList(fn.Type.Results, fset)

		methods = append(methods, methodSig{
			name:   fn.Name.Name,
			params: params,
			rets:   rets,
		})
	}

	if len(methods) == 0 {
		return "", fmt.Errorf("no public methods on *Repository")
	}

	// Sort by name for deterministic output
	sort.Slice(methods, func(i, j int) bool {
		return methods[i].name < methods[j].name
	})

	return buildInterface(methods), nil
}

// buildInterface creates a valid Go interface file string.
func buildInterface(methods []methodSig) string {
	var b strings.Builder
	b.WriteString("// Code generated by tools/gen-interface/main.go. DO NOT EDIT.\n")
	b.WriteString("package repository\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString(")\n\n")
	b.WriteString("type Repository interface {\n")
	for _, m := range methods {
		b.WriteString("\t" + m.name + "(ctx context.Context")
		if m.params != "" {
			b.WriteString(", " + m.params)
		}
		b.WriteString(")")
		if m.rets != "" {
			b.WriteString(" " + m.rets)
		}
		b.WriteString("\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// formatParamList extracts the parameter list as a comma-separated Go source string.
// It skips "ctx context.Context" since we always inject that in the interface.
func formatParamList(fields *ast.FieldList, fset *token.FileSet) string {
	if fields == nil || len(fields.List) == 0 {
		return ""
	}
	var parts []string
	for _, field := range fields.List {
		t := exprString(field.Type, fset)
		// Skip "ctx context.Context" — we inject it in the interface header
		if len(field.Names) == 1 && field.Names[0].Name == "ctx" && t == "context.Context" {
			continue
		}
		if len(field.Names) == 0 {
			parts = append(parts, t)
		} else {
			names := make([]string, len(field.Names))
			for i, n := range field.Names {
				names[i] = n.Name
			}
			parts = append(parts, strings.Join(names, ", ")+", "+t)
		}
	}
	return strings.Join(parts, ", ")
}

// formatReturnList extracts return types, wrapping multi-value returns in parentheses.
func formatReturnList(fields *ast.FieldList, fset *token.FileSet) string {
	if fields == nil || len(fields.List) == 0 {
		return ""
	}
	var types []string
	for _, field := range fields.List {
		t := exprString(field.Type, fset)
		for range field.Names {
			types = append(types, t)
		}
		if len(field.Names) == 0 {
			types = append(types, t)
		}
	}
	if len(types) == 0 {
		return ""
	}
	ret := strings.Join(types, ", ")
	if len(types) > 1 {
		return "(" + ret + ")"
	}
	return ret
}

// exprString converts an AST expression to its Go source representation.
func exprString(expr ast.Expr, fset *token.FileSet) string {
	buf := strings.Builder{}
	printer.Fprint(&buf, fset, expr)
	return strings.TrimSpace(buf.String())
}

// moduleName returns the module name from a file path (last directory before repository/).
func moduleName(repoFile string) string {
	dir := filepath.Dir(repoFile)
	parent := filepath.Base(filepath.Dir(dir)) // module name
	return parent
}

// findRoot walks up looking for go.mod
func findRoot(start string) string {
	for dir := start; ; {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}
