// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for topology.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the topology service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateTopologyRequest) (*models.Topology, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.Topology, error)
	List(ctx context.Context, tenantID string) ([]models.Topology, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateTopologyRequest) (*models.Topology, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
