// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for script-library.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the script-library service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateScriptLibraryRequest) (*models.ScriptLibrary, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.ScriptLibrary, error)
	List(ctx context.Context, tenantID string) ([]models.ScriptLibrary, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateScriptLibraryRequest) (*models.ScriptLibrary, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
