// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for permission.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/permission/models"
)

// ServiceInterface defines the interface for the permission service.
type ServiceInterface interface {
	Count(ctx context.Context, tenantID string) (int, error)
	Create(ctx context.Context, tenantID, userID string, req *models.CreatePermissionRequest) (*models.Permission, error)
	Delete(ctx context.Context, tenantID, id string) error
	GetByID(ctx context.Context, tenantID, id string) (*models.Permission, error)
	List(ctx context.Context, tenantID string, filter *models.ListFilter, offset, limit int) ([]models.Permission, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdatePermissionRequest) (*models.Permission, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
