// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CheckWindowActive(ctx context.Context, tenantID string, environmentID string) bool, error
	CreateEmergencyDeploy(ctx context.Context, ed *models.EmergencyDeploy) error
	CreateProgressiveDeploy(ctx context.Context, pd *models.ProgressiveDeploy) error
	CreateWindow(ctx context.Context, w *models.DeployWindow) error
	DeleteWindow(ctx context.Context, id string, tenantID string) bool, error
	GetEmergencyDeploy(ctx context.Context, id string, tenantID string) *models.EmergencyDeploy, error
	GetProgressiveDeploy(ctx context.Context, id string, tenantID string) *models.ProgressiveDeploy, error
	GetWindowByID(ctx context.Context, id string, tenantID string) *models.DeployWindow, error
	ListEmergencyDeploys(ctx context.Context, tenantID string, status *string) []models.EmergencyDeploy, error
	ListWindows(ctx context.Context, tenantID string, environmentID *string, status *string) []models.DeployWindow, error
	UpdateEmergencyDeploy(ctx context.Context, id string, tenantID string, updates map[string]interface{}) *models.EmergencyDeploy, error
	UpdateProgressiveDeploy(ctx context.Context, id string, tenantID string, updates map[string]interface{}) *models.ProgressiveDeploy, error
	UpdateWindow(ctx context.Context, id string, tenantID string, updates map[string]interface{}) *models.DeployWindow, error
}
