// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for compliance.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/compliance/models"
)

// ServiceInterface defines the interface for the compliance service.
type ServiceInterface interface {
	CreateReport(ctx context.Context, tenantID string, req *models.CreateComplianceReportRequest) (*models.ComplianceReport, error)
	CreateSchedule(ctx context.Context, tenantID string, req *models.CreateComplianceScheduleRequest) (*models.ComplianceSchedule, error)
	DeleteReport(ctx context.Context, id, tenantID string) (bool, error)
	DeleteSchedule(ctx context.Context, id, tenantID string) (bool, error)
	GetReport(ctx context.Context, id, tenantID string) (*models.ComplianceReport, error)
	ListReports(ctx context.Context, tenantID, framework string) ([]models.ComplianceReport, error)
	ListSchedules(ctx context.Context, tenantID string) ([]models.ComplianceSchedule, error)
	UpdateReport(ctx context.Context, id, tenantID string, req *models.UpdateComplianceReportRequest) (*models.ComplianceReport, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
