// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for process-step.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/process-step/models"
)

// ServiceInterface defines the interface for the process-step service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateProcessStepRequest) (*models.ProcessStep, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.ProcessStep, error)
	List(ctx context.Context, tenantID string) ([]models.ProcessStep, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateProcessStepRequest) (*models.ProcessStep, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
