// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for user-activity.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/user-activity/models"
)

// ServiceInterface defines the interface for the user-activity service.
type ServiceInterface interface {
	CreateActivity(ctx context.Context, userID, action, resourceType, resourceID string, details any, ipAddress, userAgent string) (*models.UserActivity, error)
	DeleteActivity(ctx context.Context, userID, activityID string) error
	GetActivities(ctx context.Context, userID string, page, pageSize int) (*models.ActivitiesResponse, error)
	GetActivity(ctx context.Context, userID, activityID string) (*models.UserActivity, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
