-- Ai-Security module tables
-- No ai-security module exists in internal/. The actual security-related
-- modules (security, security-compliance, prompt-security) have their own
-- dedicated migrations. This migration no longer creates the generic
-- 'records' table (which was shared across 12+ modules).
