// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for alert.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the alert service.
type ServiceInterface interface {
	AddKnownIssue(ctx context.Context, tenantID string, req models.AddKnownIssueRequest) (*models.KnownIssue, error)
	AddMaintenanceWindow(ctx context.Context, tenantID string, req models.AddMaintenanceWindowRequest) (*models.MaintenanceWindow, error)
	Correlate(ctx context.Context, tenantID string, alerts []models.Alert) (*models.CorrelationAnalysis, error)
	DeleteAlert(ctx context.Context, tenantID, id string) error
	GetActiveAlerts(ctx context.Context, tenantID string) ([]models.Alert, error)
	GetActiveGroups(ctx context.Context, tenantID string) ([]models.AlertGroup, error)
	GetActiveMaintenanceWindows(ctx context.Context, tenantID string) ([]models.MaintenanceWindow, error)
	GetAlert(ctx context.Context, tenantID, id string) (*models.Alert, error)
	GetDedupStats(ctx context.Context, tenantID string) (*models.DedupStats, error)
	GetOpenKnownIssues(ctx context.Context, tenantID string) ([]models.KnownIssue, error)
	GetSuppressionStats(ctx context.Context, tenantID string) (*models.SuppressionStats, error)
	GetTopology(ctx context.Context, tenantID string) (*models.Topology, error)
	Ingest(ctx context.Context, tenantID string, req models.IngestRequest) (*models.IngestResponse, error)
	ListAlerts(ctx context.Context, tenantID string, severity, status string, limit int) (*models.AlertListResponse, error)
	SetTopology(ctx context.Context, tenantID string, req models.TopologyNodesRequest) (*models.TopologyUpdate, error)
	UpdateAlert(ctx context.Context, tenantID, id string, req UpdateAlertRequest) (*models.Alert, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
