// Code generated by platform-svc-go. DO NOT EDIT.
// source: internal/cmdb-drift/repository/repository.go

package repository

import (
	"context"

	"orion/platform-svc-go/internal/cmdb-drift/models"
)

// RepositoryInterface defines the data access methods for drift records.
type RepositoryInterface interface {
	CreateDrift(ctx context.Context, d *models.DriftRecord) error
	BatchCreateDrifts(ctx context.Context, drifts []models.DriftRecord) error
	GetDrift(ctx context.Context, tenantID, id string) (*models.DriftRecord, error)
	ListDrifts(ctx context.Context, tenantID string, filter models.DriftFilter) ([]models.DriftRecord, error)
	CountDrifts(ctx context.Context, tenantID string, filter models.DriftFilter) (int, error)
	UpdateDriftResolution(ctx context.Context, tenantID, id, resolvedBy, resolution string) error
	BulkUpdateDriftResolution(ctx context.Context, tenantID string, ids []string, resolvedBy, resolution string) (int64, error)
	MarkRemediated(ctx context.Context, tenantID, id string) error
	CountUnresolvedDrifts(ctx context.Context, tenantID string) (int, error)
	GetDriftStats(ctx context.Context, tenantID string) (*models.DriftStats, error)
	DeleteDrift(ctx context.Context, tenantID, id string) (bool, error)
}

// Compile-time check: *Repository implements RepositoryInterface
var _ RepositoryInterface = (*Repository)(nil)