// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for digital-twin.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the digital-twin service.
type ServiceInterface interface {
	CancelReplay(ctx context.Context, replayID string) (*ReplaySessionSummary, error)
	CreateSandbox(ctx context.Context, tenantID string, req models.CreateSandboxRequest) (*models.Sandbox, error)
	CreateSnapshot(ctx context.Context, twinID, name string) (*models.Snapshot, error)
	CreateTwin(ctx context.Context, tenantID string, req models.CreateDigitalTwinRequest) (*models.DigitalTwin, error)
	DestroySandbox(id string) (*models.Sandbox, error)
	FindTwin(ctx context.Context, tenantID, id string) (*models.DigitalTwin, error)
	GetRecordingDetail(recordingID string) *RecordingDetail
	GetRecordingRecords(recordingID string) []any
	GetReplayReport(ctx context.Context, replayID string) (*ReplayReport, error)
	GetReplayStatus(ctx context.Context, replayID string) (*ReplayStatusDetail, error)
	GetTwinState(ctx context.Context, tenantID, twinID string) (*TwinState, error)
	ListRecordingSessions(ctx context.Context, twinID string) ([]RecordingSessionSummary, error)
	ListReplaySessions(ctx context.Context, twinID string) ([]ReplaySessionSummary, error)
	ListSandboxes(ctx context.Context) []models.Sandbox
	ListTwins(ctx context.Context, tenantID string) ([]models.DigitalTwin, error)
	PauseRecording(recordingID string) *RecordingResult
	RecordTraffic(ctx context.Context, twinID string) (*models.TrafficRecord, error)
	ReplayTraffic(ctx context.Context, twinID string) (*ReplayTrafficResult, error)
	SandboxHealth(id string) (*models.Sandbox, error)
	StartRecording(twinID, name string) *models.RecordingSession
	StartReplay(ctx context.Context, twinID string, req models.CreateReplayStartRequest) (*models.ReplaySession, error)
	StopRecording(recordingID string) *RecordingResult
	StopSandbox(id string) (*models.Sandbox, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
