// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for script-version.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the script-version service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateScriptVersionRequest) (*models.ScriptVersion, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.ScriptVersion, error)
	List(ctx context.Context, tenantID string) ([]models.ScriptVersion, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateScriptVersionRequest) (*models.ScriptVersion, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
