// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for cron.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the cron service.
type ServiceInterface interface {
	AddJob(ctx context.Context, tenantID string, req models.CreateCronJobRequest) (*models.CronJob, error)
	Create(ctx context.Context, tenantID string, req models.CreateCronJobRequest) (*models.CronJob, error)
	Delete(ctx context.Context, tenantID, id string) error
	DisableJob(ctx context.Context, tenantID, id string) error
	EnableJob(ctx context.Context, tenantID, id string) error
	ExecuteJob(ctx context.Context, tenantID, id string) (*models.CronJobExecution, error)
	Get(ctx context.Context, tenantID, id string) (*models.CronJob, error)
	GetExecutionByID(ctx context.Context, tenantID, executionID string) (*models.CronJobExecution, error)
	GetExecutionHistory(ctx context.Context, tenantID, jobID string) ([]models.CronJobExecution, error)
	GetJob(ctx context.Context, tenantID, id string) (*models.CronJob, error)
	GetJobs(ctx context.Context, tenantID string) ([]models.CronJob, error)
	GetRunningJobs([]models.CronJob)
	GetStatus(ctx context.Context, tenantID string) (map[string]any, error)
	List(ctx context.Context, tenantID string, limit, offset int) ([]models.CronJob, error)
	RemoveJob(ctx context.Context, tenantID, id string) error
	Start
	Stop
	Update(ctx context.Context, tenantID, id string, req models.UpdateCronJobRequest) (*models.CronJob, error)
	UpdatePartial(ctx context.Context, tenantID, id string, updates map[string]any) (*models.CronJob, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
