// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/report-designer/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	CreateReport(ctx context.Context, report *models.ReportDefinition) error
	GetReportByID(ctx context.Context, id string, tenantID string) (*models.ReportDefinition, error)
	UpdateReport(ctx context.Context, id string, tenantID string, updates map[string]interface{}) (*models.ReportDefinition, error)
	DeleteReport(ctx context.Context, id string, tenantID string) (bool, error)
	ListReports(ctx context.Context, req *models.ListReportsRequest, tenantID string) ([]models.ReportDefinition, int, error)
	CreateDatasource(ctx context.Context, ds *models.ReportDatasource) error
	GetDatasourceByID(ctx context.Context, id string, tenantID string) (*models.ReportDatasource, error)
	UpdateDatasource(ctx context.Context, id string, tenantID string, updates map[string]interface{}) (*models.ReportDatasource, error)
	DeleteDatasource(ctx context.Context, id string, tenantID string) (bool, error)
	ListDatasources(ctx context.Context, tenantID string) ([]models.ReportDatasource, error)
	CreateSchedule(ctx context.Context, s *models.ReportSchedule) error
	GetScheduleByID(ctx context.Context, id string, tenantID string) (*models.ReportSchedule, error)
	UpdateSchedule(ctx context.Context, id string, tenantID string, updates map[string]interface{}) (*models.ReportSchedule, error)
	DeleteSchedule(ctx context.Context, id string, tenantID string) (bool, error)
	ListSchedules(ctx context.Context, reportID string, tenantID string) ([]models.ReportSchedule, error)
	CreateExecution(ctx context.Context, e *models.ReportExecution) error
	UpdateExecutionStatus(ctx context.Context, id string, tenantID string, status string, outputPath *string, errorMessage *string) error
	ListExecutions(ctx context.Context, reportID string, tenantID string, limit int) ([]models.ReportExecution, error)
}
