// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateDatasource(ctx context.Context, ds *models.ReportDatasource) error
	CreateExecution(ctx context.Context, e *models.ReportExecution) error
	CreateReport(ctx context.Context, report *models.ReportDefinition) error
	CreateSchedule(ctx context.Context, s *models.ReportSchedule) error
	DeleteDatasource(ctx context.Context, id string, tenantID string) bool, error
	DeleteReport(ctx context.Context, id string, tenantID string) bool, error
	DeleteSchedule(ctx context.Context, id string, tenantID string) bool, error
	GetDatasourceByID(ctx context.Context, id string, tenantID string) *models.ReportDatasource, error
	GetReportByID(ctx context.Context, id string, tenantID string) *models.ReportDefinition, error
	GetScheduleByID(ctx context.Context, id string, tenantID string) *models.ReportSchedule, error
	ListDatasources(ctx context.Context, tenantID string) []models.ReportDatasource, error
	ListExecutions(ctx context.Context, reportID string, tenantID string, limit int) []models.ReportExecution, error
	ListReports(ctx context.Context, req *models.ListReportsRequest, tenantID string) []models.ReportDefinition, int, error
	ListSchedules(ctx context.Context, reportID string, tenantID string) []models.ReportSchedule, error
	UpdateDatasource(ctx context.Context, id string, tenantID string, updates map[string]interface{}) *models.ReportDatasource, error
	UpdateExecutionStatus(ctx context.Context, id string, tenantID string, status string, outputPath *string, errorMessage *string) error
	UpdateReport(ctx context.Context, id string, tenantID string, updates map[string]interface{}) *models.ReportDefinition, error
	UpdateSchedule(ctx context.Context, id string, tenantID string, updates map[string]interface{}) *models.ReportSchedule, error
}
