// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for env-lifecycle.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the env-lifecycle service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req *models.CreateEnvLifecycleRequest) (*models.EnvLifecycle, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.EnvLifecycle, error)
	List(ctx context.Context, tenantID string) ([]models.EnvLifecycle, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateEnvLifecycleRequest) (*models.EnvLifecycle, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
