// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CompleteDeployment(ctx context.Context, tenantID id status string) error
	Create(ctx context.Context, m *models.Deployment) error
	CreateAuditEntry(ctx context.Context, deploymentID action userID details string) error
	CreateReleaseNote(ctx context.Context, tenantID deploymentID content string) *models.ReleaseNote, error
	CreateRollback(ctx context.Context, tenantID deploymentID fromVersion toVersion reason string) *models.Rollback, error
	GetByID(ctx context.Context, tenantID id string) *models.Deployment, error
	GetReleaseNotes(ctx context.Context, deploymentID string) *models.ReleaseNote, error
	LatestByApp(ctx context.Context, tenantID appName environment string) *models.Deployment, error
	LinkGitCommit(ctx context.Context, deploymentID commitSHA branch string) error
	List(ctx context.Context, tenantID string, limit offset int) []models.Deployment, error
	ListAuditEntries(ctx context.Context, deploymentID string) []models.AuditEntry, error
	ListChangelog(ctx context.Context, deploymentID string) []models.GitChangelogEntry, error
	ListReleaseNotesByTenant(ctx context.Context, tenantID string) []models.ReleaseNote, error
	ListRollbacks(ctx context.Context, tenantID deploymentID string) []models.Rollback, error
	Metrics(ctx context.Context, tenantID string) *models.DeploymentMetrics, error
	UpdateStatus(ctx context.Context, tenantID id status string) error
}
