// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Claim(ctx context.Context, id string, tenantID string, assigneeID string, comment *string) error
	Complete(ctx context.Context, id string, tenantID string, comment *string, formData *string) error
	Count(ctx context.Context, tenantID string, filter *models.ListFilter) int, error
	Create(ctx context.Context, t *models.WorkflowTask) error
	GetByID(ctx context.Context, id string, tenantID string) *models.WorkflowTask, error
	List(ctx context.Context, tenantID string, filter *models.ListFilter) []models.WorkflowTask, error
	UpdateStatus(ctx context.Context, id string, tenantID string, status string) error
}
