// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for sso.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/sso/models"
)

// ServiceInterface defines the interface for the sso service.
type ServiceInterface interface {
	CreateProvider(ctx context.Context, tenantID string, provider *models.SSOProvider) (*models.SSOProvider, error)
	GetProvider(ctx context.Context, tenantID, id string) (*models.SSOProvider, error)
	HandleCallback(ctx context.Context, tenantID string, state string, userID string) (*models.SSOProvider, error)
	InitiateLogin(ctx context.Context, tenantID string, req *models.SSOLoginRequest) (*models.SSOSession, error)
	ListProviders(ctx context.Context, tenantID string, q models.ListProvidersQuery) ([]models.SSOProvider, int, error)
	UpdateProvider(ctx context.Context, tenantID, id string, updates map[string]any) error
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
