// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	BatchCreateCIs(ctx context.Context, items []models.BatchCreateItem, tenantID string, createdBy string) *models.BatchResult, error
	BatchDeleteCIs(ctx context.Context, ids []string, tenantID string) *models.BatchResult, error
	BatchQueryCIs(ctx context.Context, q *models.BatchQueryRequest, tenantID string) []models.CI, int, error
	BatchUpdateCIs(ctx context.Context, items []models.BatchUpdateItem, tenantID string) *models.BatchResult, error
	CreateCI(ctx context.Context, ci *models.CI) error
	CreateRelation(ctx context.Context, rel *models.CIRelation) error
	CreateVersion(ctx context.Context, ciID string, version int, snapshot *string, createdBy string, tenantID string) error
	DeleteCI(ctx context.Context, id string) bool, error
	DeleteRelation(ctx context.Context, relationID string, tenantID string) bool, error
	ExportCIByCiId(ctx context.Context, ciID string, tenantID string) *models.CI, error
	ExportCIs(ctx context.Context, ciType status environment search *string, tenantID string, includeArchived bool) []models.CI, error
	GetCIByCiId(ctx context.Context, ciID string, tenantID *string) *models.CI, error
	GetCIByID(ctx context.Context, id string) *models.CI, error
	GetCIRelations(ctx context.Context, ciID string) []models.CIRelation, error
	GetCIVersions(ctx context.Context, ciID string) []models.CIVersion, error
	GetCurrentVersion(ctx context.Context, ciID string) *models.CIVersion, error
	GetImpactAnalysis(ctx context.Context, tenantID string, ciID string) []models.CIRelation, error
	GetServiceDependencies(ctx context.Context, tenantID string, ciID string) []models.CIRelation, error
	GetTopologyEdges(ctx context.Context, tenantID string, limit int) []models.TopologyEdge, error
	GetTopologyNodes(ctx context.Context, ciType *string, tenantID string, limit int) []models.TopologyNode, error
	GetVersionSnapshot(ctx context.Context, ciID string, version int) *string, error
	ListCIs(ctx context.Context, ciType *string, status *string, tenantID string, page limit int) []models.CI, int, error
	UpdateCI(ctx context.Context, id string, updates map[string]interface{}) *models.CI, error
}
