// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CheckVulnerability(ctx context.Context, tenantID cveID string) *models.CheckVulnerabilityResult, error
	Create(ctx context.Context, tenantID string, req models.CreateRequest) *models.Record, error
	Delete(ctx context.Context, tenantID id string) error
	FindVulnerabilities(ctx context.Context, tenantID string, image string) *models.ScanVulnerabilitiesResult, error
	FixVulnerability(ctx context.Context, tenantID image string, cveIDs []string) *models.FixVulnerabilityResult, error
	GetByID(ctx context.Context, tenantID id string) *models.Record, error
	GetVulnerability(ctx context.Context, tenantID cveID string) *models.Vulnerability, error
	List(ctx context.Context, tenantID string) []models.Record, error
	ListVulnerabilities(ctx context.Context, tenantID string) []models.Vulnerability, error
	Update(ctx context.Context, tenantID id string, req models.CreateRequest) *models.Record, error
}
