// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateContract(ctx context.Context, req *models.CreateContractRequest, tenantID string) *models.Contract, error
	CreateRule(ctx context.Context, req *models.CreateRuleRequest, tenantID string) *models.Rule, error
	CreateVerification(ctx context.Context, req *models.VerifyRequest, contractID string, passed bool, violations []string, tenantID string) error
	CreateVersion(ctx context.Context, req *models.CreateVersionRequest, tenantID string) *models.Version, error
	GetContract(ctx context.Context, id string, tenantID string) *models.Contract, error
	GetGovernanceStats(ctx context.Context, tenantID string) models.GovernanceStats, error
	GetVerificationHistory(ctx context.Context, contractID string, tenantID string) []models.VerificationHistory, error
	GetVersion(ctx context.Context, id string, tenantID string) *models.Version, error
	ListContracts(ctx context.Context, tenantID string, apiName *string, status *string) []models.Contract, error
	ListDeprecatedVersions(ctx context.Context, tenantID string) []models.Version, error
	ListVersions(ctx context.Context, tenantID string, apiName *string, status *string) []models.Version, error
	ListViolations(ctx context.Context, tenantID string, contractID *string, severity *string) []models.Violation, error
	UpdateVersion(ctx context.Context, id string, tenantID string, updates map[string]interface{}) *models.Version, error
}
