// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: cmdb/v1/cmdb.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CMDBService_CreateCI_FullMethodName       = "/cmdb.v1.CMDBService/CreateCI"
	CMDBService_GetCI_FullMethodName          = "/cmdb.v1.CMDBService/GetCI"
	CMDBService_UpdateCI_FullMethodName       = "/cmdb.v1.CMDBService/UpdateCI"
	CMDBService_DeleteCI_FullMethodName       = "/cmdb.v1.CMDBService/DeleteCI"
	CMDBService_ListCIs_FullMethodName        = "/cmdb.v1.CMDBService/ListCIs"
	CMDBService_CreateRelation_FullMethodName = "/cmdb.v1.CMDBService/CreateRelation"
	CMDBService_DeleteRelation_FullMethodName = "/cmdb.v1.CMDBService/DeleteRelation"
	CMDBService_GetRelations_FullMethodName   = "/cmdb.v1.CMDBService/GetRelations"
	CMDBService_GetTopology_FullMethodName    = "/cmdb.v1.CMDBService/GetTopology"
	CMDBService_AnalyzeImpact_FullMethodName  = "/cmdb.v1.CMDBService/AnalyzeImpact"
	CMDBService_SyncHosts_FullMethodName      = "/cmdb.v1.CMDBService/SyncHosts"
)

// CMDBServiceClient is the client API for CMDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CMDBServiceClient interface {
	CreateCI(ctx context.Context, in *CreateCIRequest, opts ...grpc.CallOption) (*CreateCIResponse, error)
	GetCI(ctx context.Context, in *GetCIRequest, opts ...grpc.CallOption) (*CI, error)
	UpdateCI(ctx context.Context, in *UpdateCIRequest, opts ...grpc.CallOption) (*UpdateCIResponse, error)
	DeleteCI(ctx context.Context, in *DeleteCIRequest, opts ...grpc.CallOption) (*DeleteCIResponse, error)
	ListCIs(ctx context.Context, in *CIListRequest, opts ...grpc.CallOption) (*CIListResponse, error)
	CreateRelation(ctx context.Context, in *CreateRelationRequest, opts ...grpc.CallOption) (*CreateRelationResponse, error)
	DeleteRelation(ctx context.Context, in *DeleteRelationRequest, opts ...grpc.CallOption) (*DeleteRelationResponse, error)
	GetRelations(ctx context.Context, in *GetRelationsRequest, opts ...grpc.CallOption) (*GetRelationsResponse, error)
	GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error)
	AnalyzeImpact(ctx context.Context, in *AnalyzeImpactRequest, opts ...grpc.CallOption) (*AnalyzeImpactResponse, error)
	SyncHosts(ctx context.Context, in *SyncHostsRequest, opts ...grpc.CallOption) (*SyncHostsResponse, error)
}

type cMDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCMDBServiceClient(cc grpc.ClientConnInterface) CMDBServiceClient {
	return &cMDBServiceClient{cc}
}

func (c *cMDBServiceClient) CreateCI(ctx context.Context, in *CreateCIRequest, opts ...grpc.CallOption) (*CreateCIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCIResponse)
	err := c.cc.Invoke(ctx, CMDBService_CreateCI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) GetCI(ctx context.Context, in *GetCIRequest, opts ...grpc.CallOption) (*CI, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CI)
	err := c.cc.Invoke(ctx, CMDBService_GetCI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) UpdateCI(ctx context.Context, in *UpdateCIRequest, opts ...grpc.CallOption) (*UpdateCIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCIResponse)
	err := c.cc.Invoke(ctx, CMDBService_UpdateCI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) DeleteCI(ctx context.Context, in *DeleteCIRequest, opts ...grpc.CallOption) (*DeleteCIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCIResponse)
	err := c.cc.Invoke(ctx, CMDBService_DeleteCI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) ListCIs(ctx context.Context, in *CIListRequest, opts ...grpc.CallOption) (*CIListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CIListResponse)
	err := c.cc.Invoke(ctx, CMDBService_ListCIs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) CreateRelation(ctx context.Context, in *CreateRelationRequest, opts ...grpc.CallOption) (*CreateRelationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRelationResponse)
	err := c.cc.Invoke(ctx, CMDBService_CreateRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) DeleteRelation(ctx context.Context, in *DeleteRelationRequest, opts ...grpc.CallOption) (*DeleteRelationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRelationResponse)
	err := c.cc.Invoke(ctx, CMDBService_DeleteRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) GetRelations(ctx context.Context, in *GetRelationsRequest, opts ...grpc.CallOption) (*GetRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRelationsResponse)
	err := c.cc.Invoke(ctx, CMDBService_GetRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopologyResponse)
	err := c.cc.Invoke(ctx, CMDBService_GetTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) AnalyzeImpact(ctx context.Context, in *AnalyzeImpactRequest, opts ...grpc.CallOption) (*AnalyzeImpactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeImpactResponse)
	err := c.cc.Invoke(ctx, CMDBService_AnalyzeImpact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMDBServiceClient) SyncHosts(ctx context.Context, in *SyncHostsRequest, opts ...grpc.CallOption) (*SyncHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncHostsResponse)
	err := c.cc.Invoke(ctx, CMDBService_SyncHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CMDBServiceServer is the server API for CMDBService service.
// All implementations must embed UnimplementedCMDBServiceServer
// for forward compatibility.
type CMDBServiceServer interface {
	CreateCI(context.Context, *CreateCIRequest) (*CreateCIResponse, error)
	GetCI(context.Context, *GetCIRequest) (*CI, error)
	UpdateCI(context.Context, *UpdateCIRequest) (*UpdateCIResponse, error)
	DeleteCI(context.Context, *DeleteCIRequest) (*DeleteCIResponse, error)
	ListCIs(context.Context, *CIListRequest) (*CIListResponse, error)
	CreateRelation(context.Context, *CreateRelationRequest) (*CreateRelationResponse, error)
	DeleteRelation(context.Context, *DeleteRelationRequest) (*DeleteRelationResponse, error)
	GetRelations(context.Context, *GetRelationsRequest) (*GetRelationsResponse, error)
	GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error)
	AnalyzeImpact(context.Context, *AnalyzeImpactRequest) (*AnalyzeImpactResponse, error)
	SyncHosts(context.Context, *SyncHostsRequest) (*SyncHostsResponse, error)
	mustEmbedUnimplementedCMDBServiceServer()
}

// UnimplementedCMDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCMDBServiceServer struct{}

func (UnimplementedCMDBServiceServer) CreateCI(context.Context, *CreateCIRequest) (*CreateCIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCI not implemented")
}
func (UnimplementedCMDBServiceServer) GetCI(context.Context, *GetCIRequest) (*CI, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCI not implemented")
}
func (UnimplementedCMDBServiceServer) UpdateCI(context.Context, *UpdateCIRequest) (*UpdateCIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCI not implemented")
}
func (UnimplementedCMDBServiceServer) DeleteCI(context.Context, *DeleteCIRequest) (*DeleteCIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCI not implemented")
}
func (UnimplementedCMDBServiceServer) ListCIs(context.Context, *CIListRequest) (*CIListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCIs not implemented")
}
func (UnimplementedCMDBServiceServer) CreateRelation(context.Context, *CreateRelationRequest) (*CreateRelationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRelation not implemented")
}
func (UnimplementedCMDBServiceServer) DeleteRelation(context.Context, *DeleteRelationRequest) (*DeleteRelationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRelation not implemented")
}
func (UnimplementedCMDBServiceServer) GetRelations(context.Context, *GetRelationsRequest) (*GetRelationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelations not implemented")
}
func (UnimplementedCMDBServiceServer) GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopology not implemented")
}
func (UnimplementedCMDBServiceServer) AnalyzeImpact(context.Context, *AnalyzeImpactRequest) (*AnalyzeImpactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeImpact not implemented")
}
func (UnimplementedCMDBServiceServer) SyncHosts(context.Context, *SyncHostsRequest) (*SyncHostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncHosts not implemented")
}
func (UnimplementedCMDBServiceServer) mustEmbedUnimplementedCMDBServiceServer() {}
func (UnimplementedCMDBServiceServer) testEmbeddedByValue()                     {}

// UnsafeCMDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CMDBServiceServer will
// result in compilation errors.
type UnsafeCMDBServiceServer interface {
	mustEmbedUnimplementedCMDBServiceServer()
}

func RegisterCMDBServiceServer(s grpc.ServiceRegistrar, srv CMDBServiceServer) {
	// If the following call panics, it indicates UnimplementedCMDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CMDBService_ServiceDesc, srv)
}

func _CMDBService_CreateCI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).CreateCI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_CreateCI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).CreateCI(ctx, req.(*CreateCIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_GetCI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).GetCI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_GetCI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).GetCI(ctx, req.(*GetCIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_UpdateCI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).UpdateCI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_UpdateCI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).UpdateCI(ctx, req.(*UpdateCIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_DeleteCI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).DeleteCI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_DeleteCI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).DeleteCI(ctx, req.(*DeleteCIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_ListCIs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CIListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).ListCIs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_ListCIs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).ListCIs(ctx, req.(*CIListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_CreateRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).CreateRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_CreateRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).CreateRelation(ctx, req.(*CreateRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_DeleteRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).DeleteRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_DeleteRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).DeleteRelation(ctx, req.(*DeleteRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_GetRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).GetRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_GetRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).GetRelations(ctx, req.(*GetRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_GetTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).GetTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_GetTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).GetTopology(ctx, req.(*GetTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_AnalyzeImpact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeImpactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).AnalyzeImpact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_AnalyzeImpact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).AnalyzeImpact(ctx, req.(*AnalyzeImpactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMDBService_SyncHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMDBServiceServer).SyncHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMDBService_SyncHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMDBServiceServer).SyncHosts(ctx, req.(*SyncHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CMDBService_ServiceDesc is the grpc.ServiceDesc for CMDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CMDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cmdb.v1.CMDBService",
	HandlerType: (*CMDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCI",
			Handler:    _CMDBService_CreateCI_Handler,
		},
		{
			MethodName: "GetCI",
			Handler:    _CMDBService_GetCI_Handler,
		},
		{
			MethodName: "UpdateCI",
			Handler:    _CMDBService_UpdateCI_Handler,
		},
		{
			MethodName: "DeleteCI",
			Handler:    _CMDBService_DeleteCI_Handler,
		},
		{
			MethodName: "ListCIs",
			Handler:    _CMDBService_ListCIs_Handler,
		},
		{
			MethodName: "CreateRelation",
			Handler:    _CMDBService_CreateRelation_Handler,
		},
		{
			MethodName: "DeleteRelation",
			Handler:    _CMDBService_DeleteRelation_Handler,
		},
		{
			MethodName: "GetRelations",
			Handler:    _CMDBService_GetRelations_Handler,
		},
		{
			MethodName: "GetTopology",
			Handler:    _CMDBService_GetTopology_Handler,
		},
		{
			MethodName: "AnalyzeImpact",
			Handler:    _CMDBService_AnalyzeImpact_Handler,
		},
		{
			MethodName: "SyncHosts",
			Handler:    _CMDBService_SyncHosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmdb/v1/cmdb.proto",
}
