// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for global-param.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the global-param service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req *models.CreateGlobalParamRequest) (*models.GlobalParam, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.GlobalParam, error)
	List(ctx context.Context, tenantID string) ([]models.GlobalParam, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateGlobalParamRequest) (*models.GlobalParam, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
