// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: ops/v1/ops.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_ops_v1_ops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClosedAt      int64                  `protobuf:"varint,6,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_ops_v1_ops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Session) GetClosedAt() int64 {
	if x != nil {
		return x.ClosedAt
	}
	return 0
}

func (x *Session) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_ops_v1_ops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Task) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *Task) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_ops_v1_ops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *TaskResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *TaskResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CronJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Schedule      string                 `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastRunAt     int64                  `protobuf:"varint,8,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`
	NextRunAt     int64                  `protobuf:"varint,9,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	Enabled       bool                   `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronJob) Reset() {
	*x = CronJob{}
	mi := &file_ops_v1_ops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJob) ProtoMessage() {}

func (x *CronJob) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJob.ProtoReflect.Descriptor instead.
func (*CronJob) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{4}
}

func (x *CronJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CronJob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CronJob) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CronJob) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CronJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CronJob) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CronJob) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *CronJob) GetLastRunAt() int64 {
	if x != nil {
		return x.LastRunAt
	}
	return 0
}

func (x *CronJob) GetNextRunAt() int64 {
	if x != nil {
		return x.NextRunAt
	}
	return 0
}

func (x *CronJob) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type BatchCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Env            map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchCommand) Reset() {
	*x = BatchCommand{}
	mi := &file_ops_v1_ops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCommand) ProtoMessage() {}

func (x *BatchCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCommand.ProtoReflect.Descriptor instead.
func (*BatchCommand) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{5}
}

func (x *BatchCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *BatchCommand) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *BatchCommand) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ExecuteBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Commands      []*BatchCommand        `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBatchRequest) Reset() {
	*x = ExecuteBatchRequest{}
	mi := &file_ops_v1_ops_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchRequest) ProtoMessage() {}

func (x *ExecuteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBatchRequest) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteBatchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteBatchRequest) GetCommands() []*BatchCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type ExecuteBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBatchResponse) Reset() {
	*x = ExecuteBatchResponse{}
	mi := &file_ops_v1_ops_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchResponse) ProtoMessage() {}

func (x *ExecuteBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchResponse.ProtoReflect.Descriptor instead.
func (*ExecuteBatchResponse) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteBatchResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_ops_v1_ops_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{8}
}

func (x *GetSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_ops_v1_ops_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_ops_v1_ops_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_ops_v1_ops_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{11}
}

func (x *CloseSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_ops_v1_ops_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{12}
}

func (x *CloseSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_ops_v1_ops_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{13}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultsRequest) Reset() {
	*x = GetTaskResultsRequest{}
	mi := &file_ops_v1_ops_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultsRequest) ProtoMessage() {}

func (x *GetTaskResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskResultsRequest) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{14}
}

func (x *GetTaskResultsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetTaskResultsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetTaskResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TaskResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultsResponse) Reset() {
	*x = GetTaskResultsResponse{}
	mi := &file_ops_v1_ops_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultsResponse) ProtoMessage() {}

func (x *GetTaskResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResultsResponse) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{15}
}

func (x *GetTaskResultsResponse) GetResults() []*TaskResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetTaskResultsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RemotePath    string                 `protobuf:"bytes,4,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_ops_v1_ops_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{16}
}

func (x *UploadFileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UploadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UploadFileRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RemotePath    string                 `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_ops_v1_ops_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{17}
}

func (x *UploadFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadFileResponse) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RemotePath    string                 `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_ops_v1_ops_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{18}
}

func (x *DownloadFileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DownloadFileRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_ops_v1_ops_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{19}
}

func (x *DownloadFileResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DownloadFileResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateCronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronJob       *CronJob               `protobuf:"bytes,1,opt,name=cron_job,json=cronJob,proto3" json:"cron_job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCronJobRequest) Reset() {
	*x = CreateCronJobRequest{}
	mi := &file_ops_v1_ops_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCronJobRequest) ProtoMessage() {}

func (x *CreateCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCronJobRequest.ProtoReflect.Descriptor instead.
func (*CreateCronJobRequest) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{20}
}

func (x *CreateCronJobRequest) GetCronJob() *CronJob {
	if x != nil {
		return x.CronJob
	}
	return nil
}

type CreateCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronJob       *CronJob               `protobuf:"bytes,1,opt,name=cron_job,json=cronJob,proto3" json:"cron_job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCronJobResponse) Reset() {
	*x = CreateCronJobResponse{}
	mi := &file_ops_v1_ops_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCronJobResponse) ProtoMessage() {}

func (x *CreateCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCronJobResponse.ProtoReflect.Descriptor instead.
func (*CreateCronJobResponse) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{21}
}

func (x *CreateCronJobResponse) GetCronJob() *CronJob {
	if x != nil {
		return x.CronJob
	}
	return nil
}

type UpdateCronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronJob       *CronJob               `protobuf:"bytes,1,opt,name=cron_job,json=cronJob,proto3" json:"cron_job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCronJobRequest) Reset() {
	*x = UpdateCronJobRequest{}
	mi := &file_ops_v1_ops_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCronJobRequest) ProtoMessage() {}

func (x *UpdateCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCronJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateCronJobRequest) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateCronJobRequest) GetCronJob() *CronJob {
	if x != nil {
		return x.CronJob
	}
	return nil
}

type UpdateCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronJob       *CronJob               `protobuf:"bytes,1,opt,name=cron_job,json=cronJob,proto3" json:"cron_job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCronJobResponse) Reset() {
	*x = UpdateCronJobResponse{}
	mi := &file_ops_v1_ops_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCronJobResponse) ProtoMessage() {}

func (x *UpdateCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCronJobResponse.ProtoReflect.Descriptor instead.
func (*UpdateCronJobResponse) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateCronJobResponse) GetCronJob() *CronJob {
	if x != nil {
		return x.CronJob
	}
	return nil
}

type DeleteCronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCronJobRequest) Reset() {
	*x = DeleteCronJobRequest{}
	mi := &file_ops_v1_ops_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCronJobRequest) ProtoMessage() {}

func (x *DeleteCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCronJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteCronJobRequest) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteCronJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCronJobResponse) Reset() {
	*x = DeleteCronJobResponse{}
	mi := &file_ops_v1_ops_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCronJobResponse) ProtoMessage() {}

func (x *DeleteCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCronJobResponse.ProtoReflect.Descriptor instead.
func (*DeleteCronJobResponse) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteCronJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListCronJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronJobsRequest) Reset() {
	*x = ListCronJobsRequest{}
	mi := &file_ops_v1_ops_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronJobsRequest) ProtoMessage() {}

func (x *ListCronJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronJobsRequest.ProtoReflect.Descriptor instead.
func (*ListCronJobsRequest) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{26}
}

func (x *ListCronJobsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListCronJobsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListCronJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronJobs      []*CronJob             `protobuf:"bytes,1,rep,name=cron_jobs,json=cronJobs,proto3" json:"cron_jobs,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronJobsResponse) Reset() {
	*x = ListCronJobsResponse{}
	mi := &file_ops_v1_ops_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronJobsResponse) ProtoMessage() {}

func (x *ListCronJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_v1_ops_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronJobsResponse.ProtoReflect.Descriptor instead.
func (*ListCronJobsResponse) Descriptor() ([]byte, []int) {
	return file_ops_v1_ops_proto_rawDescGZIP(), []int{27}
}

func (x *ListCronJobsResponse) GetCronJobs() []*CronJob {
	if x != nil {
		return x.CronJobs
	}
	return nil
}

func (x *ListCronJobsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_ops_v1_ops_proto protoreflect.FileDescriptor

const file_ops_v1_ops_proto_rawDesc = "" +
	"\n" +
	"\x10ops/v1/ops.proto\x12\x06ops.v1\"S\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\x92\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tclosed_at\x18\x06 \x01(\x03R\bclosedAt\x129\n" +
	"\bmetadata\x18\a \x03(\v2\x1d.ops.v1.Session.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\a \x01(\x03R\n" +
	"finishedAt\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"\xed\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12<\n" +
	"\bmetadata\x18\x05 \x03(\v2 .ops.v1.TaskResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x02\n" +
	"\aCronJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x1e\n" +
	"\vlast_run_at\x18\b \x01(\x03R\tlastRunAt\x12\x1e\n" +
	"\vnext_run_at\x18\t \x01(\x03R\tnextRunAt\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\"\xba\x01\n" +
	"\fBatchCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x12/\n" +
	"\x03env\x18\x03 \x03(\v2\x1d.ops.v1.BatchCommand.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x13ExecuteBatchRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\bcommands\x18\x02 \x03(\v2\x14.ops.v1.BatchCommandR\bcommands\":\n" +
	"\x14ExecuteBatchResponse\x12\"\n" +
	"\x05tasks\x18\x01 \x03(\v2\f.ops.v1.TaskR\x05tasks\"#\n" +
	"\x11GetSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaf\x01\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\bmetadata\x18\x02 \x03(\v2*.ops.v1.CreateSessionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x15CreateSessionResponse\x12)\n" +
	"\asession\x18\x01 \x01(\v2\x0f.ops.v1.SessionR\asession\"%\n" +
	"\x13CloseSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14CloseSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"j\n" +
	"\x15GetTaskResultsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.ops.v1.PaginationR\n" +
	"pagination\"z\n" +
	"\x16GetTaskResultsResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.ops.v1.TaskResultR\aresults\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.ops.v1.PaginationR\n" +
	"pagination\"\x89\x01\n" +
	"\x11UploadFileRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vremote_path\x18\x04 \x01(\tR\n" +
	"remotePath\"O\n" +
	"\x12UploadFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vremote_path\x18\x02 \x01(\tR\n" +
	"remotePath\"U\n" +
	"\x13DownloadFileRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vremote_path\x18\x02 \x01(\tR\n" +
	"remotePath\"L\n" +
	"\x14DownloadFileResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"B\n" +
	"\x14CreateCronJobRequest\x12*\n" +
	"\bcron_job\x18\x01 \x01(\v2\x0f.ops.v1.CronJobR\acronJob\"C\n" +
	"\x15CreateCronJobResponse\x12*\n" +
	"\bcron_job\x18\x01 \x01(\v2\x0f.ops.v1.CronJobR\acronJob\"B\n" +
	"\x14UpdateCronJobRequest\x12*\n" +
	"\bcron_job\x18\x01 \x01(\v2\x0f.ops.v1.CronJobR\acronJob\"C\n" +
	"\x15UpdateCronJobResponse\x12*\n" +
	"\bcron_job\x18\x01 \x01(\v2\x0f.ops.v1.CronJobR\acronJob\"&\n" +
	"\x14DeleteCronJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteCronJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x13ListCronJobsRequest\x122\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x12.ops.v1.PaginationR\n" +
	"pagination\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"x\n" +
	"\x14ListCronJobsResponse\x12,\n" +
	"\tcron_jobs\x18\x01 \x03(\v2\x0f.ops.v1.CronJobR\bcronJobs\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.ops.v1.PaginationR\n" +
	"pagination2\xf1\x06\n" +
	"\n" +
	"OpsService\x12L\n" +
	"\rCreateSession\x12\x1c.ops.v1.CreateSessionRequest\x1a\x1d.ops.v1.CreateSessionResponse\x128\n" +
	"\n" +
	"GetSession\x12\x19.ops.v1.GetSessionRequest\x1a\x0f.ops.v1.Session\x12I\n" +
	"\fCloseSession\x12\x1b.ops.v1.CloseSessionRequest\x1a\x1c.ops.v1.CloseSessionResponse\x12I\n" +
	"\fExecuteBatch\x12\x1b.ops.v1.ExecuteBatchRequest\x1a\x1c.ops.v1.ExecuteBatchResponse\x12/\n" +
	"\aGetTask\x12\x16.ops.v1.GetTaskRequest\x1a\f.ops.v1.Task\x12O\n" +
	"\x0eGetTaskResults\x12\x1d.ops.v1.GetTaskResultsRequest\x1a\x1e.ops.v1.GetTaskResultsResponse\x12C\n" +
	"\n" +
	"UploadFile\x12\x19.ops.v1.UploadFileRequest\x1a\x1a.ops.v1.UploadFileResponse\x12I\n" +
	"\fDownloadFile\x12\x1b.ops.v1.DownloadFileRequest\x1a\x1c.ops.v1.DownloadFileResponse\x12L\n" +
	"\rCreateCronJob\x12\x1c.ops.v1.CreateCronJobRequest\x1a\x1d.ops.v1.CreateCronJobResponse\x12L\n" +
	"\rUpdateCronJob\x12\x1c.ops.v1.UpdateCronJobRequest\x1a\x1d.ops.v1.UpdateCronJobResponse\x12L\n" +
	"\rDeleteCronJob\x12\x1c.ops.v1.DeleteCronJobRequest\x1a\x1d.ops.v1.DeleteCronJobResponse\x12I\n" +
	"\fListCronJobs\x12\x1b.ops.v1.ListCronJobsRequest\x1a\x1c.ops.v1.ListCronJobsResponseB.Z,github.com/orion-platform/orion-proto/ops/v1b\x06proto3"

var (
	file_ops_v1_ops_proto_rawDescOnce sync.Once
	file_ops_v1_ops_proto_rawDescData []byte
)

func file_ops_v1_ops_proto_rawDescGZIP() []byte {
	file_ops_v1_ops_proto_rawDescOnce.Do(func() {
		file_ops_v1_ops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ops_v1_ops_proto_rawDesc), len(file_ops_v1_ops_proto_rawDesc)))
	})
	return file_ops_v1_ops_proto_rawDescData
}

var file_ops_v1_ops_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_ops_v1_ops_proto_goTypes = []any{
	(*Pagination)(nil),             // 0: ops.v1.Pagination
	(*Session)(nil),                // 1: ops.v1.Session
	(*Task)(nil),                   // 2: ops.v1.Task
	(*TaskResult)(nil),             // 3: ops.v1.TaskResult
	(*CronJob)(nil),                // 4: ops.v1.CronJob
	(*BatchCommand)(nil),           // 5: ops.v1.BatchCommand
	(*ExecuteBatchRequest)(nil),    // 6: ops.v1.ExecuteBatchRequest
	(*ExecuteBatchResponse)(nil),   // 7: ops.v1.ExecuteBatchResponse
	(*GetSessionRequest)(nil),      // 8: ops.v1.GetSessionRequest
	(*CreateSessionRequest)(nil),   // 9: ops.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 10: ops.v1.CreateSessionResponse
	(*CloseSessionRequest)(nil),    // 11: ops.v1.CloseSessionRequest
	(*CloseSessionResponse)(nil),   // 12: ops.v1.CloseSessionResponse
	(*GetTaskRequest)(nil),         // 13: ops.v1.GetTaskRequest
	(*GetTaskResultsRequest)(nil),  // 14: ops.v1.GetTaskResultsRequest
	(*GetTaskResultsResponse)(nil), // 15: ops.v1.GetTaskResultsResponse
	(*UploadFileRequest)(nil),      // 16: ops.v1.UploadFileRequest
	(*UploadFileResponse)(nil),     // 17: ops.v1.UploadFileResponse
	(*DownloadFileRequest)(nil),    // 18: ops.v1.DownloadFileRequest
	(*DownloadFileResponse)(nil),   // 19: ops.v1.DownloadFileResponse
	(*CreateCronJobRequest)(nil),   // 20: ops.v1.CreateCronJobRequest
	(*CreateCronJobResponse)(nil),  // 21: ops.v1.CreateCronJobResponse
	(*UpdateCronJobRequest)(nil),   // 22: ops.v1.UpdateCronJobRequest
	(*UpdateCronJobResponse)(nil),  // 23: ops.v1.UpdateCronJobResponse
	(*DeleteCronJobRequest)(nil),   // 24: ops.v1.DeleteCronJobRequest
	(*DeleteCronJobResponse)(nil),  // 25: ops.v1.DeleteCronJobResponse
	(*ListCronJobsRequest)(nil),    // 26: ops.v1.ListCronJobsRequest
	(*ListCronJobsResponse)(nil),   // 27: ops.v1.ListCronJobsResponse
	nil,                            // 28: ops.v1.Session.MetadataEntry
	nil,                            // 29: ops.v1.TaskResult.MetadataEntry
	nil,                            // 30: ops.v1.BatchCommand.EnvEntry
	nil,                            // 31: ops.v1.CreateSessionRequest.MetadataEntry
}
var file_ops_v1_ops_proto_depIdxs = []int32{
	28, // 0: ops.v1.Session.metadata:type_name -> ops.v1.Session.MetadataEntry
	29, // 1: ops.v1.TaskResult.metadata:type_name -> ops.v1.TaskResult.MetadataEntry
	30, // 2: ops.v1.BatchCommand.env:type_name -> ops.v1.BatchCommand.EnvEntry
	5,  // 3: ops.v1.ExecuteBatchRequest.commands:type_name -> ops.v1.BatchCommand
	2,  // 4: ops.v1.ExecuteBatchResponse.tasks:type_name -> ops.v1.Task
	31, // 5: ops.v1.CreateSessionRequest.metadata:type_name -> ops.v1.CreateSessionRequest.MetadataEntry
	1,  // 6: ops.v1.CreateSessionResponse.session:type_name -> ops.v1.Session
	0,  // 7: ops.v1.GetTaskResultsRequest.pagination:type_name -> ops.v1.Pagination
	3,  // 8: ops.v1.GetTaskResultsResponse.results:type_name -> ops.v1.TaskResult
	0,  // 9: ops.v1.GetTaskResultsResponse.pagination:type_name -> ops.v1.Pagination
	4,  // 10: ops.v1.CreateCronJobRequest.cron_job:type_name -> ops.v1.CronJob
	4,  // 11: ops.v1.CreateCronJobResponse.cron_job:type_name -> ops.v1.CronJob
	4,  // 12: ops.v1.UpdateCronJobRequest.cron_job:type_name -> ops.v1.CronJob
	4,  // 13: ops.v1.UpdateCronJobResponse.cron_job:type_name -> ops.v1.CronJob
	0,  // 14: ops.v1.ListCronJobsRequest.pagination:type_name -> ops.v1.Pagination
	4,  // 15: ops.v1.ListCronJobsResponse.cron_jobs:type_name -> ops.v1.CronJob
	0,  // 16: ops.v1.ListCronJobsResponse.pagination:type_name -> ops.v1.Pagination
	9,  // 17: ops.v1.OpsService.CreateSession:input_type -> ops.v1.CreateSessionRequest
	8,  // 18: ops.v1.OpsService.GetSession:input_type -> ops.v1.GetSessionRequest
	11, // 19: ops.v1.OpsService.CloseSession:input_type -> ops.v1.CloseSessionRequest
	6,  // 20: ops.v1.OpsService.ExecuteBatch:input_type -> ops.v1.ExecuteBatchRequest
	13, // 21: ops.v1.OpsService.GetTask:input_type -> ops.v1.GetTaskRequest
	14, // 22: ops.v1.OpsService.GetTaskResults:input_type -> ops.v1.GetTaskResultsRequest
	16, // 23: ops.v1.OpsService.UploadFile:input_type -> ops.v1.UploadFileRequest
	18, // 24: ops.v1.OpsService.DownloadFile:input_type -> ops.v1.DownloadFileRequest
	20, // 25: ops.v1.OpsService.CreateCronJob:input_type -> ops.v1.CreateCronJobRequest
	22, // 26: ops.v1.OpsService.UpdateCronJob:input_type -> ops.v1.UpdateCronJobRequest
	24, // 27: ops.v1.OpsService.DeleteCronJob:input_type -> ops.v1.DeleteCronJobRequest
	26, // 28: ops.v1.OpsService.ListCronJobs:input_type -> ops.v1.ListCronJobsRequest
	10, // 29: ops.v1.OpsService.CreateSession:output_type -> ops.v1.CreateSessionResponse
	1,  // 30: ops.v1.OpsService.GetSession:output_type -> ops.v1.Session
	12, // 31: ops.v1.OpsService.CloseSession:output_type -> ops.v1.CloseSessionResponse
	7,  // 32: ops.v1.OpsService.ExecuteBatch:output_type -> ops.v1.ExecuteBatchResponse
	2,  // 33: ops.v1.OpsService.GetTask:output_type -> ops.v1.Task
	15, // 34: ops.v1.OpsService.GetTaskResults:output_type -> ops.v1.GetTaskResultsResponse
	17, // 35: ops.v1.OpsService.UploadFile:output_type -> ops.v1.UploadFileResponse
	19, // 36: ops.v1.OpsService.DownloadFile:output_type -> ops.v1.DownloadFileResponse
	21, // 37: ops.v1.OpsService.CreateCronJob:output_type -> ops.v1.CreateCronJobResponse
	23, // 38: ops.v1.OpsService.UpdateCronJob:output_type -> ops.v1.UpdateCronJobResponse
	25, // 39: ops.v1.OpsService.DeleteCronJob:output_type -> ops.v1.DeleteCronJobResponse
	27, // 40: ops.v1.OpsService.ListCronJobs:output_type -> ops.v1.ListCronJobsResponse
	29, // [29:41] is the sub-list for method output_type
	17, // [17:29] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_ops_v1_ops_proto_init() }
func file_ops_v1_ops_proto_init() {
	if File_ops_v1_ops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ops_v1_ops_proto_rawDesc), len(file_ops_v1_ops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ops_v1_ops_proto_goTypes,
		DependencyIndexes: file_ops_v1_ops_proto_depIdxs,
		MessageInfos:      file_ops_v1_ops_proto_msgTypes,
	}.Build()
	File_ops_v1_ops_proto = out.File
	file_ops_v1_ops_proto_goTypes = nil
	file_ops_v1_ops_proto_depIdxs = nil
}
