// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for eventbus.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/eventbus/models"
)

// ServiceInterface defines the interface for the eventbus service.
type ServiceInterface interface {
	Count(ctx context.Context, tenantID string) (int, error)
	List(ctx context.Context, tenantID string, filter *models.ListFilter, offset, limit int) ([]models.Event, error)
	Publish(ctx context.Context, tenantID string, userID string, req *models.PublishRequest) (*models.Event, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
