// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/sbom/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	CreateSBOM(ctx context.Context, sbom *models.SBOMDocument) error
	GetSBOM(ctx context.Context, id string, tenantID string) (*models.SBOMDocument, error)
	ListSBOMs(ctx context.Context, tenantID string, q *models.ListQuery) ([]models.SBOMDocument, int, error)
	UpdateSBOMStatus(ctx context.Context, id string, tenantID string, status string) (*models.SBOMDocument, error)
	UpdateSBOMCounts(ctx context.Context, id string, tenantID string, compCount, vulnCount, licCount int) error
	DeleteSBOM(ctx context.Context, id string, tenantID string) (bool, error)
	CreateComponent(ctx context.Context, comp *models.SBOMComponent) error
	ListComponents(ctx context.Context, sbomID string, tenantID string, offset, limit int) ([]models.SBOMComponent, int, error)
	CountComponentsBySBOM(ctx context.Context, sbomID string, tenantID string) (int, error)
	DistinctLicenses(ctx context.Context, sbomID string, tenantID string) ([]models.SBOMComponent, error)
	CountComponentsByLicense(ctx context.Context, sbomID string, tenantID string, licenseID string) (int, error)
	CreateVulnerability(ctx context.Context, vuln *models.Vulnerability) error
	ListVulnerabilities(ctx context.Context, sbomID string, tenantID string, severity *string, offset, limit int) ([]models.Vulnerability, int, error)
	CreateAttestation(ctx context.Context, att *models.SBOMAttestation) error
	ListAttestations(ctx context.Context, sbomID string, tenantID string) ([]models.SBOMAttestation, error)
}
