// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CountComponentsByLicense(ctx context.Context, sbomID string, tenantID string, licenseID string) int, error
	CountComponentsBySBOM(ctx context.Context, sbomID string, tenantID string) int, error
	CreateAttestation(ctx context.Context, att *models.SBOMAttestation) error
	CreateComponent(ctx context.Context, comp *models.SBOMComponent) error
	CreateSBOM(ctx context.Context, sbom *models.SBOMDocument) error
	CreateVulnerability(ctx context.Context, vuln *models.Vulnerability) error
	DeleteSBOM(ctx context.Context, id string, tenantID string) bool, error
	DistinctLicenses(ctx context.Context, sbomID string, tenantID string) []models.SBOMComponent, error
	GetSBOM(ctx context.Context, id string, tenantID string) *models.SBOMDocument, error
	ListAttestations(ctx context.Context, sbomID string, tenantID string) []models.SBOMAttestation, error
	ListComponents(ctx context.Context, sbomID string, tenantID string, offset limit int) []models.SBOMComponent, int, error
	ListSBOMs(ctx context.Context, tenantID string, q *models.ListQuery) []models.SBOMDocument, int, error
	ListVulnerabilities(ctx context.Context, sbomID string, tenantID string, severity *string, offset limit int) []models.Vulnerability, int, error
	UpdateSBOMCounts(ctx context.Context, id string, tenantID string, compCount vulnCount licCount int) error
	UpdateSBOMStatus(ctx context.Context, id string, tenantID string, status string) *models.SBOMDocument, error
}
