// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CountFlows(ctx context.Context, tenantID string, filter *models.ListFlowFilters) int, error
	CreateFlow(ctx context.Context, flow *models.LowcodeFlow) error
	CreateInstance(ctx context.Context, inst *models.LowcodeInstance) error
	CreateTemplate(ctx context.Context, tmpl *models.LowcodeTemplate) error
	CreateVersionSnapshot(ctx context.Context, snap *models.VersionSnapshot) error
	DeleteFlow(ctx context.Context, tenantID id string) error
	GetFlowByID(ctx context.Context, tenantID id string) *models.LowcodeFlow, error
	GetInstanceByID(ctx context.Context, tenantID id string) *models.LowcodeInstance, error
	GetTemplateByID(ctx context.Context, id string) *models.LowcodeTemplate, error
	IncrementTemplateUsage(ctx context.Context, id string) error
	ListFlows(ctx context.Context, tenantID string, filter *models.ListFlowFilters, offset limit int) []models.LowcodeFlow, error
	ListTemplates(ctx context.Context) []models.LowcodeTemplate, error
	ListVersionSnapshots(ctx context.Context, workflowID string) []models.VersionSnapshot, error
	UpdateFlow(ctx context.Context, tenantID id string, updates map[string]interface{}) error
}
