// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, tenantID string, req models.CreateRequest) *models.Record, error
	Delete(ctx context.Context, tenantID id string) error
	GetByID(ctx context.Context, tenantID id string) *models.Record, error
	List(ctx context.Context, tenantID string) []models.Record, error
	Update(ctx context.Context, tenantID id string, req models.CreateRequest) *models.Record, error
	UpdateStatus(ctx context.Context, tenantID id status string) *models.Record, error
}
