// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for ai-security.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/ai/security/models"
)

// ServiceInterface defines the interface for the ai-security service.
type ServiceInterface interface {
	BlockAccess(ctx context.Context, tenantID, target string) (*models.BlockRecord, error)
	CheckVulnerability(ctx context.Context, tenantID, cveID string) (*models.CheckVulnerabilityResult, error)
	Create(ctx context.Context, tenantID string, req models.CreateRequest) (*models.Record, error)
	Delete(ctx context.Context, tenantID, id string) error
	FixVulnerability(ctx context.Context, tenantID, image string, cveIDs []string) (*models.FixVulnerabilityResult, error)
	Get(ctx context.Context, tenantID, id string) (*models.Record, error)
	GetAuditLog(ctx context.Context, tenantID string) ([]models.AuditLog, error)
	GetRiskScore(ctx context.Context, tenantID, id string) (*models.RiskScoreResult, error)
	GetVulnerability(ctx context.Context, tenantID, cveID string) (*models.Vulnerability, error)
	List(ctx context.Context, tenantID string) ([]models.Record, error)
	ListPolicies(ctx context.Context, tenantID string) ([]models.SecurityPolicy, error)
	ListVulnerabilities(ctx context.Context, tenantID string) ([]models.Vulnerability, error)
	ScanVulnerabilities(ctx context.Context, tenantID string, image string) (*models.ScanVulnerabilitiesResult, error)
	Update(ctx context.Context, tenantID, id string, req models.CreateRequest) (*models.Record, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
