// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateConnector(ctx context.Context, m *models.Connector) error
	CreateNetworkPolicy(ctx context.Context, tenantID string, m *models.SandboxNetworkPolicy) error
	CreateSandbox(ctx context.Context, tenantID string, m *models.SandboxInfo) error
	DeleteConnector(ctx context.Context, tenantID id string) error
	GetConnector(ctx context.Context, tenantID id string) *models.Connector, error
	GetHealthMetrics(ctx context.Context, tenantID connectorID string) *models.HealthMetrics, error
	GetNetworkPolicy(ctx context.Context, tenantID id string) *models.SandboxNetworkPolicy, error
	GetNetworkPolicyBySandbox(ctx context.Context, tenantID sandboxID string) *models.SandboxNetworkPolicy, error
	GetSandbox(ctx context.Context, tenantID id string) *models.SandboxInfo, error
	ListAllHealthMetrics(ctx context.Context, tenantID string) []models.HealthMetrics, error
	ListConnectors(ctx context.Context, tenantID string, limit offset int) []models.Connector, error
	ListNetworkPolicies(ctx context.Context, tenantID string) []models.SandboxNetworkPolicy, error
	ListSandboxes(ctx context.Context, tenantID string, limit offset int) []models.SandboxInfo, error
	UpdateConnector(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpdateConnectorStatus(ctx context.Context, tenantID id string, status models.ConnectorStatus) error
	UpdateNetworkPolicy(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpdateSandboxStatus(ctx context.Context, tenantID id string, status string) error
	UpsertHealthMetrics(ctx context.Context, tenantID string, metrics models.HealthMetrics) error
}
