// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for role.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/role/models"
)

// ServiceInterface defines the interface for the role service.
type ServiceInterface interface {
	Count(ctx context.Context, tenantID string) (int, error)
	Create(ctx context.Context, tenantID, createdBy string, req *models.CreateRoleRequest) (*models.Role, error)
	Delete(ctx context.Context, tenantID, id string) error
	GetByID(ctx context.Context, tenantID, id string) (*models.Role, error)
	GetPermissions(ctx context.Context, tenantID, id string) (*models.Role, error)
	List(ctx context.Context, tenantID string, filter *models.ListFilter, offset, limit int) ([]models.Role, error)
	SetPermissions(ctx context.Context, tenantID, id string, req *models.SetPermissionsRequest) (*models.Role, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateRoleRequest) (*models.Role, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
