// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for tracing.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the tracing service.
type ServiceInterface interface {
	CreateOtelConfig(ctx context.Context, tenantID string, req *models.CreateOtelRequest) (*models.OtelCollectorConfig, error)
	DeleteOtelConfig(ctx context.Context, tenantID, id string) error
	GetOtelConfig(ctx context.Context, tenantID, id string) (*models.OtelCollectorConfig, error)
	GetOtelConfigs(ctx context.Context, tenantID, configType string) ([]models.OtelCollectorConfig, error)
	GetSamplingConfigs(ctx context.Context, tenantID string) ([]models.TraceSamplingConfig, error)
	GetTrace(ctx context.Context, tenantID, traceID string) ([]models.TraceSpan, error)
	GetTraceList(ctx context.Context, tenantID string, serviceName string, limit int) ([]models.TraceSpan, error)
	SearchTraces(ctx context.Context, tenantID string, req *models.TraceSearchRequest) ([]models.TraceSpan, error)
	UpdateOtelConfig(ctx context.Context, tenantID, id string, req *models.UpdateOtelRequest) (*models.OtelCollectorConfig, error)
	UpsertSamplingConfig(ctx context.Context, tenantID string, req *models.UpsertSamplingRequest) (*models.TraceSamplingConfig, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
