// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for observability.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the observability service.
type ServiceInterface interface {
	CreateAlertRule(ctx context.Context, tenantID string, rule *models.AlertRule) (*models.AlertRule, error)
	GetMetric(ctx context.Context, tenantID, name string) (*models.Metric, error)
	ListAlertRules(ctx context.Context, tenantID string) ([]models.AlertRule, error)
	ListMetrics(ctx context.Context, tenantID string, q models.MetricQuery) ([]models.Metric, error)
	RecordMetric(ctx context.Context, tenantID string, m *models.Metric) (*models.Metric, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
