// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for chaos-enhanced.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the chaos-enhanced service.
type ServiceInterface interface {
	AvailableFaultTypes([]string)
	CreateExperiment(ctx context.Context, req *models.CreateExperimentRequest, tenantID string) (*models.Experiment, error)
	FaultConfigTemplate(faultType string) map[string]any
	GetExperiment(ctx context.Context, id string, tenantID string) (*models.Experiment, error)
	GetExperimentRecovery(ctx context.Context, id string, tenantID string) (*ExperimentRecovery, error)
	GetExperimentStatus(ctx context.Context, id string, tenantID string) (*ExperimentStatus, error)
	InjectFault(ctx context.Context, experimentID string, tenantID string, faultType string, faultConfig string) (*models.FaultInjection, error)
	ListExperiments(ctx context.Context, tenantID string, status *string, environmentID *string) ([]models.Experiment, int, error)
	StartExperiment(ctx context.Context, id string, tenantID string) (*models.Experiment, error)
	StopExperiment(ctx context.Context, id string, tenantID string) (*models.Experiment, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
