// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for multi-modal-trigger.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the multi-modal-trigger service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateMultiModalTriggerRequest) (*models.MultiModalTrigger, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.MultiModalTrigger, error)
	List(ctx context.Context, tenantID string) ([]models.MultiModalTrigger, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateMultiModalTriggerRequest) (*models.MultiModalTrigger, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
