// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for data-quality.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/data-quality/models"
)

// ServiceInterface defines the interface for the data-quality service.
type ServiceInterface interface {
	CreateAlert(ctx context.Context, tenantID string, req *models.CreateAlertRequest) (*models.Alert, error)
	CreateRule(ctx context.Context, tenantID string, req *models.CreateRuleRequest) (*models.Rule, error)
	CreateScanResult(ctx context.Context, tenantID string, req *models.CreateScanResultRequest) (*models.ScanResult, error)
	DeleteAlert(ctx context.Context, tenantID, id string) error
	DeleteRule(ctx context.Context, tenantID, id string) error
	GetAlert(ctx context.Context, tenantID, id string) (*models.Alert, error)
	GetRule(ctx context.Context, tenantID, id string) (*models.Rule, error)
	GetStats(ctx context.Context, tenantID string) (*models.QualityStats, error)
	ListAlerts(ctx context.Context, tenantID string, status *string) ([]models.Alert, error)
	ListRules(ctx context.Context, tenantID string, filter *models.RuleFilter) ([]models.Rule, error)
	ListScanResults(ctx context.Context, tenantID, ruleID string, status *string) ([]models.ScanResult, error)
	UpdateAlert(ctx context.Context, tenantID, id string, req *models.UpdateAlertRequest) (*models.Alert, error)
	UpdateRule(ctx context.Context, tenantID, id string, req *models.UpdateRuleRequest) (*models.Rule, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
