// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CountRunHistory(ctx context.Context, pipelineID string, tenantID string) int, error
	GetRunHistory(ctx context.Context, pipelineID string, tenantID string, period string, limit int) []models.RunHistoryEntry, error
}
