// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	AddDispatchRule(ctx context.Context, tenantID string, req models.AddDispatchRuleRequest) *models.DispatchRule, error
	AddRelation(ctx context.Context, tenantID ticketID relatedID relType string) *models.TicketRelation, error
	AddWorkflowHistory(ctx context.Context, tenantID ticketID action fromState toState userID comment string) error
	AssignTicket(ctx context.Context, tenantID id string, assigneeID string) error
	CountTickets(ctx context.Context, tenantID string) int, error
	CountTicketsByCategory(ctx context.Context, tenantID string) map[string]int, error
	CountTicketsByPriority(ctx context.Context, tenantID string) map[string]int, error
	CountTicketsByStatus(ctx context.Context, tenantID string) map[string]int, error
	CreateAssignment(ctx context.Context, tenantID ticketID assignee assignedBy reason string) error
	CreateAssignmentRule(ctx context.Context, tenantID string, req models.CreateAssignmentRuleRequest) *models.AssignmentRule, error
	CreateAutomationRule(ctx context.Context, tenantID string, req models.CreateAutomationRuleRequest) *models.AutomationRule, error
	CreateSLAPolicy(ctx context.Context, tenantID string, req models.CreateSLAPolicyRequest) *models.SLAPolicy, error
	CreateSLATarget(ctx context.Context, tenantID string, req models.CreateSLATargetRequest) *models.SLATarget, error
	CreateSuspend(ctx context.Context, tenantID string, req models.CreateSuspendRequest) *models.Suspend, error
	CreateTicket(ctx context.Context, t *models.Ticket) error
	DeleteAssignmentRule(ctx context.Context, tenantID string, id int) error
	DeleteAutomationRule(ctx context.Context, tenantID string, ruleID int) error
	DeleteSLAPolicy(ctx context.Context, tenantID string, policyID int) error
	DeleteTicket(ctx context.Context, tenantID id string) error
	DetectDuplicates(ctx context.Context, tenantID ticketID string) []models.TicketRelation, error
	FindRelatedTickets(ctx context.Context, tenantID ticketID string) []models.TicketRelation, error
	GetAssignmentsByTicket(ctx context.Context, tenantID ticketID string) []struct {
	ID		string		`db:"id"`
	TicketID	string		`db:"ticket_id"`
	Assignee	string		`db:"assignee"`
	AssignedBy	string		`db:"assigned_by"`
	Reason		string		`db:"reason"`
	CreatedAt	time.Time	`db:"created_at"`
}, error
	GetDispatchQueueEntries(ctx context.Context, tenantID string) []models.QueueEntry, error
	GetDispatchQueueStatus(ctx context.Context, tenantID string) *models.QueueStatus, error
	GetDispatchWeights(ctx context.Context, tenantID string) map[string]int, error
	GetEngineer(ctx context.Context, tenantID id string) *models.DispatchEngineer, error
	GetEngineerSuspendImpact(ctx context.Context, tenantID engineerID string) *models.EngineerSuspendImpact, error
	GetEngineerSuspensions(ctx context.Context, tenantID engineerID string) []models.Suspend, error
	GetRelations(ctx context.Context, tenantID ticketID string) []models.TicketRelation, error
	GetSLABreaches(ctx context.Context, tenantID string) []models.SLABreach, error
	GetSLACompliance(ctx context.Context, tenantID string, policyID int) *models.ComplianceResult, error
	GetSLAPolicy(ctx context.Context, tenantID string, policyID int) *models.SLAPolicy, error
	GetSLATarget(ctx context.Context, tenantID priority string) *models.SLATarget, error
	GetSLATracking(ctx context.Context, tenantID ticketID string) *TicketSLATracking, error
	GetSuspend(ctx context.Context, tenantID id string) *models.Suspend, error
	GetTicket(ctx context.Context, tenantID id string) *models.Ticket, error
	GetTicketSLAStatus(ctx context.Context, tenantID ticketID string) *models.TicketSLAStatus, error
	GetTransferHistory(ctx context.Context, tenantID ticketID string) []models.TransferHistoryEntry, error
	GetTransferStats(ctx context.Context, tenantID string) *models.TransferStats, error
	GetWorkflowHistory(ctx context.Context, tenantID ticketID string) []models.WorkflowHistoryEntry, error
	IsServiceActive(ctx context.Context, tenantID string) bool, error
	ListAssignmentRules(ctx context.Context, tenantID string) []models.AssignmentRule, error
	ListAutomationRules(ctx context.Context, tenantID string) []models.AutomationRule, error
	ListDispatchRules(ctx context.Context, tenantID string) []models.DispatchRule, error
	ListEngineers(ctx context.Context, tenantID string) []models.DispatchEngineer, error
	ListSLAPolicies(ctx context.Context, tenantID string) []models.SLAPolicy, error
	ListSuspensions(ctx context.Context, tenantID string) []models.Suspend, error
	ListTickets(ctx context.Context, tenantID string, q models.TicketListQuery) []models.Ticket, error
	RecordSLABreach(ctx context.Context, tenantID ticketID policyID btype string) error
	RegisterEngineer(ctx context.Context, tenantID string, req models.RegisterEngineerRequest) *models.DispatchEngineer, error
	SetServiceActive(ctx context.Context, tenantID string, active bool) error
	TransferTicket(ctx context.Context, tenantID ticketID fromUserID toUserID reason string) error
	UpdateAutomationRule(ctx context.Context, tenantID string, ruleID int, updates map[string]interface{}) error
	UpdateDispatchWeights(ctx context.Context, tenantID string, weights map[string]int) error
	UpdateSLAPolicy(ctx context.Context, tenantID string, policyID int, updates map[string]interface{}) error
	UpdateSLATracking(ctx context.Context, ticketID string, updates map[string]interface{}) error
	UpdateSuspendStatus(ctx context.Context, tenantID id string, status string) error
	UpdateTicket(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpdateTicketStatus(ctx context.Context, tenantID id string, status string) error
	UpsertSLATracking(ctx context.Context, tenantID ticketID priority string, targetResolutionMs int64) *TicketSLATracking, error
}
