// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	GetAllWorkflows(ctx context.Context) []models.WorkflowDefinitionRow, error
	GetWorkflowByID(ctx context.Context, id string) *models.WorkflowDefinitionRow, error
}
