// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/workflow-dependency/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	GetAllWorkflows(ctx context.Context) ([]models.WorkflowDefinitionRow, error)
	GetWorkflowByID(ctx context.Context, id string) (*models.WorkflowDefinitionRow, error)
}
