// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for tenant.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the tenant service.
type ServiceInterface interface {
	AcceptInvite(ctx context.Context, code, userID, userEmail string) (*map[string]any, error)
	AddTenantUser(ctx context.Context, tenantID, userID, role string) error
	AllocateNamespace(ctx context.Context, tenantID int, purpose string) (*models.NamespaceAllocation, error)
	CheckQuota(ctx context.Context, tenantID int, tenantIDStr string, req models.QuotaCheckRequest) (*models.QuotaCheckResult, error)
	CreateTenant(ctx context.Context, req models.CreateTenantRequest) (*map[string]any, error)
	DeleteTenant(ctx context.Context, id string) error
	GetAlertStats(ctx context.Context, tenantID string) (*map[string]any, error)
	GetAlerts(ctx context.Context, tenantID string, q models.AlertsQuery) (*map[string]any, error)
	GetCurrentTenant(ctx context.Context, tenantID string) (*map[string]any, error)
	GetInviteByCode(ctx context.Context, code string) (*map[string]any, error)
	GetPoolStatus(ctx context.Context) (*models.NamespacePoolStatus, error)
	GetQuota(ctx context.Context, tenantID int, tenantIDStr string) (*models.TenantQuota, error)
	GetTenant(ctx context.Context, id string) (*map[string]any, error)
	GetTenantNamespaces(ctx context.Context, tenantID string) ([]models.NamespaceUsageDetail, error)
	GetUserTenants(ctx context.Context, userID string, currentTenantID string) (*map[string]any, error)
	InviteUser(ctx context.Context, tenantID string, req models.InviteRequest) (*models.InviteResponse, error)
	ListTenantUsers(ctx context.Context, tenantID string) ([]map[string]any, error)
	ListTenants(ctx context.Context, req models.ListTenantRequest) (*models.TenantWithMeta, error)
	ReleaseNamespace(ctx context.Context, nsName string) (bool, error)
	RemoveTenantUser(ctx context.Context, tenantID, userID, currentUserID string) error
	SetQuota(ctx context.Context, tenantID int, tenantIDStr string, req models.QuotaUpdateRequest) (*models.TenantQuota, error)
	SplitTenant(ctx context.Context, originalID string, req models.SplitTenantRequest) (*map[string]any, error)
	TenantCount(ctx context.Context, status *string) (int, error)
	UpdateTenant(ctx context.Context, id string, req models.UpdateTenantRequest) (*map[string]any, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
