// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/user-status/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, tenantID, userID string, status string, message string) (*models.UserStatus, error)
	GetByUserID(ctx context.Context, tenantID, userID string) (*models.UserStatus, error)
	Update(ctx context.Context, tenantID, userID string, status string, message string) (*models.UserStatus, error)
	ListByStatus(ctx context.Context, tenantID string, status string) ([]models.UserStatus, error)
	EnsureTable(ctx context.Context) error
}
