// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, tenantID userID string, status string, message string) *models.UserStatus, error
	EnsureTable(ctx context.Context) error
	GetByUserID(ctx context.Context, tenantID userID string) *models.UserStatus, error
	ListByStatus(ctx context.Context, tenantID string, status string) []models.UserStatus, error
	Update(ctx context.Context, tenantID userID string, status string, message string) *models.UserStatus, error
}
