// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/user-activity/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	GetActivities(ctx context.Context, userID string, limit, offset int) ([]models.UserActivity, error)
	GetActivityCount(ctx context.Context, userID string) (int, error)
	CreateActivity(ctx context.Context, a *models.UserActivity) error
	EnsureTable(ctx context.Context) error
	GetActivityByID(ctx context.Context, userID, activityID string) (*models.UserActivity, error)
	DeleteActivity(ctx context.Context, userID, activityID string) error
}
