// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/team/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, m *models.Team) error
	GetByID(ctx context.Context, tenantID, id string) (*models.Team, error)
	GetBySlug(ctx context.Context, tenantID, slug string) (*models.Team, error)
	List(ctx context.Context, tenantID string, typeFilter *string, limit, offset int) ([]models.Team, error)
	Update(ctx context.Context, tenantID, id string, updates map[string]interface{}) error
	Delete(ctx context.Context, tenantID, id string) error
	GetOrphanedChildrenCount(ctx context.Context, tenantID, parentID string) (int64, error)
	GetUserTeams(ctx context.Context, userID, tenantID string) ([]models.Team, error)
	AddMember(ctx context.Context, m *models.TeamMember) error
	RemoveMember(ctx context.Context, teamID, userID string) (bool, error)
	GetMembers(ctx context.Context, teamID string) ([]models.TeamMember, error)
	UpdateMemberRole(ctx context.Context, teamID, userID, newRole string) error
	AssignRole(ctx context.Context, teamID, roleName string, grantedBy *string) error
	RemoveRole(ctx context.Context, teamID, roleName string) (bool, error)
	GetRoles(ctx context.Context, teamID string) ([]models.TeamRole, error)
}
