// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateBaseline(ctx context.Context, tenantID string, b *models.Baseline) *models.Baseline, error
	DetectRegression(ctx context.Context, tenantID string, req *models.DetectRegressionRequest) *models.RegressionResult, error
	GetBaselineByID(ctx context.Context, id string, tenantID string) *models.Baseline, error
	GetBottlenecks(ctx context.Context, tenantID string, profileID string) []models.Bottleneck, error
	GetEvaluationHistory(ctx context.Context, baselineID string, tenantID string) []models.Evaluation, error
	GetSuggestions(ctx context.Context, tenantID string, serviceName string) []models.Suggestion, error
	GetTestResults(ctx context.Context, tenantID string, serviceName string) []models.Baseline, error
	ListBaselines(ctx context.Context, tenantID string) []models.Baseline, error
	ProfileService(ctx context.Context, tenantID string, serviceName string) *models.Profile, error
	RecordEvaluation(ctx context.Context, tenantID string, baselineID string, value float64, status string) error
	RecordTestResult(ctx context.Context, tenantID string, req *models.TestResultRequest) error
}
