// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CheckBudgetAlerts(ctx context.Context, tenantID string) []models.BudgetAlert, error
	CreateBudget(ctx context.Context, budget *models.Budget) int, error
	CreateChargeback(ctx context.Context, e *models.ChargebackEntry) error
	CreateROI(ctx context.Context, e *models.ROIEntry) int, error
	CreateRecommendation(ctx context.Context, rec *models.Recommendation) int, error
	CreateReport(ctx context.Context, report *models.Report) int, error
	DeleteBudget(ctx context.Context, tenantID id string) error
	DeleteRecommendation(ctx context.Context, tenantID string, id string) error
	DetectUnusedResources(ctx context.Context, tenantID string) []models.Recommendation, error
	EstimateSavings(ctx context.Context, tenantID string) *models.SavingsEstimate, error
	ForecastBudget(ctx context.Context, tenantID id string) *models.BudgetForecastResponse, error
	GetAlertTriggers(ctx context.Context) []models.AlertTrigger, error
	GetBudget(ctx context.Context, tenantID id string) *models.Budget, error
	GetBudgetStatus(ctx context.Context, tenantID id string) *models.BudgetStatusResponse, error
	GetChargebackReport(ctx context.Context, tenantID string) []models.ChargebackEntry, error
	GetCostBreakdown(ctx context.Context, tenantID dimension string) []models.CostBreakdownItem, error
	GetCostByEntity(ctx context.Context, tenantID entityType entityID string) []models.CostEntry, error
	GetCostSummary(ctx context.Context, tenantID period string) *models.CostSummary, error
	GetEntityCostTrend(ctx context.Context, tenantID entityType entityID period string) []models.CostTrendPoint, error
	GetROIHistory(ctx context.Context, tenantID string) []models.ROIEntry, error
	GetROISummary(ctx context.Context, tenantID string) *models.ROISummary, error
	GetRecommendation(ctx context.Context, tenantID string, id string) *models.Recommendation, error
	GetRegisteredProviders(ctx context.Context) []string, error
	GetReportHistory(ctx context.Context, tenantID string) []models.Report, error
	GetRightSizingRecommendations(ctx context.Context, tenantID string) []models.Recommendation, error
	GetSchedule(ctx context.Context, provider string) *models.CollectionSchedule, error
	HealthCheck(ctx context.Context) bool, error
	HealthCheckAlways(ctx context.Context) bool, error
	ListBudgets(ctx context.Context, tenantID string, limit offset int) []models.Budget, error
	ListRecommendations(ctx context.Context, tenantID string, limit offset int) []models.Recommendation, error
	SetSchedule(ctx context.Context, provider cronExpression string, enabled bool) error
	TrackCost(ctx context.Context, e *models.CostEntry) int, error
	UpdateBudget(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpdateRecommendationStatus(ctx context.Context, tenantID string, id string, status string) error
}
