/**
 * Mock Data for Core Pages (TASK-905)
 * - Dashboard metrics and activity
 * - Pipeline runs
 * - Deployments
 * - Alerts
 */

import type {
  DashboardMetric,
  ActivityEvent,
  QuickAction,
  PipelineRun,
  Deployment,
  Alert,
} from '@/types/pages';

// ============================================================================
// Dashboard Mock Data
// ============================================================================

export const mockDashboardMetrics: DashboardMetric[] = [
  {
    id: 'pipeline-success-rate',
    title: 'Pipeline 成功率',
    value: '95.2',
    unit: '%',
    trend: 'up',
    trendPercent: 2.3,
    previousValue: '92.9',
    color: '#52c41a',
  },
  {
    id: 'deployment-frequency',
    title: '部署频率',
    value: 156,
    unit: '次/周',
    trend: 'up',
    trendPercent: 12.1,
    previousValue: 139,
    color: '#1890ff',
  },
  {
    id: 'active-alerts',
    title: '活跃告警',
    value: 3,
    unit: '个',
    trend: 'down',
    trendPercent: 25,
    previousValue: 4,
    color: '#faad14',
  },
  {
    id: 'system-health',
    title: '系统健康度',
    value: '99.8',
    unit: '%',
    trend: 'stable',
    trendPercent: 0,
    previousValue: '99.8',
    color: '#722ed1',
  },
];

export const mockRecentActivity: ActivityEvent[] = [
  {
    id: 'act-1',
    title: 'Pipeline "frontend-deploy" 执行成功',
    description: '分支 main, 耗时 2m 30s',
    time: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    type: 'pipeline',
    status: 'success',
    user: 'heal',
  },
  {
    id: 'act-2',
    title: '部署 "api-gateway" 到 production',
    description: '版本 v2.3.1, 策略: rolling',
    time: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    type: 'deployment',
    status: 'success',
    user: 'heal',
  },
  {
    id: 'act-3',
    title: '告警: API Gateway 响应时间超过阈值',
    description: '当前值 456ms, 阈值 200ms',
    time: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    type: 'alert',
    status: 'warning',
  },
  {
    id: 'act-4',
    title: 'Pipeline "api-service-build" 执行中',
    description: '分支 feature/auth, 当前阶段: test',
    time: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    type: 'pipeline',
    status: 'running',
    user: 'ci-bot',
  },
  {
    id: 'act-5',
    title: 'Pipeline "test-suite" 执行失败',
    description: '分支 develop, 阶段 "unit-test" 失败',
    time: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    type: 'pipeline',
    status: 'failed',
    user: 'ci-bot',
  },
  {
    id: 'act-6',
    title: '配置变更: 数据库连接池大小调整为 50',
    time: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    type: 'config',
    user: 'admin',
  },
  {
    id: 'act-7',
    title: '部署 "platform-service" 到 staging',
    description: '版本 v1.8.0-rc.2, 策略: canary',
    time: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    type: 'deployment',
    status: 'success',
    user: 'heal',
  },
];

export const mockQuickActions: QuickAction[] = [
  {
    name: '创建 Pipeline',
    icon: 'RocketOutlined',
    path: '/pipelines',
    color: '#1890ff',
    description: '新建 CI/CD 流水线',
  },
  {
    name: '部署应用',
    icon: 'CloudUploadOutlined',
    path: '/deployments',
    color: '#52c41a',
    description: '部署应用到目标环境',
  },
  {
    name: '查看告警',
    icon: 'BellOutlined',
    path: '/alerts',
    color: '#fa541c',
    description: '查看活跃告警',
  },
  {
    name: '查看日志',
    icon: 'FileTextOutlined',
    path: '/pipelines',
    color: '#722ed1',
    description: '查看流水线执行日志',
  },
];

// ============================================================================
// Pipeline Mock Data
// ============================================================================

export const mockPipelines: PipelineRun[] = [
  {
    id: 'pl-001',
    name: 'frontend-deploy',
    runNumber: 142,
    status: 'success',
    branch: 'main',
    commit: 'a1b2c3d',
    author: 'heal',
    trigger: 'push',
    startTime: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 2 * 60 * 1000 + 150000).toISOString(),
    duration: 150,
    pipelineId: 'pipe-frontend',
    stages: [
      {
        name: 'checkout',
        status: 'success',
        duration: 5,
        startTime: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
        endTime: new Date(Date.now() - 2 * 60 * 1000 + 5000).toISOString(),
        logs: ['Cloning repository...', 'Checkout complete.'],
      },
      {
        name: 'install',
        status: 'success',
        duration: 25,
        logs: ['Installing dependencies...', 'npm install completed in 25s.'],
      },
      {
        name: 'build',
        status: 'success',
        duration: 45,
        logs: ['Building application...', 'Build successful.'],
      },
      {
        name: 'test',
        status: 'success',
        duration: 60,
        logs: ['Running tests...', '42 tests passed, 0 failed.'],
      },
      {
        name: 'deploy',
        status: 'success',
        duration: 15,
        logs: ['Deploying to production...', 'Deployment successful.'],
      },
    ],
  },
  {
    id: 'pl-002',
    name: 'api-service-build',
    runNumber: 89,
    status: 'running',
    branch: 'feature/auth',
    commit: 'e4f5g6h',
    author: 'ci-bot',
    trigger: 'push',
    startTime: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    pipelineId: 'pipe-api',
    stages: [
      {
        name: 'checkout',
        status: 'success',
        duration: 4,
      },
      {
        name: 'install',
        status: 'success',
        duration: 20,
      },
      {
        name: 'build',
        status: 'running',
        duration: 30,
      },
      {
        name: 'test',
        status: 'pending',
      },
      {
        name: 'deploy',
        status: 'pending',
      },
    ],
  },
  {
    id: 'pl-003',
    name: 'database-migration',
    runNumber: 23,
    status: 'pending',
    branch: 'main',
    author: 'heal',
    trigger: 'manual',
    startTime: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    pipelineId: 'pipe-db',
  },
  {
    id: 'pl-004',
    name: 'test-suite',
    runNumber: 201,
    status: 'failed',
    branch: 'develop',
    commit: 'i7j8k9l',
    author: 'ci-bot',
    trigger: 'push',
    startTime: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 60 * 60 * 1000 + 105000).toISOString(),
    duration: 105,
    pipelineId: 'pipe-test',
    stages: [
      {
        name: 'checkout',
        status: 'success',
        duration: 5,
      },
      {
        name: 'install',
        status: 'success',
        duration: 22,
      },
      {
        name: 'unit-test',
        status: 'failed',
        duration: 78,
        logs: [
          'Running unit tests...',
          'FAIL: AuthService.test.ts - should validate JWT tokens',
          'Expected: true, Received: false',
          '41 passed, 1 failed.',
        ],
      },
      {
        name: 'integration-test',
        status: 'pending',
      },
    ],
  },
  {
    id: 'pl-005',
    name: 'docs-build',
    runNumber: 67,
    status: 'success',
    branch: 'main',
    author: 'heal',
    trigger: 'schedule',
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 2 * 60 * 60 * 1000 + 200000).toISOString(),
    duration: 200,
    pipelineId: 'pipe-docs',
  },
  {
    id: 'pl-006',
    name: 'infra-provision',
    runNumber: 12,
    status: 'success',
    branch: 'main',
    author: 'admin',
    trigger: 'api',
    startTime: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 3 * 60 * 60 * 1000 + 300000).toISOString(),
    duration: 300,
    pipelineId: 'pipe-infra',
  },
  {
    id: 'pl-007',
    name: 'security-scan',
    runNumber: 156,
    status: 'warning',
    branch: 'main',
    author: 'ci-bot',
    trigger: 'schedule',
    startTime: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 4 * 60 * 60 * 1000 + 180000).toISOString(),
    duration: 180,
    pipelineId: 'pipe-security',
  },
  {
    id: 'pl-008',
    name: 'mobile-app-build',
    runNumber: 34,
    status: 'cancelled',
    branch: 'feature/new-ui',
    author: 'developer',
    trigger: 'manual',
    startTime: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
    duration: 90,
    pipelineId: 'pipe-mobile',
  },
];

// ============================================================================
// Deployment Mock Data
// ============================================================================

export const mockDeployments: Deployment[] = [
  {
    id: 'dep-001',
    appName: 'api-gateway',
    version: 'v2.3.1',
    environment: 'production',
    strategy: 'rolling',
    status: 'success',
    triggeredBy: 'heal',
    startTime: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 10 * 60 * 1000 + 180000).toISOString(),
    duration: 180,
    pipelineRunId: 'pl-001',
    commit: 'a1b2c3d',
    stages: [
      { name: 'pre-check', status: 'success', details: 'All checks passed' },
      { name: 'deploy', status: 'success', details: 'Rolling update complete' },
      { name: 'health-check', status: 'success', details: 'All endpoints healthy' },
      { name: 'smoke-test', status: 'success', details: 'Smoke tests passed' },
    ],
    healthChecks: [
      { name: 'API /health', status: 'healthy', message: 'OK', latency: 12 },
      { name: 'Database connection', status: 'healthy', message: 'Connected', latency: 5 },
      { name: 'Redis cache', status: 'healthy', message: 'Connected', latency: 2 },
    ],
  },
  {
    id: 'dep-002',
    appName: 'platform-service',
    version: 'v1.8.0-rc.2',
    environment: 'staging',
    strategy: 'canary',
    status: 'success',
    triggeredBy: 'heal',
    startTime: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 3 * 60 * 60 * 1000 + 600000).toISOString(),
    duration: 600,
    commit: 'e4f5g6h',
    stages: [
      { name: 'pre-check', status: 'success', details: 'Canary analysis started' },
      { name: 'deploy-canary', status: 'success', details: '10% traffic routed' },
      { name: 'canary-analysis', status: 'success', details: 'Error rate within threshold' },
      { name: 'full-rollout', status: 'success', details: '100% traffic routed' },
    ],
    healthChecks: [
      { name: 'API /health', status: 'healthy', message: 'OK', latency: 15 },
      { name: 'Database connection', status: 'healthy', message: 'Connected', latency: 8 },
    ],
  },
  {
    id: 'dep-003',
    appName: 'frontend-app',
    version: 'v3.1.0',
    environment: 'production',
    strategy: 'blue-green',
    status: 'running',
    triggeredBy: 'ci-bot',
    startTime: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    stages: [
      { name: 'pre-check', status: 'success', details: 'Blue environment ready' },
      { name: 'deploy-green', status: 'running', details: 'Deploying to green environment' },
      { name: 'traffic-switch', status: 'pending', details: 'Waiting for deployment' },
    ],
  },
  {
    id: 'dep-004',
    appName: 'auth-service',
    version: 'v1.2.3',
    environment: 'production',
    strategy: 'rolling',
    status: 'failed',
    triggeredBy: 'ci-bot',
    startTime: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 24 * 60 * 60 * 1000 + 120000).toISOString(),
    duration: 120,
    rollbackFrom: 'dep-003',
    stages: [
      { name: 'pre-check', status: 'success', details: 'All checks passed' },
      { name: 'deploy', status: 'failed', details: 'Pod failed to start: OOMKilled' },
      { name: 'rollback', status: 'success', details: 'Rolled back to previous version' },
    ],
    healthChecks: [
      { name: 'API /health', status: 'unhealthy', message: 'Connection refused', latency: 0 },
    ],
  },
  {
    id: 'dep-005',
    appName: 'notification-service',
    version: 'v0.9.5',
    environment: 'development',
    strategy: 'recreate',
    status: 'success',
    triggeredBy: 'developer',
    startTime: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 48 * 60 * 60 * 1000 + 90000).toISOString(),
    duration: 90,
    stages: [
      { name: 'pre-check', status: 'success' },
      { name: 'deploy', status: 'success' },
      { name: 'health-check', status: 'success' },
    ],
    healthChecks: [{ name: 'API /health', status: 'healthy', latency: 20 }],
  },
];

// ============================================================================
// Alert Mock Data
// ============================================================================

export const mockAlerts: Alert[] = [
  {
    id: 'alert-001',
    severity: 'critical',
    metric: 'error_rate',
    value: '15.2%',
    threshold: '< 1%',
    status: 'active',
    message: 'API Gateway error rate exceeded critical threshold',
    source: 'api-gateway',
    firstTriggered: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-002',
    severity: 'warning',
    metric: 'response_time_p99',
    value: '456ms',
    threshold: '< 200ms',
    status: 'active',
    message: 'Platform Service P99 response time elevated',
    source: 'platform-service',
    firstTriggered: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-003',
    severity: 'warning',
    metric: 'memory_usage',
    value: '89%',
    threshold: '< 85%',
    status: 'acknowledged',
    message: 'Database server memory usage high',
    source: 'database',
    firstTriggered: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    acknowledgedBy: 'heal',
    acknowledgedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-004',
    severity: 'info',
    metric: 'disk_usage',
    value: '72%',
    threshold: '< 70%',
    status: 'active',
    message: 'Storage volume disk usage approaching threshold',
    source: 'storage',
    firstTriggered: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-005',
    severity: 'critical',
    metric: 'pod_restart_count',
    value: '12',
    threshold: '< 3',
    status: 'resolved',
    message: 'Auth Service pods restarting frequently (OOMKilled)',
    source: 'auth-service',
    firstTriggered: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    acknowledgedBy: 'admin',
    acknowledgedAt: new Date(Date.now() - 23.5 * 60 * 60 * 1000).toISOString(),
    resolvedBy: 'admin',
    resolvedAt: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-006',
    severity: 'warning',
    metric: 'queue_depth',
    value: '1,245',
    threshold: '< 500',
    status: 'active',
    message: 'Event bus queue depth increasing rapidly',
    source: 'event-bus',
    firstTriggered: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-007',
    severity: 'info',
    metric: 'certificate_expiry',
    value: '14 days',
    threshold: '> 30 days',
    status: 'active',
    message: 'TLS certificate for api.orion.internal expires in 14 days',
    source: 'api-gateway',
    firstTriggered: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
  },
];
