/**
 * Schema-as-Code Atlas Migration Management Page
 * Atlas DB schema migration: plan, apply, review, history
 */
import React, { useState, useEffect } from 'react';
import {
  Typography,
  Card,
  Table,
  Tag,
  Button,
  Space,
  Modal,
  message,
  Statistic,
  Row,
  Col,
  Empty,
  Descriptions,
  Alert,
} from 'antd';
import {
  CodeOutlined,
  DatabaseOutlined,
  PlayCircleOutlined,
  HistoryOutlined,
  ReloadOutlined,
  CloudDownloadOutlined,
} from '@ant-design/icons';
import { colors, spacing } from '@/tokens';
import type { ColumnsType } from 'antd/es/table';
import PageSkeleton from '@/components/PageSkeleton';
const { Title, Text } = Typography;

interface Migration {
  id: string;
  version: string;
  description: string;
  status: 'pending' | 'applied' | 'failed';
  dataSource: string;
  executedAt: string;
  duration: number;
}

const FALLBACK_MIGRATIONS: Migration[] = [
  { id: '1', version: 'V20260820__add_users_table', description: 'Create users table with indexes', status: 'applied', dataSource: 'main-db', executedAt: '2026-08-20T10:00:00Z', duration: 234 },
  { id: '2', version: 'V20260821__add_projects_fk', description: 'Add projects foreign key constraint', status: 'applied', dataSource: 'main-db', executedAt: '2026-08-21T14:00:00Z', duration: 156 },
  { id: '3', version: 'V20260825__add_audit_log', description: 'Create audit_log table', status: 'pending', dataSource: 'main-db', executedAt: '', duration: 0 },
  { id: '4', version: 'V20260826__add_partition', description: 'Partition orders table by month', status: 'failed', dataSource: 'analytics-db', executedAt: '2026-08-26T09:00:00Z', duration: 5432 },
];

const AtlasSchemaPage: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [migrations, setMigrations] = useState<Migration[]>(FALLBACK_MIGRATIONS);
  const [planModal, setPlanModal] = useState(false);
  const [applyModal, setApplyModal] = useState(false);
  const [selected, setSelected] = useState<Migration | null>(null);

  const load = async () => {
    setLoading(true);
    try {
      const resp = await fetch('/api/v1/dba/migrations', {
        headers: { Authorization: `Bearer ${localStorage.getItem('token') || ''}` },
      });
      if (resp.ok) {
        const json = await resp.json();
        setMigrations(json.data || FALLBACK_MIGRATIONS);
      }
    } catch {
      setMigrations(FALLBACK_MIGRATIONS);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []);

  const pending = migrations.filter((m) => m.status === 'pending');
  const applied = migrations.filter((m) => m.status === 'applied');
  const failed = migrations.filter((m) => m.status === 'failed');

  const handleApply = async (m: Migration) => {
    setApplyModal(false);
    message.loading({ content: `正在执行迁移 ${m.version}...`, key: 'migrate' });
    try {
      const resp = await fetch(`/api/v1/dba/migrations/${m.id}/apply`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${localStorage.getItem('token') || ''}` },
      });
      if (resp.ok) {
        message.success({ content: `迁移 ${m.version} 执行成功`, key: 'migrate' });
        load();
      } else {
        message.error({ content: '迁移执行失败', key: 'migrate' });
      }
    } catch {
      message.error({ content: '迁移执行失败', key: 'migrate' });
    }
  };

  const columns: ColumnsType<Migration> = [
    { title: '版本', dataIndex: 'version', key: 'version', render: (v: string) => <Text code>{v}</Text> },
    { title: '描述', dataIndex: 'description', key: 'description' },
    { title: '数据源', dataIndex: 'dataSource', key: 'dataSource', width: 100, render: (v: string) => <Tag>{v}</Tag> },
    {
      title: '状态', dataIndex: 'status', key: 'status', width: 90,
      render: (v: string) => <Tag color={v === 'applied' ? 'green' : v === 'pending' ? 'default' : 'error'}>{v === 'applied' ? '已应用' : v === 'pending' ? '待执行' : '失败'}</Tag>,
    },
    { title: '执行时间', dataIndex: 'executedAt', key: 'executedAt', width: 160 },
    { title: '耗时(ms)', dataIndex: 'duration', key: 'duration', width: 100 },
    {
      title: '操作', key: 'action', width: 160,
      render: (_: unknown, r: Migration) => (
        <Space size="small">
          {r.status === 'pending' && (
            <Button size="small" type="primary" icon={<PlayCircleOutlined />} onClick={() => { setSelected(r); setApplyModal(true); }}>执行</Button>
          )}
          <Button size="small" icon={<CloudDownloadOutlined />} onClick={() => { setSelected(r); setPlanModal(true); }}>计划</Button>
        </Space>
      ),
    },
  ];

  const atlasPlan = `-- Atlas Migration Plan: ${selected?.version || '...'}
-- Generated by Atlas CLI

ALTER TABLE \`orders\`
  ADD COLUMN \`new_field\` VARCHAR(255) NULL COMMENT 'new field';

-- Checksum: abc123def456
-- Duration estimate: ~2s`;

  return (
    <div style={{ padding: spacing.lg }}>
      <Title level={2} style={{ marginBottom: spacing.sm }}>
        <CodeOutlined style={{ marginRight: spacing.sm, color: colors.primary[500] }} />
        Schema-as-Code 迁移管理
      </Title>
      <Text type="secondary" style={{ display: 'block', marginBottom: spacing.md }}>
        Atlas DB Schema Migration · Plan → Review → Apply · 版本化 Schema 变更
      </Text>

      {loading ? <PageSkeleton rows={6} /> : (
        <>
          <Row gutter={[spacing.md, spacing.md]} style={{ marginBottom: spacing.md }}>
            <Col span={6}><Card size="small"><Statistic title="迁移总数" value={migrations.length} prefix={<DatabaseOutlined />} /></Card></Col>
            <Col span={6}><Card size="small"><Statistic title="已应用" value={applied.length} prefix={<PlayCircleOutlined />} valueStyle={{ color: colors.success[500] }} /></Card></Col>
            <Col span={6}><Card size="small"><Statistic title="待执行" value={pending.length} prefix={<HistoryOutlined />} valueStyle={{ color: colors.warning[500] }} /></Card></Col>
            <Col span={6}><Card size="small"><Statistic title="失败" value={failed.length} prefix={<DatabaseOutlined />} valueStyle={{ color: failed.length > 0 ? colors.error[500] : colors.success[500] }} /></Card></Col>
          </Row>

          <Card title="迁移历史" extra={<Button icon={<ReloadOutlined />} onClick={load}>刷新</Button>}>
            <Table dataSource={migrations} columns={columns} rowKey="id" size="small" pagination={{ pageSize: 10 }}
              locale={{ emptyText: <Empty description="暂无迁移记录" /> }} />
          </Card>

          <Alert message="Atlas CLI 使用示例" description="atlas migrate diff —env dev —to 'postgres://...?schema=public' —dir file://migrations/"
            type="info" showIcon style={{ marginTop: spacing.md }} />
        </>
      )}

      <Modal title="迁移计划预览" open={planModal} onCancel={() => setPlanModal(false)}
        footer={[<Button key="close" onClick={() => setPlanModal(false)}>关闭</Button>]}
      >
        {selected && (
          <>
            <Descriptions size="small" bordered column={2}>
              <Descriptions.Item label="版本">{selected.version}</Descriptions.Item>
              <Descriptions.Item label="数据源">{selected.dataSource}</Descriptions.Item>
              <Descriptions.Item label="描述" span={2}>{selected.description}</Descriptions.Item>
            </Descriptions>
            <pre style={{ background: '#f0f0f0', padding: 12, borderRadius: 4, fontSize: 12, whiteSpace: 'pre-wrap' }}>
              {atlasPlan}
            </pre>
          </>
        )}
      </Modal>

      <Modal title="确认执行迁移" open={applyModal} onCancel={() => setApplyModal(false)}
        okText="执行" cancelText="取消" confirmLoading={false}
        onOk={() => selected && handleApply(selected)}
      >
        {selected && (
          <>
            <Alert message={`即将执行迁移: ${selected.version}`} description={selected.description} type="warning" showIcon />
            <pre style={{ background: '#f0f0f0', padding: 12, borderRadius: 4, fontSize: 12, marginTop: 12 }}>
              {atlasPlan}
            </pre>
          </>
        )}
      </Modal>
    </div>
  );
};

export default AtlasSchemaPage;
