// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateLocale(ctx context.Context, locale *models.Locale) error
	DeleteTranslation(ctx context.Context, tenantID localeCode namespace key string) bool, error
	GetAllTranslations(ctx context.Context, tenantID localeCode string) map[string]map[string]string, error
	GetTranslationsByNamespace(ctx context.Context, tenantID localeCode namespace string) map[string]string, error
	ListLocales(ctx context.Context, tenantID string) []models.Locale, error
	SetBulkTranslations(ctx context.Context, tenantID localeCode namespace string, kv map[string]string) int, error
	SetTranslation(ctx context.Context, t *models.Translation) error
}
