// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for inspection.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"

	"orion/platform-svc-go/internal/inspection/models"
)

// ServiceInterface defines the interface for the inspection service.
type ServiceInterface interface {
	BatchCreate(ctx context.Context, tenantID string, items []models.CreateRequest) (map[string]any, error)
	Create(ctx context.Context, tenantID string, req models.CreateRequest) (*models.Record, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.Record, error)
	GetHistory(ctx context.Context, tenantID string) ([]string, error)
	GetResults(ctx context.Context, tenantID, id string) ([]models.Record, error)
	GetStats(ctx context.Context, tenantID string) (map[string]any, error)
	List(ctx context.Context, tenantID string) ([]models.Record, error)
	ListTemplates(ctx context.Context, tenantID string) ([]models.Record, error)
	RunInspection(ctx context.Context, tenantID, id string) (map[string]any, error)
	Update(ctx context.Context, tenantID, id string, req models.CreateRequest) (*models.Record, error)
	UpdateStatus(ctx context.Context, tenantID, id string, status string) (map[string]any, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
