apiVersion: v1
kind: Service
metadata:
  name: orion-skill-svc
  namespace: orion
  labels:
    app: orion-skill-svc
    component: skill-management
    tier: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: orion-skill-svc
---
apiVersion: v1
kind: Service
metadata:
  name: orion-skill-svc-nodeport
  namespace: orion
  labels:
    app: orion-skill-svc
    component: skill-management
    tier: backend
spec:
  type: NodePort
  ports:
    - name: http
      port: 3001
      nodePort: 30031
      protocol: TCP
  selector:
    app: orion-skill-svc