// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for cost-allocation.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/cost-allocation/models"
)

// ServiceInterface defines the interface for the cost-allocation service.
type ServiceInterface interface {
	CompleteReport(ctx context.Context, tenantID, id string, totalCost, allocatedCost float64, resultData string) (*models.Report, error)
	CreateAllocation(ctx context.Context, tenantID string, req models.CreateAllocationRequest) (*models.Allocation, error)
	CreateReport(ctx context.Context, tenantID string, req models.CreateReportRequest) (*models.Report, error)
	CreateRule(ctx context.Context, tenantID string, req models.CreateRuleRequest) (*models.Rule, error)
	DeleteAllocation(ctx context.Context, tenantID, id string) (bool, error)
	DeleteReport(ctx context.Context, tenantID, id string) (bool, error)
	DeleteRule(ctx context.Context, tenantID, ruleID string) (bool, error)
	FailReport(ctx context.Context, tenantID, id string, errMsg string) (*models.Report, error)
	GetAllocation(ctx context.Context, tenantID, id string) (*models.Allocation, error)
	GetReport(ctx context.Context, tenantID, id string) (*models.Report, error)
	ListAllocations(ctx context.Context, tenantID string, filter *models.AllocationFilter) ([]models.Allocation, error)
	ListReports(ctx context.Context, tenantID string, filter *models.ReportFilter) ([]models.Report, error)
	ListRules(ctx context.Context, tenantID, allocationID string) ([]models.Rule, error)
	UpdateAllocation(ctx context.Context, tenantID, id string, req models.UpdateAllocationRequest) (*models.Allocation, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
