apiVersion: v1
kind: ConfigMap
metadata:
  name: orion-secret-svc-go-config
  namespace: orion
  labels:
    app: orion-secret-svc-go
    app.kubernetes.io/part-of: orion-platform
data:
  environment: "development"
  database_url: "postgres://orion:orion@postgres:5432/orion_orion_secret_svc_go?sslmode=disable"
  redis_addr: "redis:6379"
  nats_addr: "nats://nats:4222"
  nats_stream: "EVENTS"
