// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Archive(ctx context.Context, tenantID id string) error
	Count(ctx context.Context, tenantID string) int, error
	Create(ctx context.Context, lc *models.ArtifactLifecycle) error
	Delete(ctx context.Context, tenantID id string) error
	GetByArtifactID(ctx context.Context, tenantID artifactID string) *models.ArtifactLifecycle, error
	GetByID(ctx context.Context, tenantID id string) *models.ArtifactLifecycle, error
	GetStageHistory(ctx context.Context, tenantID id string) []models.ArtifactLifecycle, error
	List(ctx context.Context, tenantID string, limit offset int) []models.ArtifactLifecycle, error
	Update(ctx context.Context, tenantID id string, updates map[string]interface{}) error
}
