// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, tenantID string, m *models.ApkUploadRecord) error
	Delete(ctx context.Context, tenantID id string) error
	EnsureTable(ctx context.Context) error
	ExistsByVersion(ctx context.Context, tenantID market packageName version string) bool, error
	GetByID(ctx context.Context, tenantID id string) *models.ApkUploadRecord, error
	List(ctx context.Context, tenantID string, q models.ListQuery) []models.ApkUploadRecord, int, error
	RecentFailures(ctx context.Context, tenantID string, limit int) []models.ApkUploadRecord, error
	Stats(ctx context.Context, tenantID string) *models.ApkUploadStats, error
	Update(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.ApkUploadRecord, error
}
