// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for service-topology.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/service-topology/models"
)

// ServiceInterface defines the interface for the service-topology service.
type ServiceInterface interface {
	AddDependency(ctx context.Context, tenantID, source, target string, relType models.RelationType) error
	Create(ctx context.Context, tenantID string, req models.CreateServiceTopologyRequest) (*models.ServiceTopology, error)
	Delete(ctx context.Context, tenantID, id string) error
	DetectCycles(ctx context.Context, tenantID string) ([][]string, error)
	FindImpactScope(ctx context.Context, tenantID, serviceName string) (*models.ImpactScope, error)
	Get(ctx context.Context, tenantID, id string) (*models.ServiceTopology, error)
	GetByServiceName(ctx context.Context, tenantID, serviceName string) (*models.ServiceTopology, error)
	GetDependencies(ctx context.Context, tenantID, serviceName string) ([]models.TopologyEdge, error)
	GetDownstreamDependents(ctx context.Context, tenantID, serviceName string) ([]string, error)
	GetTopologyStats(ctx context.Context, tenantID string) (*models.TopologyStats, error)
	GetUpstreamDependencies(ctx context.Context, tenantID, serviceName string) ([]string, error)
	List(ctx context.Context, tenantID string) ([]models.ServiceTopology, error)
	RemoveDependency(ctx context.Context, tenantID, source, target string) error
	Update(ctx context.Context, tenantID, id string, req models.UpdateServiceTopologyRequest) (*models.ServiceTopology, error)
	ValidateTopology(ctx context.Context, tenantID string) (*models.ValidateTopologyResult, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
