// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for developer-portal.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/developer-portal/models"
)

// ServiceInterface defines the interface for the developer-portal service.
type ServiceInterface interface {
	ApproveReview(c context.Context, tenantID, id, userID string) (*models.PortalDocument, error)
	ApproveSubscription(c context.Context, tenantID, id, approvedBy string) (*models.Subscription, error)
	CancelSubscription(c context.Context, tenantID, id string) (*models.Subscription, error)
	ClearHistory(c context.Context, tenantID, requestID string) error
	Create(c context.Context, tenantID string, req models.CreateDeveloperPortalRequest) (*models.DeveloperPortal, error)
	CreateDocument(c context.Context, tenantID, userID string, req models.CreateDocumentRequest) (*models.PortalDocument, error)
	CreateMockRule(c context.Context, tenantID string, req models.CreateMockRuleRequest) (*models.MockRule, error)
	CreateNewVersion(c context.Context, tenantID, id, version, userID string) (*models.PortalDocument, error)
	CreateSDKTask(c context.Context, tenantID string, req models.CreateSDKTaskRequest) (*models.SDKTask, error)
	CreateSubscription(c context.Context, tenantID, userID string, req models.CreateSubscriptionRequest) (*models.Subscription, error)
	Delete(c context.Context, tenantID, id string) error
	DeleteDocument(c context.Context, tenantID, id string) error
	DeleteMockRule(c context.Context, tenantID, id string) error
	DeletePlaygroundRequest(c context.Context, tenantID, id string) error
	DeleteSDKTask(c context.Context, tenantID, id string) error
	ExecuteRequest(c context.Context, tenantID, id string) (*models.PlaygroundExecuteResult, error)
	Get(c context.Context, tenantID, id string) (*models.DeveloperPortal, error)
	GetCategories(c context.Context, tenantID string) ([]models.CategoryInfo, error)
	GetDocument(c context.Context, tenantID, id string) (*models.PortalDocument, error)
	GetDocumentStats(c context.Context, tenantID string) (*models.DocumentStats, error)
	GetDocumentVersions(c context.Context, tenantID, id string) ([]models.DocumentVersion, error)
	GetMockRule(c context.Context, tenantID, id string) (*models.MockRule, error)
	GetMockRuleStats(c context.Context, tenantID string) (*models.MockRuleStats, error)
	GetPlaygroundRequest(c context.Context, tenantID, id string) (*models.PlaygroundRequest, error)
	GetPlaygroundStats(c context.Context, tenantID, userID string) (*models.PlaygroundStats, error)
	GetPopular(c context.Context, tenantID string) ([]models.PortalDocument, error)
	GetResponseHistory(c context.Context, tenantID, requestID string, filter models.UsageRecordFilter) (*models.ResponseHistoryListResult, error)
	GetSDKTask(c context.Context, tenantID, id string) (*models.SDKTask, error)
	GetSDKTaskStats(c context.Context, tenantID string) (*models.SDKTaskStats, error)
	GetSubscription(c context.Context, tenantID, id string) (*models.Subscription, error)
	GetSupportedLanguages() []models.SDKLanguage
	GetUsageRecords(c context.Context, tenantID, subscriptionID string, filter models.UsageRecordFilter) (*models.UsageRecordListResult, error)
	GetUsageStats(c context.Context, tenantID string) (*models.SubscriptionStats, error)
	List(c context.Context, tenantID string, limit, offset int) ([]models.DeveloperPortal, error)
	ListDocuments(c context.Context, tenantID string, page, pageSize int) ([]models.PortalDocument, error)
	ListMockRules(c context.Context, tenantID string, filter models.MockRuleFilter) (*models.MockRuleListResult, error)
	ListPlaygroundRequests(c context.Context, tenantID, userID string, filter models.PlaygroundRequestFilter) (*models.PlaygroundRequestListResult, error)
	ListSDKTasks(c context.Context, tenantID string, filter models.SDKTaskFilter) (*models.SDKTaskListResult, error)
	ListSubscriptions(c context.Context, tenantID string, filter models.SubscriptionFilter) (*models.SubscriptionListResult, error)
	MatchRequest(c context.Context, tenantID string, method, path string) (*models.MockSimulateResult, error)
	PublishDocument(c context.Context, tenantID, id, userID string) (*models.PortalDocument, error)
	QuickExecute(c context.Context, tenantID, userID string, req models.PlaygroundExecuteRequest) (*models.PlaygroundExecuteResult, error)
	RecordHelpful(c context.Context, tenantID, id string, helpful bool) (*models.PortalDocument, error)
	RegenerateTask(c context.Context, tenantID, id string) (*models.SDKTask, error)
	RejectReview(c context.Context, tenantID, id, userID, reason string) (*models.PortalDocument, error)
	RejectSubscription(c context.Context, tenantID, id, approvedBy, reason string) (*models.Subscription, error)
	SaveRequest(c context.Context, tenantID, userID string, req models.CreatePlaygroundRequestRequest) (*models.PlaygroundRequest, error)
	SearchDocuments(c context.Context, tenantID string, query string) ([]models.PortalDocument, error)
	SubmitForReview(c context.Context, tenantID, id, userID string) (*models.PortalDocument, error)
	SuspendSubscription(c context.Context, tenantID, id string) (*models.Subscription, error)
	ToggleMockRule(c context.Context, tenantID, id string) (*models.MockRule, error)
	UnpublishDocument(c context.Context, tenantID, id, userID string) (*models.PortalDocument, error)
	Update(c context.Context, tenantID, id string, req models.UpdateDeveloperPortalRequest) (*models.DeveloperPortal, error)
	UpdateDocument(c context.Context, tenantID, id string, req models.UpdateDocumentRequest) (*models.PortalDocument, error)
	UpdateMockRule(c context.Context, tenantID, id string, req models.UpdateMockRuleRequest) (*models.MockRule, error)
	UpdatePlaygroundRequest(c context.Context, tenantID, id string, req models.UpdatePlaygroundRequestRequest) (*models.PlaygroundRequest, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
