// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, m *models.PageRegistry) error
	Delete(ctx context.Context, tenantID path string) error
	GetAll(ctx context.Context, tenantID string) []models.PageRegistry, error
	GetByPath(ctx context.Context, tenantID path string) *models.PageRegistry, error
	GetEnabled(ctx context.Context, tenantID string) []models.PageRegistry, error
	GetHistory(ctx context.Context, tenantID path string) []models.PageRegistryHistory, error
	PathExists(ctx context.Context, tenantID path string) bool, error
	ToggleStatus(ctx context.Context, tenantID path string) *models.PageRegistry, error
	Update(ctx context.Context, tenantID path string, updates map[string]interface{}) *models.PageRegistry, error
}
