// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for sla.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the sla service.
type ServiceInterface interface {
	CreateDefinition(ctx context.Context, tenantID string, req models.CreateDefinitionRequest) (*models.SLADefinition, error)
	DeleteDefinition(ctx context.Context, tenantID, id string) error
	DetectBreaches(ctx context.Context, tenantID string) (*models.DetectionResult, error)
	GetBreachEvents(ctx context.Context, trackingID string) ([]models.SLABreachEvent, error)
	GetDefinition(ctx context.Context, tenantID, id string) (*models.SLADefinition, error)
	GetStats(ctx context.Context, tenantID string) (*models.StatsResult, error)
	GetTracking(ctx context.Context, tenantID, id string) (*models.SLATracking, error)
	ListBreachEvents(ctx context.Context, tenantID string, limit, offset int) (*models.BreachListResult, error)
	ListDefinitions(ctx context.Context, tenantID string, q models.DefinitionListQuery) (*models.DefinitionListResult, error)
	ListTracking(ctx context.Context, tenantID string, q models.TrackingListQuery) (*models.TrackingListResult, error)
	MarkBreached(ctx context.Context, tenantID, trackingID, details string) (*models.SLATracking, error)
	MarkMet(ctx context.Context, tenantID, trackingID string) (*models.SLATracking, error)
	PauseTracking(ctx context.Context, tenantID, trackingID, reason string) (*models.SLATracking, error)
	ResumeTracking(ctx context.Context, tenantID, trackingID string) (*models.SLATracking, error)
	StartTracking(ctx context.Context, tenantID string, req models.StartTrackingRequest) (*models.SLATracking, error)
	UpdateDefinition(ctx context.Context, tenantID, id string, req models.UpdateDefinitionRequest) (*models.SLADefinition, error)
	UpdateTracking(ctx context.Context, tenantID, id string, req models.UpdateTrackingRequest) (*models.SLATracking, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
