// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for degradation.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the degradation service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req *models.CreateDegradationRequest) (*models.Degradation, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.Degradation, error)
	List(ctx context.Context, tenantID string) ([]models.Degradation, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateDegradationRequest) (*models.Degradation, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
