// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for pipeline-template.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/pipeline-template/models"
)

// ServiceInterface defines the interface for the pipeline-template service.
type ServiceInterface interface {
	CreateTemplate(ctx context.Context, req *models.CreateTemplateRequest, tenantID string) (*models.PipelineTemplate, error)
	DeleteTemplate(ctx context.Context, id string, tenantID string) (bool, error)
	GetTemplate(ctx context.Context, id string, tenantID string) (*models.PipelineTemplate, error)
	InstantiateTemplate(ctx context.Context, templateID string, req *models.InstantiateRequest, tenantID string) (*models.InstantiatedPipeline, error)
	ListTemplates(ctx context.Context, tenantID string) ([]models.PipelineTemplate, int, error)
	UpdateTemplate(ctx context.Context, id string, req *models.UpdateTemplateRequest, tenantID string) (*models.PipelineTemplate, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
