// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateBenchmark(ctx context.Context, tenantID string, b *models.ResilienceBenchmark) error
	CreateHistory(ctx context.Context, tenantID string, h *models.ResilienceHistory) error
	CreateRecommendation(ctx context.Context, tenantID string, rec *models.ResilienceRecommendation) error
	DeleteRecommendations(ctx context.Context, tenantID string) error
	EnsureRecommendations(ctx context.Context, tenantID string) error
	GetBenchmark(ctx context.Context, tenantID id string) *models.ResilienceBenchmark, error
	GetRecentHistory(ctx context.Context, tenantID string, limit int) []models.ResilienceHistory, error
	GetServiceScore(ctx context.Context, tenantID serviceName string) *models.ServiceResilienceScore, error
	ListBenchmarks(ctx context.Context, tenantID string, q models.ListQuery) []models.ResilienceBenchmark, int, error
	ListHistory(ctx context.Context, tenantID string, q models.ListQuery) []models.ResilienceHistory, int, error
	ListRecommendations(ctx context.Context, tenantID string, q models.ListQuery, priority component string) []models.ResilienceRecommendation, int, error
	ListServiceScores(ctx context.Context, tenantID string, q models.ListQuery) []models.ServiceResilienceScore, int, error
	UpsertServiceScore(ctx context.Context, tenantID string, s *models.ServiceResilienceScore) error
}
