// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/resilience-score/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	CreateHistory(ctx context.Context, tenantID string, h *models.ResilienceHistory) error
	ListHistory(ctx context.Context, tenantID string, q models.ListQuery) ([]models.ResilienceHistory, int, error)
	GetRecentHistory(ctx context.Context, tenantID string, limit int) ([]models.ResilienceHistory, error)
	CreateRecommendation(ctx context.Context, tenantID string, rec *models.ResilienceRecommendation) error
	ListRecommendations(ctx context.Context, tenantID string, q models.ListQuery, priority, component string) ([]models.ResilienceRecommendation, int, error)
	DeleteRecommendations(ctx context.Context, tenantID string) error
	CreateBenchmark(ctx context.Context, tenantID string, b *models.ResilienceBenchmark) error
	ListBenchmarks(ctx context.Context, tenantID string, q models.ListQuery) ([]models.ResilienceBenchmark, int, error)
	UpsertServiceScore(ctx context.Context, tenantID string, s *models.ServiceResilienceScore) error
	ListServiceScores(ctx context.Context, tenantID string, q models.ListQuery) ([]models.ServiceResilienceScore, int, error)
	GetServiceScore(ctx context.Context, tenantID, serviceName string) (*models.ServiceResilienceScore, error)
	EnsureRecommendations(ctx context.Context, tenantID string) error
	GetBenchmark(ctx context.Context, tenantID, id string) (*models.ResilienceBenchmark, error)
}
