// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for hook-chain.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/hook-chain/models"
)

// ServiceInterface defines the interface for the hook-chain service.
type ServiceInterface interface {
	Count(ctx context.Context, tenantID string) (int, error)
	Create(ctx context.Context, tenantID, userID string, req *models.CreateHookRequest) (*models.Hook, error)
	Delete(ctx context.Context, tenantID, id string) error
	GetByID(ctx context.Context, tenantID, id string) (*models.Hook, error)
	List(ctx context.Context, tenantID string, filter *models.ListFilter, offset, limit int) ([]models.Hook, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateHookRequest) (*models.Hook, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
