// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Count(ctx context.Context, tenantID string, status *string) int, error
	CountExecutionsByWorkflowID(ctx context.Context, workflowID string, tenantID string) int, error
	Create(ctx context.Context, wf *models.Workflow) error
	CreateExecution(ctx context.Context, exec *models.WorkflowExecution) error
	Delete(ctx context.Context, id string, tenantID string) bool, error
	GetByID(ctx context.Context, id string, tenantID string) *models.Workflow, error
	GetExecutionByID(ctx context.Context, id string, tenantID string) *models.WorkflowExecution, error
	List(ctx context.Context, tenantID string, status *string, limit offset int) []models.Workflow, error
	ListExecutionsByWorkflowID(ctx context.Context, workflowID string, tenantID string, limit offset int) []models.WorkflowExecution, error
	SetEnabled(ctx context.Context, id string, tenantID string, enabled bool) *models.Workflow, error
	Update(ctx context.Context, id string, tenantID string, updates map[string]interface{}) *models.Workflow, error
}
