// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for incident.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/incident/models"
)

// ServiceInterface defines the interface for the incident service.
type ServiceInterface interface {
	AddTimelineEvent(ctx context.Context, tenantID, incidentID string, req models.AddTimelineEventRequest) (*models.TimelineEvent, error)
	ArchivePostmortem(ctx context.Context, tenantID, incidentID string) (*models.PostmortemRecord, error)
	AssignCommander(ctx context.Context, tenantID, id, commanderID string) (*models.Incident, error)
	CheckSlaBreach(ctx context.Context, tenantID, incidentID string) (*models.SlaCheckResult, error)
	Create(ctx context.Context, tenantID string, req models.CreateIncidentRequest) (*models.Incident, error)
	CreatePostmortem(ctx context.Context, tenantID, incidentID string, req models.CreatePostmortemRequest) (*models.PostmortemRecord, error)
	Delete(ctx context.Context, tenantID, id string) error
	Escalate(ctx context.Context, tenantID, incidentID string, req models.EscalateRequest) error
	Get(ctx context.Context, tenantID, id string) (*models.Incident, error)
	GetEscalations(ctx context.Context, tenantID, incidentID string) ([]models.EscalationRecord, error)
	GetKnowledgeRecommendations(ctx context.Context, tenantID, incidentID string, limit int) (*models.KnowledgeRecommendationResult, error)
	GetPostmortem(ctx context.Context, tenantID, incidentID string) (*models.PostmortemRecord, error)
	GetStats(ctx context.Context, tenantID string) (*models.IncidentStats, error)
	GetTimeline(ctx context.Context, tenantID, incidentID string, q models.TimelineQuery) ([]models.TimelineEvent, error)
	List(ctx context.Context, tenantID string, q models.IncidentListQuery) (*models.IncidentListResult, error)
	MarkSlaBreach(ctx context.Context, tenantID, incidentID string) (*models.Incident, error)
	PublishPostmortem(ctx context.Context, tenantID, incidentID string, reviewedBy *string) (*models.PostmortemRecord, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateIncidentRequest) (*models.Incident, error)
	UpdatePostmortem(ctx context.Context, tenantID, incidentID string, req models.UpdatePostmortemRequest) (*models.PostmortemRecord, error)
	UpdateStatus(ctx context.Context, tenantID, id, newStatus, actorID, reason string) (*models.Incident, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
