// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreatePRTestResult(ctx context.Context, res *models.PRTestResult) error
	CreateTestCase(ctx context.Context, c *models.TestCase) error
	CreateTestCodeMapping(ctx context.Context, m *models.TestCodeMapping) error
	CreateTestExecutionRecord(ctx context.Context, rec *models.TestExecutionRecord) error
	CreateTestSuite(ctx context.Context, s *models.TestSuite) error
	DeleteCodeMappingsByTenant(ctx context.Context, tenantID string) error
	DeleteExecutionHistoryByTenant(ctx context.Context, tenantID string) error
	DeleteTestCasesByTenant(ctx context.Context, tenantID string) error
	DeleteTestSuite(ctx context.Context, tenantID id string) error
	DeleteTestSuitesByTenant(ctx context.Context, tenantID string) error
	GetAllTestStats(ctx context.Context, tenantID string) []*models.TestHistoryStats, error
	GetCoverageStats(ctx context.Context, tenantID string) models.CoverageStats, error
	GetDependenciesForTest(ctx context.Context, tenantID testID string) []string, error
	GetFlakyTests(ctx context.Context, tenantID string, threshold float64) []string, error
	GetOrCreateTestID(ctx context.Context, tenantID name filePath string) string
	GetPRTestResultByPRID(ctx context.Context, tenantID prID string) *models.PRTestResult, error
	GetPRTestResultByPlanID(ctx context.Context, tenantID planID string) *models.PRTestResult, error
	GetTestHistory(ctx context.Context, tenantID testID string) []models.TestExecutionRecord, error
	GetTestStats(ctx context.Context, tenantID testID string) *models.TestHistoryStats, error
	GetTestsForSourceFile(ctx context.Context, tenantID sourceFile string) []string, error
	ListTestCases(ctx context.Context, tenantID string) []models.TestCase, error
	ListTestCasesByFlakyScore(ctx context.Context, tenantID string, threshold float64) []models.TestCase, error
	ListTestCasesBySuite(ctx context.Context, tenantID suiteID string) []models.TestCase, error
	ListTestSuites(ctx context.Context, tenantID string) []models.TestSuite, error
	PruneOldHistory(ctx context.Context, tenantID string, retentionDays int) int, error
	UpdateCaseFlakyScore(ctx context.Context, tenantID testID string, score float64) error
	UpdatePRTestStatus(ctx context.Context, tenantID prID string, status models.TestStatus) error
}
