// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/test-selector/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	CreatePRTestResult(ctx context.Context, res *models.PRTestResult) error
	GetPRTestResultByPlanID(ctx context.Context, tenantID, planID string) (*models.PRTestResult, error)
	GetPRTestResultByPRID(ctx context.Context, tenantID, prID string) (*models.PRTestResult, error)
	UpdatePRTestStatus(ctx context.Context, tenantID, prID string, status models.TestStatus) error
	CreateTestSuite(ctx context.Context, s *models.TestSuite) error
	ListTestSuites(ctx context.Context, tenantID string) ([]models.TestSuite, error)
	DeleteTestSuitesByTenant(ctx context.Context, tenantID string) error
	DeleteTestSuite(ctx context.Context, tenantID, id string) error
	CreateTestCase(ctx context.Context, c *models.TestCase) error
	ListTestCases(ctx context.Context, tenantID string) ([]models.TestCase, error)
	ListTestCasesBySuite(ctx context.Context, tenantID, suiteID string) ([]models.TestCase, error)
	ListTestCasesByFlakyScore(ctx context.Context, tenantID string, threshold float64) ([]models.TestCase, error)
	DeleteTestCasesByTenant(ctx context.Context, tenantID string) error
	CreateTestExecutionRecord(ctx context.Context, rec *models.TestExecutionRecord) error
	GetTestHistory(ctx context.Context, tenantID, testID string) ([]models.TestExecutionRecord, error)
	GetTestStats(ctx context.Context, tenantID, testID string) (*models.TestHistoryStats, error)
	GetAllTestStats(ctx context.Context, tenantID string) ([]*models.TestHistoryStats, error)
	GetFlakyTests(ctx context.Context, tenantID string, threshold float64) ([]string, error)
	DeleteExecutionHistoryByTenant(ctx context.Context, tenantID string) error
	PruneOldHistory(ctx context.Context, tenantID string, retentionDays int) (int, error)
	CreateTestCodeMapping(ctx context.Context, m *models.TestCodeMapping) error
	DeleteCodeMappingsByTenant(ctx context.Context, tenantID string) error
	GetCoverageStats(ctx context.Context, tenantID string) (models.CoverageStats, error)
	GetTestsForSourceFile(ctx context.Context, tenantID, sourceFile string) ([]string, error)
	GetDependenciesForTest(ctx context.Context, tenantID, testID string) ([]string, error)
	GetOrCreateTestID(ctx context.Context, tenantID, name, filePath string) string
	UpdateCaseFlakyScore(ctx context.Context, tenantID, testID string, score float64) error
}
