// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/sso-unified/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, config *models.SSOConfig) error
	GetByProvider(ctx context.Context, tenantID, provider string) (*models.SSOConfig, error)
	GetAll(ctx context.Context, tenantID string) ([]models.SSOConfig, error)
	Update(ctx context.Context, tenantID, provider string, updates map[string]interface{}) (*models.SSOConfig, error)
	Delete(ctx context.Context, tenantID, provider string) (bool, error)
}
