apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: orion-ai-svc-pdb
  namespace: orion
  labels:
    app: orion-ai-svc
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: orion-ai-svc
