// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CountExemptions(ctx context.Context, tenantID string) int, error
	CreateBundle(ctx context.Context, b *models.PolicyBundle) error
	CreateEvaluation(ctx context.Context, e *models.PolicyEvaluation) error
	CreateExemption(ctx context.Context, e *models.Exemption) error
	CreateOverride(ctx context.Context, o *models.PolicyOverride) error
	CreatePolicy(ctx context.Context, m *models.Policy) error
	CreateViolation(ctx context.Context, v *models.Violation) error
	DeletePolicy(ctx context.Context, tenantID id string) error
	GetBundle(ctx context.Context, tenantID id string) *models.PolicyBundle, error
	GetEvaluation(ctx context.Context, tenantID id string) *models.PolicyEvaluation, error
	GetExemption(ctx context.Context, tenantID id string) *models.Exemption, error
	GetPolicy(ctx context.Context, tenantID id string) *models.Policy, error
	GetViolation(ctx context.Context, tenantID id string) *models.Violation, error
	ListBundles(ctx context.Context, tenantID string) []models.PolicyBundle, error
	ListEvaluationHistory(ctx context.Context, tenantID policyID string, limit offset int) []models.PolicyEvaluation, error
	ListEvaluations(ctx context.Context, tenantID string, limit offset int) []models.PolicyEvaluation, error
	ListExemptions(ctx context.Context, tenantID string, status models.ExemptionStatus, policyID string, limit offset int) []models.Exemption, error
	ListOverrides(ctx context.Context, tenantID string, limit offset int) []models.PolicyOverride, error
	ListPolicies(ctx context.Context, tenantID string, limit offset int) []models.Policy, error
	ListViolations(ctx context.Context, tenantID string, limit offset int) []models.Violation, error
	TogglePolicy(ctx context.Context, tenantID id string, enabled bool) *models.Policy, error
	UpdateBundle(ctx context.Context, tenantID id string, status string) error
	UpdateExemption(ctx context.Context, tenantID id string, status models.ExemptionStatus, reviewer note string) error
	UpdatePolicy(ctx context.Context, tenantID id string, m *models.Policy) error
	UpdateViolationStatus(ctx context.Context, tenantID id string, status string) error
}
