// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	DeleteConfig(ctx context.Context, tenantID string) error
	EnsureTable(ctx context.Context) error
	GetConfig(ctx context.Context, tenantID string) *models.PrivacyConfig, error
	ListComplianceStatus(ctx context.Context) []models.ComplianceStatus, error
	UpdateConfig(ctx context.Context, tenantID string, updates map[string]interface{}) *models.PrivacyConfig, error
	UpsertConfig(ctx context.Context, tenantID string, cfg *models.PrivacyConfig) *models.PrivacyConfig, error
}
