// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for abac-policy.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the abac-policy service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req *models.CreateABACPolicyRequest) (*models.ABACPolicy, error)
	Delete(ctx context.Context, tenantID, id string) (bool, error)
	GetByID(ctx context.Context, tenantID, id string) (*models.ABACPolicy, error)
	List(ctx context.Context, tenantID string, filter *models.ABACPolicyFilter) ([]models.ABACPolicy, int, error)
	Update(ctx context.Context, tenantID, id string, req *models.UpdateABACPolicyRequest) (*models.ABACPolicy, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
