// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for api-consumption.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the api-consumption service.
type ServiceInterface interface {
	CreateConsumption(ctx context.Context, tenantID string, req *models.CreateConsumptionRequest) (*models.Consumption, error)
	CreateLimit(ctx context.Context, tenantID string, req *models.CreateLimitRequest) (*models.Limit, error)
	DeleteLimit(ctx context.Context, tenantID, id string) error
	GetLimit(ctx context.Context, tenantID, id string) (*models.Limit, error)
	GetStats(ctx context.Context, tenantID string) (*models.ConsumptionStats, error)
	ListConsumptions(ctx context.Context, tenantID string, filter *models.ConsumptionFilter) ([]models.Consumption, error)
	ListLimits(ctx context.Context, tenantID string) ([]models.Limit, error)
	UpdateLimit(ctx context.Context, tenantID, id string, req *models.UpdateLimitRequest) (*models.Limit, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
