// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Count(ctx context.Context, tenantID string) int, error
	Create(ctx context.Context, p *models.Permission) error
	Delete(ctx context.Context, tenantID id string) error
	GetByID(ctx context.Context, tenantID id string) *models.Permission, error
	List(ctx context.Context, tenantID string, filter *models.ListFilter, offset limit int) []models.Permission, error
	Update(ctx context.Context, p *models.Permission) error
}
