// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for deploy.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/deploy/models"
)

// ServiceInterface defines the interface for the deploy service.
type ServiceInterface interface {
	Cancel(ctx context.Context, tenantID, id string) error
	Complete(ctx context.Context, tenantID, id string, status string) error
	Create(ctx context.Context, tenantID string, req models.CreateDeploymentRequest) (*models.Deployment, error)
	GenerateReleaseNotes(ctx context.Context, tenantID, deploymentID, content string) (*models.ReleaseNote, error)
	Get(ctx context.Context, tenantID, id string) (*models.Deployment, error)
	GetAuditTrail(ctx context.Context, deploymentID string) ([]models.AuditEntry, error)
	GetDeploymentChangelog(ctx context.Context, deploymentID string) ([]models.GitChangelogEntry, error)
	GetLatest(ctx context.Context, tenantID, appName, environment string) (*models.Deployment, error)
	GetReleaseNotes(ctx context.Context, deploymentID string) (*models.ReleaseNote, error)
	GetReleaseNotesByTenant(ctx context.Context, tenantID string) ([]models.ReleaseNote, error)
	GetRollbackHistory(ctx context.Context, tenantID, id string) ([]models.Rollback, error)
	LinkGitCommit(ctx context.Context, deploymentID, commitSHA, branch string) error
	List(ctx context.Context, tenantID string, limit, offset int) ([]models.Deployment, error)
	LogAudit(ctx context.Context, deploymentID, action, userID, details string) error
	Metrics(ctx context.Context, tenantID string) (*models.DeploymentMetrics, error)
	Rollback(ctx context.Context, tenantID, id string, targetVersion, reason string) (*models.Rollback, error)
	Start(ctx context.Context, tenantID, id string) error
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
