// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for mcp.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the mcp service.
type ServiceInterface interface {
	CreateServer(ctx context.Context, tenantID string, req models.CreateMCPServerRequest) (*models.MCPServer, error)
	DeleteServer(ctx context.Context, tenantID, id string) error
	GetServer(ctx context.Context, tenantID, id string) (*models.MCPServer, error)
	ListServers(ctx context.Context, tenantID string, q models.ListMCPServersQuery) (*models.MCPServerListResponse, error)
	ListTools(ctx context.Context, q models.ListMCPToolsQuery) (*models.MCPToolListResponse, error)
	UpdateServer(ctx context.Context, tenantID, id string, req models.UpdateMCPServerRequest) (*models.MCPServer, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
