// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	AggregateCosts(ctx context.Context, tenantID string) *models.CloudStats, error
	CountResources(ctx context.Context, tenantID string) int, error
	CreateAccount(ctx context.Context, account *models.CloudAccount) error
	CreateMigrationPlan(ctx context.Context, plan *models.MigrationPlan) error
	CreatePolicy(ctx context.Context, policy *models.SchedulingPolicy) error
	CreateResource(ctx context.Context, resource *models.CloudResource) error
	DeleteAccount(ctx context.Context, tenantID id string) bool, error
	GetAccountByID(ctx context.Context, tenantID id string) *models.CloudAccount, error
	GetMigrationPlanByID(ctx context.Context, tenantID id string) *models.MigrationPlan, error
	GetPolicyByID(ctx context.Context, tenantID id string) *models.SchedulingPolicy, error
	GetResourceByID(ctx context.Context, tenantID resourceType resourceID string) *models.CloudResource, error
	GetResourceStatistics(ctx context.Context, tenantID string) *models.ResourceStatistics, error
	GetResourcesByAccount(ctx context.Context, tenantID accountID string) []models.CloudResource, error
	GetSchedulingHistory(ctx context.Context, tenantID string) []models.ScheduleDecision, error
	InsertSchedulingHistory(ctx context.Context, tenantID string, decision models.ScheduleDecision, policyID string) error
	ListAccounts(ctx context.Context, tenantID string) []models.CloudAccount, error
	ListPolicies(ctx context.Context, tenantID string) []models.SchedulingPolicy, error
	ListResources(ctx context.Context, tenantID string) []models.CloudResource, error
	ListResourcesByAccount(ctx context.Context, tenantID accountID string) []models.CloudResource, error
	UpdateAccount(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.CloudAccount, error
	UpdateMigrationPlanStatus(ctx context.Context, tenantID id status string) error
}
