// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for deploy-enhanced.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the deploy-enhanced service.
type ServiceInterface interface {
	AdvanceStage(ctx context.Context, id string, stageID string, validationResult *string, tenantID string) (*models.ProgressiveDeploy, error)
	ApproveEmergencyDeploy(ctx context.Context, id string, approvedBy string, tenantID string) (*models.EmergencyDeploy, error)
	CheckWindow(ctx context.Context, id string, tenantID string) (*models.WindowCheckResult, error)
	CompleteEmergencyDeploy(ctx context.Context, id string, postMortem *string, tenantID string) (*models.EmergencyDeploy, error)
	CreateProgressiveDeploy(ctx context.Context, deploymentID string, req *models.CreateProgressiveDeployRequest, tenantID string) (*models.ProgressiveDeploy, error)
	CreateWindow(ctx context.Context, req *models.CreateDeployWindowRequest, tenantID string) (*models.DeployWindow, error)
	DeleteWindow(ctx context.Context, id string, tenantID string) (bool, error)
	GetEmergencyDeploy(ctx context.Context, id string, tenantID string) (*models.EmergencyDeploy, error)
	GetProgress(ctx context.Context, id string, tenantID string) (*models.ProgressiveDeploy, error)
	GetWindow(ctx context.Context, id string, tenantID string) (*models.DeployWindow, error)
	ListEmergencies(ctx context.Context, tenantID string, status *string) ([]models.EmergencyDeploy, int, error)
	ListWindows(ctx context.Context, tenantID string, environmentID *string, status *string) ([]models.DeployWindow, int, error)
	RejectEmergencyDeploy(ctx context.Context, id string, tenantID string) (*models.EmergencyDeploy, error)
	RequestEmergencyDeploy(ctx context.Context, req *models.CreateEmergencyDeployRequest, tenantID string) (*models.EmergencyDeploy, error)
	RollbackStage(ctx context.Context, id string, stageID string, reason string, tenantID string) (*models.ProgressiveDeploy, error)
	UpdateWindow(ctx context.Context, id string, req *models.UpdateDeployWindowRequest, tenantID string) (*models.DeployWindow, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
