apiVersion: v1
kind: Service
metadata:
  name: orion-plugin-svc
  namespace: orion
  labels:
    app: orion-plugin
    component: plugin-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3011
      protocol: TCP
      name: http
  selector:
    app: orion-plugin
---
apiVersion: v1
kind: Service
metadata:
  name: orion-plugin-svc-headless
  namespace: orion
  labels:
    app: orion-plugin
    component: plugin-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3011
      targetPort: 3011
      protocol: TCP
      name: http
  selector:
    app: orion-plugin