// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	ApprovePermissionRequest(ctx context.Context, ticketID int, approverID string) error
	CheckPermission(ctx context.Context, tenantID capabilityID userID string, userRoles []string) bool, string, error
	CleanupExpiredTemporaryPermissions(ctx context.Context, tenantID string) int, error
	Create(ctx context.Context, m *models.Capability) error
	CreatePermissionRequest(ctx context.Context, tenantID string, userID capabilityID reason string, durationHours int, envSuffix *string) error
	Delete(ctx context.Context, tenantID id string) error
	GetActiveTempExpiry(ctx context.Context, tenantID capabilityID userID string) *time.Time, error
	GetActiveTemporaryPermissions(ctx context.Context, tenantID userId string) []models.TemporaryPermission, error
	GetByCapabilityID(ctx context.Context, tenantID capabilityID string) *models.Capability, error
	GetByID(ctx context.Context, tenantID id string) *models.Capability, error
	GetCapabilityForCommand(ctx context.Context, tenantID command action string, env *string) *models.Capability, error
	GetCapabilityForPermissionRequest(ctx context.Context, tenantID capabilityID string) *models.Capability, error
	GetCapabilityIDForCommand(ctx context.Context, tenantID command action env string) string, error
	GetParent(ctx context.Context, tenantID parentCapabilityID string) *models.Capability, error
	GetPermissionRequestByID(ctx context.Context, tenantID string, ticketID int) *models.PermissionRequest, error
	GetTemporaryPermissionByID(ctx context.Context, tenantID string, id int) *models.TemporaryPermission, error
	GetUserGrantExpiry(ctx context.Context, tenantID capabilityID userID string) *time.Time, error
	GetUserPermissionRequests(ctx context.Context, tenantID userId string) []models.PermissionRequest, error
	GrantCapabilityToRole(ctx context.Context, tenantID string, capabilityID roleName string) error
	GrantCapabilityToUser(ctx context.Context, tenantID string, capabilityID userId grantedBy string, expiresInHours *int) error
	GrantTemporaryPermission(ctx context.Context, tenantID string, userID capabilityID grantedBy string, envSuffix *string, expiresInHours int) error
	HasChildren(ctx context.Context, tenantID id string) bool, error
	InsertAuditLog(ctx context.Context, tenantID action userID targetType targetID details string) error
	InsertCommandMapping(ctx context.Context, tenantID string, capID string, cmdName cmdAction string, envSuffix *string) error
	List(ctx context.Context, tenantID string, limit offset int) []models.Capability, error
	ListAuditLogs(ctx context.Context, tenantID string, q *models.AuditLogQuery) []map[string]interface{}, error
	ListByCategory(ctx context.Context, tenantID category string, limit offset int) []models.Capability, error
	ListByParent(ctx context.Context, tenantID parentCapabilityID string) []models.Capability, error
	ListCapabilityIDsByRole(ctx context.Context, tenantID role string) []string, error
	ListCapabilityIDsByUser(ctx context.Context, tenantID userID string) []string, error
	ListRoot(ctx context.Context, tenantID string) []models.Capability, error
	RejectPermissionRequest(ctx context.Context, ticketID int, rejecterID string, reason *string) error
	RevokeCapabilityFromRole(ctx context.Context, tenantID string, capabilityID roleName string) error
	RevokeCapabilityFromUser(ctx context.Context, tenantID string, capabilityID userId string) error
	RevokeTemporaryPermissionByID(ctx context.Context, id int, byUserID string) error
	Update(ctx context.Context, tenantID id string, updates map[string]interface{}) error
}
