// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/workflow-webhook/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	FindByWebhookPath(ctx context.Context, webhookPath string) (*models.WebhookTrigger, error)
	Create(ctx context.Context, t *models.WebhookTrigger) error
	GetByID(ctx context.Context, tenantID, id string) (*models.WebhookTrigger, error)
	List(ctx context.Context, tenantID string, filter *models.ListFilter, offset, limit int) ([]models.WebhookTrigger, error)
	Count(ctx context.Context, tenantID string) (int, error)
	Update(ctx context.Context, t *models.WebhookTrigger) error
	Delete(ctx context.Context, tenantID, id string) error
	CreateLog(ctx context.Context, log *models.WebhookTriggerLog) error
	UpdateLogStatus(ctx context.Context, id, status, errorMessage string, durationMs int) error
	ListLogs(ctx context.Context, triggerID string, offset, limit int) ([]models.WebhookTriggerLog, error)
}
