// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for pipeline-run-history.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the pipeline-run-history service.
type ServiceInterface interface {
	GetRunHistory(ctx context.Context, pipelineID string, tenantID string, period string, limit int) (*models.RunHistoryResponse, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
