// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for skill.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the skill service.
type ServiceInterface interface {
	AddVersion(ctx context.Context, tenantID, skillID string, req models.AddVersionRequest) (*models.SkillVersion, error)
	CreateInstance(ctx context.Context, tenantID, skillID string, req models.CreateInstanceRequest) (*models.SkillInstance, error)
	CreateSkill(ctx context.Context, tenantID string, req models.CreateSkillRequest) (*models.Skill, error)
	DeleteInstance(ctx context.Context, tenantID, id string) error
	DeleteSkill(ctx context.Context, tenantID, id string) error
	ExecuteSkill(ctx context.Context, tenantID, skillID, userID string, req models.ExecuteSkillRequest) (*models.SkillExecution, error)
	GetInstance(ctx context.Context, tenantID, id string) (*models.SkillInstance, error)
	GetRatingStats(ctx context.Context, tenantID, skillID string) (*map[string]any, error)
	GetReview(ctx context.Context, tenantID, skillID string) (*models.SkillReview, error)
	GetSkill(ctx context.Context, tenantID, id string) (*models.Skill, error)
	GetStats(ctx context.Context, tenantID string) (*map[string]any, error)
	ListAuditLogs(ctx context.Context, tenantID, skillID string, page, limit int) ([]models.SkillAuditLog, int64)
	ListExecutions(ctx context.Context, tenantID, skillID string, page, limit int) ([]models.SkillExecution, error)
	ListInstances(ctx context.Context, tenantID string) ([]models.SkillInstance, error)
	ListReviews(ctx context.Context, tenantID string, status string) ([]models.SkillReview, error)
	ListSkills(ctx context.Context, tenantID string, category, status string, page, limit int) ([]models.Skill, int64)
	ListVersions(ctx context.Context, tenantID, skillID string) ([]models.SkillVersion, error)
	RateSkill(ctx context.Context, tenantID, skillID, userID string, req models.RateSkillRequest) (*models.Skill, error)
	ReviewAction(ctx context.Context, tenantID, skillID, userID, action string, req models.ReviewActionRequest) (*models.SkillReview, error)
	UpdateInstance(ctx context.Context, tenantID, id string, req models.UpdateInstanceRequest) (*models.SkillInstance, error)
	UpdateSkill(ctx context.Context, tenantID, id string, req models.UpdateSkillRequest) (*models.Skill, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
