// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/subapp/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, m *models.SubApp) error
	GetByKey(ctx context.Context, tenantID, key string) (*models.SubApp, error)
	GetAll(ctx context.Context, tenantID string) ([]models.SubApp, error)
	GetEnabled(ctx context.Context, tenantID string) ([]models.SubApp, error)
	Update(ctx context.Context, m *models.SubApp) error
	UpdatePartial(ctx context.Context, tenantID, key string, updates map[string]interface{}) error
	ToggleStatus(ctx context.Context, tenantID, key string) (*models.SubApp, error)
	Delete(ctx context.Context, tenantID, key string) error
	AddHistory(ctx context.Context, h *models.SubAppConfigHistory) error
	GetHistory(ctx context.Context, tenantID, key string) ([]models.SubAppConfigHistory, error)
}
