// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for apk-upload-history.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/apk-upload-history/models"
)

// ServiceInterface defines the interface for the apk-upload-history service.
type ServiceInterface interface {
	CheckDuplicate(ctx context.Context, tenantID, market, packageName, version string) (bool, error)
	CreateRecord(ctx context.Context, tenantID string, record *models.ApkUploadRecord) (*models.ApkUploadRecord, error)
	GetRecord(ctx context.Context, tenantID, id string) (*models.ApkUploadRecord, error)
	GetStats(ctx context.Context, tenantID string) (*models.ApkUploadStats, error)
	ListRecords(ctx context.Context, tenantID string, q models.ListQuery) ([]models.ApkUploadRecord, int, error)
	RecentFailures(ctx context.Context, tenantID string) ([]models.ApkUploadRecord, error)
	UpdateStatus(ctx context.Context, tenantID, id string, status models.ApkStatus, errMsg string) (*models.ApkUploadRecord, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
