// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, tenantID string, req models.CreateHealthCheckRequest) string, error
	Delete(ctx context.Context, tenantID id string) error
	Get(ctx context.Context, tenantID id string) *models.HealthCheck, error
	List(ctx context.Context, tenantID string) []models.HealthCheck, error
	Update(ctx context.Context, tenantID id string, req models.CreateHealthCheckRequest) error
}
