// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for change.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/change/models"
)

// ServiceInterface defines the interface for the change service.
type ServiceInterface interface {
	AddCABDecision(ctx context.Context, tenantID, cabID string, req models.CreateCABDecisionRequest) (*models.CABDecision, error)
	AddTimelineEvent(ctx context.Context, tenantID, changeRequestID, eventType, description string, metadata map[string]any, userID string) (*models.TimelineEvent, error)
	CreateCABMeeting(ctx context.Context, tenantID string, req models.CreateCABMeetingRequest, userID string) (*models.CABMeeting, error)
	CreateChangeRequest(ctx context.Context, tenantID string, req models.CreateChangeRequestRequest, userID string) (*models.ChangeRequest, error)
	CreateRFC(ctx context.Context, tenantID string, req models.CreateRFCRequest, userID string) (*models.RFC, error)
	DeleteChangeRequest(ctx context.Context, tenantID, id string) error
	GetCABMeeting(ctx context.Context, tenantID, id string) (*models.CABMeeting, error)
	GetChangeRequest(ctx context.Context, tenantID, id string) (*models.ChangeRequest, error)
	GetRFC(ctx context.Context, tenantID, id string) (*models.RFC, error)
	GetStats(ctx context.Context, tenantID string) (*models.ChangeStats, error)
	GetTimeline(ctx context.Context, tenantID, changeRequestID string, limit, offset int) ([]models.TimelineEvent, error)
	ListCABMeetings(ctx context.Context, tenantID string, q models.CABMeetingListQuery) (*models.ListResult[models.CABMeeting], error)
	ListChangeRequests(ctx context.Context, tenantID string, q models.ChangeRequestListQuery) (*models.ListResult[models.ChangeRequest], error)
	ListRFCs(ctx context.Context, tenantID string, limit, offset int) (*models.ListResult[models.RFC], error)
	UpdateCABMeeting(ctx context.Context, tenantID, id string, req models.UpdateCABMeetingRequest) (*models.CABMeeting, error)
	UpdateChangeRequest(ctx context.Context, tenantID, id string, req models.UpdateChangeRequestRequest) (*models.ChangeRequest, error)
	UpdateRFC(ctx context.Context, tenantID, id string, req models.UpdateRFCRequest) (*models.RFC, error)
	UpdateStatus(ctx context.Context, tenantID, id, status, reason string) (*models.ChangeRequest, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
