apiVersion: v1
kind: Service
metadata:
  name: orion-governance-svc
  namespace: orion
  labels:
    app: orion-governance-svc
    component: governance-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3030
      targetPort: 3030
      protocol: TCP
  selector:
    app: orion-governance-svc
---
apiVersion: v1
kind: Service
metadata:
  name: orion-governance-svc-nodeport
  namespace: orion
  labels:
    app: orion-governance-svc
    component: governance-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 3030
      targetPort: 3030
      nodePort: 30330
      protocol: TCP
  selector:
    app: orion-governance-svc