// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for unified-config.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the unified-config service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateUnifiedConfigRequest) (*models.UnifiedConfig, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.UnifiedConfig, error)
	List(ctx context.Context, tenantID string) ([]models.UnifiedConfig, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateUnifiedConfigRequest) (*models.UnifiedConfig, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
