// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for service-registry.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the service-registry service.
type ServiceInterface interface {
	Deregister(ctx context.Context, tenantID, serviceID string) error
	GetByInternalID(ctx context.Context, tenantID, id string) (*models.ServiceRegistry, error)
	GetByServiceID(ctx context.Context, tenantID, serviceID string) (*models.ServiceRegistry, error)
	List(ctx context.Context, tenantID string, f *repository.ListFilters) ([]models.ServiceRegistry, error)
	RecordHeartbeat(ctx context.Context, tenantID, serviceID string) error
	Register(ctx context.Context, tenantID string, req models.RegisterRequest) (*models.ServiceRegistry, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
