// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for circuit-breaker.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the circuit-breaker service.
type ServiceInterface interface {
	Create(ctx context.Context, req *models.CreateRequest, tenantID string) (*models.CircuitBreaker, error)
	Delete(ctx context.Context, id, tenantID string) (bool, error)
	Evaluate(ctx context.Context, id, tenantID string) (*models.StateResponse, error)
	Get(ctx context.Context, id, tenantID string) (*models.CircuitBreaker, error)
	GetRecentEvents(ctx context.Context, id, tenantID string, limit int) ([]models.CircuitEvent, error)
	List(ctx context.Context, tenantID string) ([]models.CircuitBreaker, error)
	ListOpen(ctx context.Context, tenantID string) ([]models.CircuitBreaker, error)
	RecordFailure(ctx context.Context, id, tenantID string, errMsg string) (*models.CircuitBreaker, error)
	RecordSuccess(ctx context.Context, id, tenantID string, responseTimeMs int) (*models.CircuitBreaker, error)
	Update(ctx context.Context, id, tenantID string, req *models.UpdateRequest) (*models.CircuitBreaker, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
