// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateContract(ctx context.Context, contract *models.Contract) error
	CreateEndpoint(ctx context.Context, endpoint *models.Endpoint) error
	DeleteContract(ctx context.Context, tenantID id string) bool, error
	DeleteEndpoint(ctx context.Context, tenantID contractID id string) bool, error
	GetContractByID(ctx context.Context, tenantID id string) *models.Contract, error
	GetStats(ctx context.Context, tenantID string) *models.ContractStats, error
	ListContracts(ctx context.Context, tenantID string, filter *models.ContractFilter) []models.Contract, error
	ListEndpointsByContract(ctx context.Context, tenantID contractID string) []models.Endpoint, error
	UpdateContract(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.Contract, error
}
