// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CreateKnownError(ctx context.Context, ke *models.KnownError) error
	CreateProblem(ctx context.Context, problem *models.Problem) error
	DeleteKnownError(ctx context.Context, id string) bool, error
	DeleteProblem(ctx context.Context, id string, tenantID string) bool, error
	GetChangeLinks(ctx context.Context, problemID string) []string, error
	GetIncidentLinks(ctx context.Context, problemID string) []string, error
	GetKnownErrorByID(ctx context.Context, id string) *models.KnownError, error
	GetProblemByID(ctx context.Context, id string, tenantID string) *models.Problem, error
	GetStats(ctx context.Context, tenantID string) *models.ProblemStats, error
	LinkChangeWithTenant(ctx context.Context, problemID changeID tenantID string) *models.Problem, error
	LinkIncident(ctx context.Context, problemID incidentID string) *models.Problem, error
	LinkIncidentWithTenant(ctx context.Context, problemID incidentID tenantID string) *models.Problem, error
	ListKnownErrors(ctx context.Context, tenantID string, filter *models.KnownErrorFilter) []models.KnownError, int, error
	ListProblems(ctx context.Context, tenantID string, filter *models.ProblemFilter) []models.Problem, int, error
	SearchKnownErrors(ctx context.Context, query string, tenantID string) []models.KnownError, int, error
	UpdateKnownError(ctx context.Context, id string, updates map[string]interface{}) *models.KnownError, error
	UpdateProblem(ctx context.Context, id string, tenantID string, updates map[string]interface{}) *models.Problem, error
}
