// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for user-token.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/user-token/models"
)

// ServiceInterface defines the interface for the user-token service.
type ServiceInterface interface {
	CreateToken(ctx context.Context, tenantID string, req models.CreateTokenRequest) (models.CreateTokenResponse, error)
	DeleteToken(ctx context.Context, tenantID, id string) error
	GetTokens(ctx context.Context, tenantID, userID string) ([]models.Token, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
