// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for metadata.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"

	"github.com/gin-gonic/gin"
	"orion/platform-svc-go/internal/metadata/models"
)

// ServiceInterface defines the interface for the metadata service.
type ServiceInterface interface {
	BatchCreate(ctx context.Context, tenantID string) error
	Create(ctx context.Context, tenantID string, req models.CreateRequest) (*models.Record, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.Record, error)
	GetStats(ctx context.Context, tenantID string) (gin.H, error)
	List(ctx context.Context, tenantID string) ([]models.Record, error)
	Search(ctx context.Context, tenantID string) ([]string, error)
	Update(ctx context.Context, tenantID, id string, req models.CreateRequest) (*models.Record, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
