// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for metadata.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the metadata service.
type ServiceInterface interface {
	AddTag(ctx context.Context, tenantID string) error
	Approve(ctx context.Context, tenantID string) error
	BatchCreate(ctx context.Context, tenantID string) error
	CheckCompatibility(ctx context.Context, tenantID string) (bool, error)
	Configure(ctx context.Context, tenantID string) error
	Create(ctx context.Context, tenantID string, req models.CreateRequest) (*models.Record, error)
	Delete(ctx context.Context, tenantID, id string) error
	DeleteTag(ctx context.Context, tenantID string) error
	Deploy(ctx context.Context, tenantID string) error
	DeregisterModel(ctx context.Context, tenantID string) error
	DisablePlugin(ctx context.Context, tenantID, name string) error
	EnablePlugin(ctx context.Context, tenantID, name string) error
	EnforcePolicy(ctx context.Context, tenantID string) error
	Escalate(ctx context.Context, tenantID string) error
	Evaluate(ctx context.Context, tenantID string) error
	Forecast(ctx context.Context, tenantID string) (gin.H, error)
	Get(ctx context.Context, tenantID, id string) (*models.Record, error)
	GetBranchStatus(ctx context.Context, tenantID string) (string, error)
	GetByUser(ctx context.Context, tenantID string) ([]string, error)
	GetConfig(ctx context.Context, tenantID string) (gin.H, error)
	GetCoverage(ctx context.Context, tenantID string) (gin.H, error)
	GetHistory(ctx context.Context, tenantID string) ([]string, error)
	GetLineage(ctx context.Context, tenantID string) (gin.H, error)
	GetLogs(ctx context.Context, tenantID string) ([]string, error)
	GetMetrics(ctx context.Context, tenantID string) (gin.H, error)
	GetPlugin(ctx context.Context, tenantID, name string) (gin.H, error)
	GetResults(ctx context.Context, tenantID string) ([]string, error)
	GetStats(ctx context.Context, tenantID string) (gin.H, error)
	GetStatus(ctx context.Context, tenantID string) (string, error)
	GetStatusMiddleware(ctx context.Context, tenantID string) (string, error)
	GetUtilization(ctx context.Context, tenantID string) (gin.H, error)
	List(ctx context.Context, tenantID string) ([]models.Record, error)
	ListAlerts(ctx context.Context, tenantID string) ([]string, error)
	ListArtifacts(ctx context.Context, tenantID string) ([]string, error)
	ListExperiments(ctx context.Context, tenantID string) ([]string, error)
	ListHistories(ctx context.Context, tenantID string) ([]string, error)
	ListModels(ctx context.Context, tenantID string) ([]string, error)
	ListPending(ctx context.Context, tenantID string) ([]string, error)
	ListPipelines(ctx context.Context, tenantID string) ([]string, error)
	ListPlugins(ctx context.Context, tenantID string) ([]string, error)
	ListSchemas(ctx context.Context, tenantID string) ([]string, error)
	ListTemplates(ctx context.Context, tenantID string) ([]string, error)
	ListTemplates2(ctx context.Context, tenantID string) ([]string, error)
	ListViolations(ctx context.Context, tenantID string) ([]string, error)
	Pause(ctx context.Context, tenantID string) error
	Regenerate(ctx context.Context, tenantID string) error
	RegisterModel(ctx context.Context, tenantID string) error
	Reject(ctx context.Context, tenantID string) error
	Restart(ctx context.Context, tenantID string) error
	Resume(ctx context.Context, tenantID string) error
	Rollback(ctx context.Context, tenantID string) error
	RunInspection(ctx context.Context, tenantID string) error
	RunPipeline(ctx context.Context, tenantID string) error
	ScaleResource(ctx context.Context, tenantID string) error
	Search(ctx context.Context, tenantID string) ([]string, error)
	Train(ctx context.Context, tenantID string) error
	Trigger(ctx context.Context, tenantID string) error
	Update(ctx context.Context, tenantID, id string, req models.CreateRequest) (*models.Record, error)
	UpdateConfig(ctx context.Context, tenantID string) error
	UpdateStatus(ctx context.Context, tenantID string) error
	ValidateBranch(ctx context.Context, tenantID string) (bool, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
