// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, tenantID string, m *models.Runbook) error
	CreateExecution(ctx context.Context, tenantID string, ex *models.RunbookExecution) error
	Delete(ctx context.Context, tenantID id string) error
	EnsureTable(ctx context.Context) error
	GetByID(ctx context.Context, tenantID id string) *models.Runbook, error
	List(ctx context.Context, tenantID string, q models.ListQuery) []models.Runbook, int, error
	ListExecutions(ctx context.Context, tenantID runbookID string, limit int) []models.RunbookExecution, error
	Update(ctx context.Context, tenantID id string, updates map[string]interface{}) *models.Runbook, error
	UpdateExecutionStatus(ctx context.Context, tenantID executionID string, status string) error
}
