// Code generated by repository interface extractor. DO NOT EDIT.

package repository

import (
	"context"
	"orion/platform-svc-go/internal/workflow-trigger/models"
)


// RepositoryInterface defines the data access contract.
type RepositoryInterface interface {
	Create(ctx context.Context, t *models.WorkflowTrigger) error
	GetByID(ctx context.Context, tenantID, id string) (*models.WorkflowTrigger, error)
	List(ctx context.Context, tenantID string, filter *models.ListFilter, offset, limit int) ([]models.WorkflowTrigger, error)
	Count(ctx context.Context, tenantID string, filter *models.ListFilter) (int, error)
	Update(ctx context.Context, t *models.WorkflowTrigger) error
	Delete(ctx context.Context, tenantID, id string) error
	SetEnabled(ctx context.Context, tenantID, id string, enabled bool) error
}
