// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, m *models.Module) error
	Delete(ctx context.Context, tenantID id string) error
	GetByID(ctx context.Context, tenantID id string) *models.Module, error
	List(ctx context.Context, tenantID string) []models.Module, error
	UpdateStatus(ctx context.Context, tenantID id string, enabled bool, status string) *models.Module, error
}
