// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for api-market.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/api-market/models"
)

// ServiceInterface defines the interface for the api-market service.
type ServiceInterface interface {
	CheckSubscription(ctx context.Context, appID string, productID string, tenantID string) (bool, error)
	CreateDeveloperApp(ctx context.Context, req *models.CreateDeveloperAppRequest, developerID string, tenantID string) (*models.DeveloperApp, error)
	CreateProduct(ctx context.Context, req *models.CreateProductRequest, ownerID string, tenantID string) (*models.Product, error)
	DeleteProduct(ctx context.Context, id string, tenantID string) (bool, error)
	GenerateAPIKey(ctx context.Context, appID string, scopes []string, tenantID string) (*GenerateAPIKeyResult, error)
	GetApp(ctx context.Context, id string, tenantID string) (*models.DeveloperApp, error)
	GetProduct(ctx context.Context, id string, tenantID string) (*models.Product, error)
	ListAPIKeys(ctx context.Context, appID string, tenantID string) ([]models.SafeAPIKey, error)
	ListAppsByDeveloper(ctx context.Context, tenantID string, developerID string) ([]models.DeveloperApp, error)
	ListProducts(ctx context.Context, tenantID string) ([]models.Product, error)
	ListSubscriptions(ctx context.Context, appID string, tenantID string) ([]models.Subscription, error)
	PublishProduct(ctx context.Context, id string, tenantID string) (*models.Product, error)
	Subscribe(ctx context.Context, req *models.SubscribeRequest, tenantID string) error
	ValidateAPIKey(ctx context.Context, tenantID string, clientID string, clientSecret string) (*models.APIKeyValidationResult, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
