// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Create(ctx context.Context, tenantID string, cb *models.CanaryTraffic) error
	Delete(ctx context.Context, id tenantID string) bool, error
	EnsureTable(ctx context.Context) error
	GetByID(ctx context.Context, id tenantID string) *models.CanaryTraffic, error
	List(ctx context.Context, tenantID string) []models.CanaryTraffic, error
	Update(ctx context.Context, id tenantID string, attrs map[string]interface{}) *models.CanaryTraffic, error
}
