// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for artifact-ops.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/artifact-ops/models"
)

// ServiceInterface defines the interface for the artifact-ops service.
type ServiceInterface interface {
	Cleanup(ctx context.Context, tenantID string) (map[string]any, error)
	DefineRetentionPolicy(ctx context.Context, tenantID string, req models.DefineRetentionPolicyRequest) (*models.RetentionPolicy, error)
	DeletePolicy(ctx context.Context, tenantID, policyID string) error
	DetectMalicious(ctx context.Context, tenantID string, req models.DetectMaliciousRequest) (*models.DetectMaliciousResult, error)
	EvaluateRetention(ctx context.Context, tenantID string, req models.EvaluateRetentionRequest) (*models.EvaluateRetentionResult, error)
	GetArtifactScanReports(ctx context.Context, tenantID, artifactID string) ([]models.ScanReport, error)
	GetArtifactStats(ctx context.Context, tenantID, artifactID string) (*models.ArtifactStats, error)
	GetOperationHistory(ctx context.Context, tenantID, artifactID string, limit, offset int) ([]models.ArtifactOperation, error)
	GetRetentionReport(ctx context.Context, tenantID string, req models.RetentionReportRequest) (*models.RetentionReport, error)
	GetScanReport(ctx context.Context, tenantID, scanID string) (*models.ScanReport, error)
	ListPolicies(ctx context.Context, tenantID string) ([]models.RetentionPolicy, error)
	ScanArtifact(ctx context.Context, tenantID, artifactID string, req models.ScanArtifactRequest) (*models.ArtifactScan, error)
	TrackOperation(ctx context.Context, tenantID, actorID string, req models.TrackOperationRequest) (*models.ArtifactOperation, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
