// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	CountTracesByTenant(ctx context.Context, tenantID string, q *models.ListTracesQuery) int64, error
	CreateTrace(ctx context.Context, t *models.LLMTrace) error
	GetCustomPricing(ctx context.Context, modelID string) *models.ModelPricing, error
	GetDailyStats(ctx context.Context, tenantID dateStr string) *models.DailyStats, error
	GetTrace(ctx context.Context, traceID tenantID string) *models.LLMTrace, error
	GetTrackingAccuracy(ctx context.Context, tenantID string) *models.TrackingAccuracy, error
	ListTracesByTenant(ctx context.Context, tenantID string, q *models.ListTracesQuery) []models.LLMTrace, error
	ListTracesByTenantAndDateRange(ctx context.Context, tenantID string, start end *time.Time) []models.LLMTrace, error
	UpdateTrace(ctx context.Context, traceID tenantID string, fields map[string]interface{}) error
}
