// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for code-repo.
// Generated to enable handler layer mocking in tests.

package service

// ServiceInterface defines the interface for the code-repo service.
type ServiceInterface interface {
	AddComment(ctx context.Context, adapterID, repoID, prID string, userID, username string, req models.CreateCommentRequest) (*models.Comment, error)
	AddReview(ctx context.Context, adapterID, repoID, prID string, userID, username string, req models.CreateReviewRequest) (*models.Review, error)
	ClosePullRequest(ctx context.Context, adapterID, repoID, prID string) error
	CreateBranch(ctx context.Context, adapterID, repoID string, req models.CreateBranchRequest) error
	CreatePullRequest(ctx context.Context, adapterID, repoID string, req models.CreatePullRequestRequest) (*models.PullRequest, error)
	DeleteBranch(ctx context.Context, adapterID, repoID, branchName string) error
	GetCommit(ctx context.Context, adapterID, repoID, sha string) (*models.Commit, error)
	GetFileDiff(ctx context.Context, adapterID, repoID string, base, head, path string) ([]models.FileDiff, error)
	GetPullRequest(ctx context.Context, adapterID, repoID, prID string) (*models.PullRequest, error)
	GetRepository(ctx context.Context, adapterID, repoID string) (*models.CodeRepo, error)
	GetWebhookSecret(ctx context.Context, repoID string) (*models.WebhookSecretResponse, error)
	ListAdapters(ctx context.Context) ([]models.CodeRepoAdapter, error)
	ListBranches(ctx context.Context, adapterID, repoID string) ([]models.Branch, error)
	ListCodeOwners(ctx context.Context, repoID string) ([]models.CodeOwner, error)
	ListComments(ctx context.Context, adapterID, repoID, prID string) ([]models.Comment, error)
	ListCommits(ctx context.Context, adapterID, repoID string, limit, offset int) ([]models.Commit, error)
	ListPullRequests(ctx context.Context, adapterID, repoID, state string) ([]models.PullRequest, error)
	ListRepositories(ctx context.Context, adapterID string) ([]models.CodeRepo, error)
	ListReviews(ctx context.Context, adapterID, repoID, prID string) ([]models.Review, error)
	ListWebhookLogs(ctx context.Context, limit, offset int) ([]map[string]any, error)
	MergePullRequest(ctx context.Context, adapterID, repoID, prID string) error
	RotateWebhookSecret(ctx context.Context, repoID, providedSecret string) (*models.WebhookSecretResponse, error)
	SetWebhookSecret(ctx context.Context, repoID, secret string) (*models.WebhookSecretResponse, error)
	UpdatePullRequest(ctx context.Context, adapterID, repoID, prID string, req models.UpdatePullRequestRequest) (*models.PullRequest, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
