// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for session.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/session/models"
)

// ServiceInterface defines the interface for the session service.
type ServiceInterface interface {
	CleanupExpired(ctx context.Context, tenantID string) (int64, error)
	Create(ctx context.Context, tenantID string, req *models.CreateSessionRequest) (*models.Session, error)
	GetByID(ctx context.Context, tenantID, id string) (*models.Session, error)
	List(ctx context.Context, tenantID, userID string, offset, limit int) ([]models.Session, error)
	Logout(ctx context.Context, tenantID, sessionID string) error
	LogoutAll(ctx context.Context, tenantID, userID string) (int64, error)
	Verify(ctx context.Context, tenantID, token string) (*models.VerifySessionResponse, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
