// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for escalation.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/escalation/models"
)

// ServiceInterface defines the interface for the escalation service.
type ServiceInterface interface {
	CreateRule(ctx context.Context, tenantID string, req models.TriggerRequest) (*models.EscalationRule, error)
	DeleteRule(ctx context.Context, tenantID, id string) error
	GetEventsByRule(ctx context.Context, tenantID, ruleID string) ([]models.TriggerEvent, error)
	GetRule(ctx context.Context, tenantID, id string) (*models.EscalationRule, error)
	GetStats(ctx context.Context, tenantID string) (*models.EscalationStats, error)
	ListRules(ctx context.Context, tenantID string, q models.ListRulesQuery) ([]models.EscalationRule, error)
	TriggerRule(ctx context.Context, tenantID, id string, req models.TriggerRequest) (*models.TriggerEvent, error)
	UpdateRule(ctx context.Context, tenantID, id string, req models.TriggerRequest) (*models.EscalationRule, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
