// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	AddTag(ctx context.Context, tenantID versionID tagName createdBy string) error
	AuditLogStats(ctx context.Context, tenantID string) map[string]interface{}, error
	BatchUpdateApprovalConfigs(ctx context.Context, tenantID string, configs []models.ApprovalConfig) error
	CreateAuditLog(ctx context.Context, m *models.AuditLog) error
	CreateCapabilityMapping(ctx context.Context, m *models.CapabilityMapping) error
	CreateCommand(ctx context.Context, m *models.ChatOpsCommand) error
	CreateCommandPermission(ctx context.Context, m *models.CommandPermission) error
	CreateCommandVersion(ctx context.Context, m *models.CommandVersion) error
	CreateEnvironmentPermission(ctx context.Context, m *models.EnvironmentPermission) error
	CreateExecution(ctx context.Context, m *models.Execution) error
	CreateMessage(ctx context.Context, m *models.ChatOpsMessage) error
	CreateRateLimit(ctx context.Context, m *models.RateLimit) error
	CreateRole(ctx context.Context, m *models.PermissionRole) error
	CreateSession(ctx context.Context, tenantID userID string) *models.ChatOpsSession, error
	CreateWebhook(ctx context.Context, m *models.Webhook) error
	DeleteCapabilityMapping(ctx context.Context, tenantID id string) error
	DeleteCommand(ctx context.Context, tenantID id string) error
	DeleteCommandPermission(ctx context.Context, tenantID id string) error
	DeleteCommandVersion(ctx context.Context, tenantID id string) error
	DeleteEnvironmentPermission(ctx context.Context, tenantID id string) error
	DeleteRateLimit(ctx context.Context, tenantID id string) error
	DeleteRole(ctx context.Context, tenantID id string) error
	DeleteWebhook(ctx context.Context, tenantID id string) error
	ExportAuditLogs(ctx context.Context, tenantID string, q *models.AuditLogQuery) []models.AuditLog, error
	GetAlertStates(ctx context.Context, tenantID userID string) []models.AlertState, error
	GetAllApprovalConfigs(ctx context.Context, tenantID string) []models.ApprovalConfig, error
	GetAllCapabilityMappings(ctx context.Context, tenantID string, environment *string) []models.CapabilityMapping, error
	GetAllCommandPermissions(ctx context.Context, tenantID string) []models.CommandPermission, error
	GetAllCommandVersions(ctx context.Context, tenantID string, limit offset int) []models.CommandVersion, int, error
	GetAllEnvironmentPermissions(ctx context.Context, tenantID string) []models.EnvironmentPermission, error
	GetAllRateLimits(ctx context.Context, tenantID string) []models.RateLimit, error
	GetAllRoles(ctx context.Context, tenantID string) []models.PermissionRole, error
	GetAllWebhooks(ctx context.Context, tenantID string) []models.Webhook, error
	GetApprovalConfigByCapability(ctx context.Context, tenantID capability string) *models.ApprovalConfig, error
	GetApproverSchedule(ctx context.Context, tenantID string) []models.ApproverSchedule, error
	GetApprovers(ctx context.Context, tenantID string) []models.Approver, error
	GetCapabilityMapping(ctx context.Context, tenantID id string) *models.CapabilityMapping, error
	GetCommand(ctx context.Context, tenantID id string) *models.ChatOpsCommand, error
	GetCommandConfigs(ctx context.Context, tenantID userID string) []models.CommandConfig, error
	GetCommandPermission(ctx context.Context, tenantID id string) *models.CommandPermission, error
	GetCommandVersion(ctx context.Context, tenantID id string) *models.CommandVersion, error
	GetDNDSettings(ctx context.Context, tenantID userID string) *models.DNDSettings, error
	GetDashboardStats(ctx context.Context, tenantID string, days int) *models.DashboardStatsResult, error
	GetEnvironmentPermission(ctx context.Context, tenantID id string) *models.EnvironmentPermission, error
	GetExecution(ctx context.Context, tenantID id string) *models.Execution, error
	GetGlobalApprovalConfig(ctx context.Context, tenantID string) *models.GlobalApprovalConfig, error
	GetKnowledgeRecommendations(ctx context.Context, tenantID string, context string, limit int) []models.KnowledgeRecommendation, error
	GetNotificationPreference(ctx context.Context, tenantID userID string) *models.NotificationPreference, error
	GetPlatformConfigs(ctx context.Context, tenantID userID string) []models.PlatformConfig, error
	GetQuestionConfigs(ctx context.Context, tenantID userID string) []models.QuestionConfig, error
	GetRateLimit(ctx context.Context, tenantID id string) *models.RateLimit, error
	GetRecommendations(ctx context.Context, tenantID userID string, currentPage resourceID string) []map[string]interface{}, error
	GetRole(ctx context.Context, tenantID id string) *models.PermissionRole, error
	GetSessionMessages(ctx context.Context, tenantID sessionID string, limit int, cursor *string) []models.ChatOpsMessage, error
	GetUserAllowedCommands(ctx context.Context, tenantID userID string) []string, error
	GetUserPermissionRequests(ctx context.Context, tenantID userID string) []map[string]interface{}, error
	GetVersionsByCommand(ctx context.Context, tenantID commandID string) []models.CommandVersion, error
	GetWebhook(ctx context.Context, tenantID id string) *models.Webhook, error
	GetWebhookLogs(ctx context.Context, tenantID webhookID string, limit int) []map[string]interface{}, error
	HealthCheck(ctx context.Context) *models.HealthCheckResult, error
	ListAuditLogs(ctx context.Context, tenantID string, q *models.AuditLogQuery) []models.AuditLog, error
	ListCommands(ctx context.Context, tenantID string, permissionLevel name *string, limit offset int) []models.ChatOpsCommand, error
	ListExecutions(ctx context.Context, tenantID string, commandID userID status *string, limit offset int) []models.Execution, error
	RemoveTag(ctx context.Context, tenantID versionID tagName string) error
	TestWebhook(ctx context.Context, tenantID webhookID string) *models.TestWebhookResult, error
	UpdateAlertState(ctx context.Context, tenantID userID alertID status string) error
	UpdateApproverSchedule(ctx context.Context, tenantID string, schedule []models.ApproverSchedule) error
	UpdateCapabilityMapping(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpdateCommand(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpdateCommandPermission(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpdateEnvironmentPermission(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpdateExecutionStatus(ctx context.Context, tenantID id status string) error
	UpdateRateLimit(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpdateRole(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpdateWebhook(ctx context.Context, tenantID id string, updates map[string]interface{}) error
	UpsertApprovalConfig(ctx context.Context, tenantID capability string, enabled *bool, approvers *string, threshold *int) error
	UpsertCommandConfigs(ctx context.Context, tenantID userID string, configs []models.CommandConfig) error
	UpsertDNDSettings(ctx context.Context, m *models.DNDSettings) error
	UpsertGlobalApprovalConfig(ctx context.Context, tenantID string, config *models.GlobalApprovalConfig) error
	UpsertNotificationPreference(ctx context.Context, m *models.NotificationPreference) error
	UpsertPlatformConfigs(ctx context.Context, tenantID userID string, configs []models.PlatformConfig) error
	UpsertQuestionConfigs(ctx context.Context, tenantID userID string, configs []models.QuestionConfig) error
}
