package executor

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestPITRManifestPath_Joins(t *testing.T) {
	got := PITRManifestPath("/scratch", "b-1")
	want := filepath.Join("/scratch", "pitr-b-1-manifest.json")
	if got != want {
		t.Fatalf("got %q want %q", got, want)
	}
}

func TestPITRScriptPath_Joins(t *testing.T) {
	got := PITRScriptPath("/scratch", "b-2")
	want := filepath.Join("/scratch", "pitr-b-2.sh")
	if got != want {
		t.Fatalf("got %q want %q", got, want)
	}
}

func TestPreparePGRecoveryPlan_RequiresBackupID(t *testing.T) {
	_, err := PreparePGRecoveryPlan(context.Background(), PGRecoveryOptions{}, nil)
	if err == nil {
		t.Fatal("expected error when backup id missing")
	}
	if !strings.Contains(err.Error(), "backup id") {
		t.Fatalf("unexpected error %v", err)
	}
}

func TestPreparePGRecoveryPlan_RequiresBackupPath(t *testing.T) {
	_, err := PreparePGRecoveryPlan(context.Background(), PGRecoveryOptions{
		BackupID: "b-1",
	}, nil)
	if err == nil {
		t.Fatal("expected error when backup path missing")
	}
}

func TestPreparePGRecoveryPlan_EmptyArchivesOK(t *testing.T) {
	scratch := t.TempDir()
	plan, err := PreparePGRecoveryPlan(context.Background(), PGRecoveryOptions{
		BackupID:   "b-empty",
		BackupPath: "/var/backups/base.dump",
		ScratchDir: scratch,
	}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if plan == nil {
		t.Fatal("expected non-nil plan")
	}
	if plan.BackupID != "b-empty" {
		t.Fatalf("backup id mismatch %q", plan.BackupID)
	}
	if plan.ManifestSHA256 == "" {
		t.Fatal("manifest sha256 must be set")
	}
	if plan.ScriptPath == "" || !fileExists(plan.ScriptPath) {
		t.Fatalf("script not written: %q", plan.ScriptPath)
	}
	script, err := os.ReadFile(plan.ScriptPath)
	if err != nil {
		t.Fatal(err)
	}
	s := string(script)
	if !strings.HasPrefix(s, "#!/usr/bin/env bash") {
		t.Fatalf("script missing shebang: %q", s[:min(30, len(s))])
	}
	if !strings.Contains(s, "set -euo pipefail") {
		t.Fatal("script missing set -euo pipefail")
	}
	if !strings.Contains(s, "Auto-generated by orion-platform-svc") {
		t.Fatal("script missing generated-by header")
	}
}

func TestPreparePGRecoveryPlan_CopiesAndHashesArchives(t *testing.T) {
	scratch := t.TempDir()
	srcDir := t.TempDir()
	src1 := filepath.Join(srcDir, "000000010000000000000001")
	src2 := filepath.Join(srcDir, "000000010000000000000002")
	content1 := []byte("wal-segment-1")
	content2 := []byte("wal-segment-2")
	if err := os.WriteFile(src1, content1, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(src2, content2, 0o600); err != nil {
		t.Fatal(err)
	}

	plan, err := PreparePGRecoveryPlan(context.Background(), PGRecoveryOptions{
		BackupID:     "b-hash",
		BackupPath:   "/var/backups/base.dump",
		ArchivePaths: []string{src1, src2},
		ScratchDir:   scratch,
	}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.ArchiveFiles) != 2 {
		t.Fatalf("expected 2 archive files, got %d", len(plan.ArchiveFiles))
	}
	// Verify the copied file contents and that the SHA256 matches.
	for _, af := range plan.ArchiveFiles {
		if !fileExists(af.Path) {
			t.Fatalf("archive copy missing: %s", af.Path)
		}
		got, err := os.ReadFile(af.Path)
		if err != nil {
			t.Fatal(err)
		}
		sum := sha256.Sum256(got)
		if hex.EncodeToString(sum[:]) != af.SHA256 {
			t.Fatalf("sha mismatch for %s: %s vs %s", af.Path, af.SHA256, hex.EncodeToString(sum[:]))
		}
	}
	script, err := os.ReadFile(plan.ScriptPath)
	if err != nil {
		t.Fatal(err)
	}
	s := string(script)
	for _, af := range plan.ArchiveFiles {
		if !strings.Contains(s, af.Path) {
			t.Fatalf("script missing path %s", af.Path)
		}
		if !strings.Contains(s, af.SHA256) {
			t.Fatalf("script missing sha %s", af.SHA256)
		}
	}
}

func TestPreparePGRecoveryPlan_EmptyArchivePathFails(t *testing.T) {
	dir := t.TempDir()
	f1 := filepath.Join(dir, "seg1")
	if err := os.WriteFile(f1, []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	_, err := PreparePGRecoveryPlan(context.Background(), PGRecoveryOptions{
		BackupID:     "b-err",
		BackupPath:   "/var/backups/base.dump",
		ArchivePaths: []string{f1, ""},
		ScratchDir:   t.TempDir(),
	}, nil)
	if err == nil {
		t.Fatal("expected error for empty archive path")
	}
	if !strings.Contains(err.Error(), "empty path") {
		t.Fatalf("unexpected error %v", err)
	}
}

func TestPreparePGRecoveryPlan_MissingArchiveFails(t *testing.T) {
	_, err := PreparePGRecoveryPlan(context.Background(), PGRecoveryOptions{
		BackupID:     "b-err",
		BackupPath:   "/var/backups/base.dump",
		ArchivePaths: []string{"/tmp/definitely-not-exists-wal-12345"},
		ScratchDir:   t.TempDir(),
	}, nil)
	if err == nil {
		t.Fatal("expected error for missing archive file")
	}
}

func TestPreparePGRecoveryPlan_CancelsOnContextDone(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	_, err := PreparePGRecoveryPlan(ctx, PGRecoveryOptions{
		BackupID:     "b-cancel",
		BackupPath:   "/var/backups/base.dump",
		ArchivePaths: []string{"/tmp/whatever"},
		ScratchDir:   t.TempDir(),
	}, nil)
	if err == nil {
		t.Fatal("expected error when context already cancelled")
	}
}

func TestPreparePGRecoveryPlan_DefaultScratchDir(t *testing.T) {
	// Just verify the function returns the default ScratchDir path when unset.
	// We don't actually write to /var/lib/orion-pitr — the empty archive path
	// branch triggers before any file writes.
	_, err := PreparePGRecoveryPlan(context.Background(), PGRecoveryOptions{
		BackupID:     "b-default",
		BackupPath:   "/var/backups/base.dump",
		ArchivePaths: []string{""},
	}, nil)
	// The default scratch dir will be created (mkdir). If it fails (perm),
	// we still want the empty archive path error. Either error is acceptable
	// here; the point is not to panic.
	if err == nil {
		t.Fatal("expected error (empty archive path or scratch dir creation)")
	}
}

func TestPreparePGRecoveryPlan_TargetTimeEmitted(t *testing.T) {
	scratch := t.TempDir()
	tt := time.Date(2026, 7, 1, 12, 0, 0, 0, time.UTC)
	plan, err := PreparePGRecoveryPlan(context.Background(), PGRecoveryOptions{
		BackupID:   "b-time",
		BackupPath: "/var/backups/base.dump",
		TargetTime: &tt,
		ScratchDir: scratch,
	}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if plan.TargetTime == nil || !plan.TargetTime.Equal(tt) {
		t.Fatalf("target time mismatch: %v", plan.TargetTime)
	}
	script, _ := os.ReadFile(plan.ScriptPath)
	s := string(script)
	if !strings.Contains(s, "recovery_target_time") {
		t.Fatalf("script missing recovery_target_time line")
	}
}

func TestBuildPGRecoveryScript_AllStepsCommented(t *testing.T) {
	s := buildPGRecoveryScript(PGRecoveryPlan{
		BackupID:   "b-1",
		BackupPath: "/var/backups/base.dump",
		ArchiveDir: "/var/lib/orion-pitr/pitr-b-1",
		ArchiveFiles: []ArchiveFileInfo{
			{Path: "/x/seg1", SHA256: "abc"},
		},
		GeneratedAt: time.Date(2026, 7, 1, 0, 0, 0, 0, time.UTC),
	})
	// All DB-mutating commands must be commented.
	for _, cmd := range []string{"pg_restore", "pg_ctl", "restore_command", "recovery_target_inclusive"} {
		if idx := strings.Index(s, cmd); idx < 0 {
			t.Fatalf("missing %s in script", cmd)
		} else {
			line := extractLine(idx, s)
			trimmed := strings.TrimSpace(line)
			if !strings.HasPrefix(trimmed, "#") {
				t.Fatalf("command %s not commented: %q", cmd, line)
			}
		}
	}
}

func TestCopyFile_CopiesAndSetsMode(t *testing.T) {
	src := filepath.Join(t.TempDir(), "src")
	if err := os.WriteFile(src, []byte("hello"), 0o644); err != nil {
		t.Fatal(err)
	}
	dst := filepath.Join(t.TempDir(), "dst")
	if err := copyFile(src, dst); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(dst)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "hello" {
		t.Fatalf("content mismatch %q", got)
	}
	fi, err := os.Stat(dst)
	if err != nil {
		t.Fatal(err)
	}
	if fi.Mode().Perm() != 0o600 {
		t.Fatalf("expected 0600 perms, got %v", fi.Mode().Perm())
	}
}

func TestCopyFile_SrcMissingFails(t *testing.T) {
	dst := filepath.Join(t.TempDir(), "dst")
	err := copyFile("/tmp/definitely-not-exists-src", dst)
	if err == nil {
		t.Fatal("expected error when src missing")
	}
}

func TestHashString_Deterministic(t *testing.T) {
	a := hashString("abc")
	b := hashString("abc")
	if a != b {
		t.Fatalf("hashString not deterministic: %s vs %s", a, b)
	}
	c := hashString("abd")
	if c == a {
		t.Fatal("different inputs produced same hash")
	}
	if len(a) != 64 {
		t.Fatalf("sha256 hex should be 64 chars, got %d", len(a))
	}
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

func extractLine(idx int, s string) string {
	start := idx
	for start > 0 && s[start-1] != '\n' {
		start--
	}
	end := idx
	for end < len(s) && s[end] != '\n' {
		end++
	}
	return s[start:end]
}
