// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for handler-registry.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/handler-registry/models"
)

// ServiceInterface defines the interface for the handler-registry service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateHandlerRegistryRequest) (*models.HandlerRegistry, error)
	Delete(ctx context.Context, tenantID, id string) error
	Disable(ctx context.Context, tenantID, domain, name string) error
	Enable(ctx context.Context, tenantID, domain, name string) error
	Get(ctx context.Context, tenantID, id string) (*models.HandlerRegistry, error)
	GetDomains(ctx context.Context, tenantID string) ([]string, error)
	GetEntry(ctx context.Context, tenantID, domain, name string) (*models.HandlerRegistryEntry, error)
	HealthCheck(ctx context.Context) (map[string]any, error)
	Invoke(ctx context.Context, tenantID, domain, name string, payload map[string]any) (map[string]any, error)
	List(ctx context.Context, tenantID string, limit, offset int) ([]models.HandlerRegistry, error)
	ListEntries(ctx context.Context, tenantID string, opts models.ListHandlerRegistryOptions) ([]models.HandlerRegistryEntry, error)
	RegisterHandler(ctx context.Context, tenantID string, req models.RegisterHandlerRequest) (*models.HandlerRegistryEntry, error)
	Unregister(ctx context.Context, tenantID, domain, name string) error
	Update(ctx context.Context, tenantID, id string, req models.UpdateHandlerRegistryRequest) (*models.HandlerRegistry, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
