// Code generated by tools/generate_service_interface.go. DO NOT EDIT.
//
// This file defines the ServiceInterface for self-service.
// Generated to enable handler layer mocking in tests.

package service

import (
	"context"
	"orion/platform-svc-go/internal/self-service/models"
)

// ServiceInterface defines the interface for the self-service service.
type ServiceInterface interface {
	Create(ctx context.Context, tenantID string, req models.CreateSelfServiceRequest) (*models.SelfService, error)
	Delete(ctx context.Context, tenantID, id string) error
	Get(ctx context.Context, tenantID, id string) (*models.SelfService, error)
	List(ctx context.Context, tenantID string) ([]models.SelfService, error)
	Update(ctx context.Context, tenantID, id string, req models.UpdateSelfServiceRequest) (*models.SelfService, error)
}

// Ensure compile-time safety: *Service implements ServiceInterface.
var _ ServiceInterface = (*Service)(nil)
