apiVersion: v1
kind: Service
metadata:
  name: orion-community-svc
  namespace: orion
  labels:
    app: orion-community
    component: community-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3029
      protocol: TCP
      name: http
  selector:
    app: orion-community
---
apiVersion: v1
kind: Service
metadata:
  name: orion-community-svc-headless
  namespace: orion
  labels:
    app: orion-community
    component: community-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3029
      targetPort: 3029
      protocol: TCP
      name: http
  selector:
    app: orion-community