// Code generated by tools/gen-interface/main.go. DO NOT EDIT.
package repository

import (
	"context"
)

type Repository interface {
	Count(ctx context.Context, tenantID string, filter *ListFilter) int64, error
	CreateDecision(ctx context.Context, d *models.AIDecision) error
	CreateFeedback(ctx context.Context, fb *models.DecisionFeedback) error
	CreateTrace(ctx context.Context, t *models.DecisionTrace) error
	CreateTraces(ctx context.Context, traces []*models.DecisionTrace) error
	Delete(ctx context.Context, id string, tenantID string) bool, error
	DeleteFeedbacks(ctx context.Context, decisionID string, tenantID string) error
	DeleteTraces(ctx context.Context, decisionID string, tenantID string) error
	GetByID(ctx context.Context, id string, tenantID string) *models.AIDecision, error
	GetFeedbacks(ctx context.Context, decisionID string, tenantID string) []models.DecisionFeedback, error
	GetStats(ctx context.Context, tenantID string, dateRange *models.DateRange) *models.DecisionStats, error
	GetTraces(ctx context.Context, decisionID string, tenantID string) []models.DecisionTrace, error
	List(ctx context.Context, tenantID string, filter *ListFilter) []models.AIDecision, error
	UpdateDecisionStatus(ctx context.Context, id string, tenantID string, status models.DecisionStatus, executedAt *int64) *models.AIDecision, error
}
